/**
 * FR/EN/AR labels for content delivery (kept local to avoid bloating translations.js).
 */

import { normalizeLanguage } from '../utils/translations';

const labels = {
  en: {
    cdNewStories: 'New stories available!',
    cdUpdateNow: 'Update now',
    cdLater: 'Later',
    cdDownloading: 'Downloading…',
    cdProgress: '{percent}%',
    cdEta: 'About {eta} left',
    cdPause: 'Pause',
    cdResume: 'Resume',
    cdCancel: 'Cancel',
    cdApplied: 'Content updated',
    cdFailed: 'Update failed — previous version kept',
    cdRolledBack: 'Rolled back safely',
    cdStorageTitle: 'Downloads & storage',
    cdDownloadedSize: 'Downloaded',
    cdAvailableStorage: 'Available',
    cdLastSync: 'Last sync',
    cdRemovePack: 'Remove pack',
    cdRedownload: 'Redownload',
    cdClearCache: 'Clear cache',
    cdOptimize: 'Optimize storage',
    cdPacksTitle: 'Content packs',
    cdDownloadPack: 'Download',
    cdHistoryTitle: 'Content updates',
    cdRecentlyAdded: 'Recently added',
    cdUpdatedStories: 'Updated stories',
    cdRemovedStories: 'Removed stories',
    cdNewQuizzes: 'New quizzes',
    cdNewGames: 'New games',
    cdNewWorlds: 'New educational worlds',
    cdNoHistory: 'No updates yet',
    cdCatalogVersion: 'Catalog',
    cdAdminTitle: 'Catalog versions',
    cdAdminSubtitle: 'Publish live content updates without a new app release.',
    cdCreateVersion: 'Create version',
    cdPublish: 'Publish',
    cdRollback: 'Rollback',
    cdArchive: 'Archive',
    cdFeature: 'Feature',
    cdSchedule: 'Schedule',
    cdChangelogHint: 'Changelog entry',
    cdBumpPatch: 'Patch',
    cdBumpMinor: 'Minor',
    cdBumpMajor: 'Major',
    cdPackageSize: 'Package size',
    cdStatusDraft: 'Draft',
    cdStatusPublished: 'Published',
    cdStatusScheduled: 'Scheduled',
    cdStatusArchived: 'Archived',
    cdCurrent: 'Current',
  },
  fr: {
    cdNewStories: 'Nouvelles histoires disponibles !',
    cdUpdateNow: 'Mettre à jour',
    cdLater: 'Plus tard',
    cdDownloading: 'Téléchargement…',
    cdProgress: '{percent} %',
    cdEta: 'Environ {eta} restantes',
    cdPause: 'Pause',
    cdResume: 'Reprendre',
    cdCancel: 'Annuler',
    cdApplied: 'Contenu mis à jour',
    cdFailed: 'Échec — version précédente conservée',
    cdRolledBack: 'Retour arrière sécurisé',
    cdStorageTitle: 'Téléchargements & stockage',
    cdDownloadedSize: 'Téléchargé',
    cdAvailableStorage: 'Disponible',
    cdLastSync: 'Dernière sync',
    cdRemovePack: 'Retirer le pack',
    cdRedownload: 'Retélécharger',
    cdClearCache: 'Vider le cache',
    cdOptimize: 'Optimiser',
    cdPacksTitle: 'Packs de contenu',
    cdDownloadPack: 'Télécharger',
    cdHistoryTitle: 'Mises à jour contenu',
    cdRecentlyAdded: 'Ajouts récents',
    cdUpdatedStories: 'Histoires mises à jour',
    cdRemovedStories: 'Histoires retirées',
    cdNewQuizzes: 'Nouveaux quiz',
    cdNewGames: 'Nouveaux jeux',
    cdNewWorlds: 'Nouveaux mondes éducatifs',
    cdNoHistory: 'Pas encore de mises à jour',
    cdCatalogVersion: 'Catalogue',
    cdAdminTitle: 'Versions du catalogue',
    cdAdminSubtitle: 'Publiez du contenu en direct sans nouvelle version de l’app.',
    cdCreateVersion: 'Créer une version',
    cdPublish: 'Publier',
    cdRollback: 'Rollback',
    cdArchive: 'Archiver',
    cdFeature: 'Mettre en avant',
    cdSchedule: 'Planifier',
    cdChangelogHint: 'Entrée du journal',
    cdBumpPatch: 'Patch',
    cdBumpMinor: 'Mineure',
    cdBumpMajor: 'Majeure',
    cdPackageSize: 'Taille du paquet',
    cdStatusDraft: 'Brouillon',
    cdStatusPublished: 'Publié',
    cdStatusScheduled: 'Planifié',
    cdStatusArchived: 'Archivé',
    cdCurrent: 'Actuel',
  },
  ar: {
    cdNewStories: 'قصص جديدة متاحة!',
    cdUpdateNow: 'حدّث الآن',
    cdLater: 'لاحقًا',
    cdDownloading: 'جارٍ التنزيل…',
    cdProgress: '{percent}%',
    cdEta: 'يتبقى حوالي {eta}',
    cdPause: 'إيقاف مؤقت',
    cdResume: 'استئناف',
    cdCancel: 'إلغاء',
    cdApplied: 'تم تحديث المحتوى',
    cdFailed: 'فشل التحديث — تم الإبقاء على النسخة السابقة',
    cdRolledBack: 'تم التراجع بأمان',
    cdStorageTitle: 'التنزيلات والتخزين',
    cdDownloadedSize: 'تم التنزيل',
    cdAvailableStorage: 'المتاح',
    cdLastSync: 'آخر مزامنة',
    cdRemovePack: 'إزالة الحزمة',
    cdRedownload: 'إعادة التنزيل',
    cdClearCache: 'مسح الذاكرة',
    cdOptimize: 'تحسين التخزين',
    cdPacksTitle: 'حزم المحتوى',
    cdDownloadPack: 'تنزيل',
    cdHistoryTitle: 'تحديثات المحتوى',
    cdRecentlyAdded: 'أضيف مؤخرًا',
    cdUpdatedStories: 'قصص محدّثة',
    cdRemovedStories: 'قصص محذوفة',
    cdNewQuizzes: 'اختبارات جديدة',
    cdNewGames: 'ألعاب جديدة',
    cdNewWorlds: 'عوالم تعليمية جديدة',
    cdNoHistory: 'لا تحديثات بعد',
    cdCatalogVersion: 'الكتالوج',
    cdAdminTitle: 'إصدارات الكتالوج',
    cdAdminSubtitle: 'انشر المحتوى مباشرة دون إصدار تطبيق جديد.',
    cdCreateVersion: 'إنشاء إصدار',
    cdPublish: 'نشر',
    cdRollback: 'تراجع',
    cdArchive: 'أرشفة',
    cdFeature: 'تمييز',
    cdSchedule: 'جدولة',
    cdChangelogHint: 'سجل التغييرات',
    cdBumpPatch: 'تصحيح',
    cdBumpMinor: 'ثانوي',
    cdBumpMajor: 'رئيسي',
    cdPackageSize: 'حجم الحزمة',
    cdStatusDraft: 'مسودة',
    cdStatusPublished: 'منشور',
    cdStatusScheduled: 'مجدول',
    cdStatusArchived: 'مؤرشف',
    cdCurrent: 'الحالي',
  },
};

export function cdLabel(key, language = 'fr', vars = {}) {
  const lang = normalizeLanguage(language);
  const dict = labels[lang] || labels.fr;
  let text = dict[key] || labels.en[key] || key;
  Object.entries(vars).forEach(([k, v]) => {
    text = text.replace(`{${k}}`, String(v));
  });
  return text;
}
