/**
 * FR / EN / AR labels for Educational Worlds (keeps translations.js lean).
 */
import { normalizeLanguage } from '../utils/translations';

const labels = {
  en: {
    eduWorldAlphabet: 'Alphabet',
    eduWorldAlphabetDesc: 'Discover letters through playful puzzles.',
    eduWorldNumbers: 'Numbers',
    eduWorldNumbersDesc: 'Count, compare, and play with numbers.',
    eduWorldColors: 'Colors',
    eduWorldColorsDesc: 'Match and name bright colors.',
    eduWorldShapes: 'Shapes',
    eduWorldShapesDesc: 'Find circles, squares, and more.',
    eduWorldLogic: 'Logic',
    eduWorldLogicDesc: 'Patterns, memory, and smart thinking.',
    eduWorldMath: 'Mathematics',
    eduWorldMathDesc: 'Gentle math adventures.',
    eduWorldScience: 'Science',
    eduWorldScienceDesc: 'Observe and discover the world.',
    eduWorldGeography: 'Geography',
    eduWorldGeographyDesc: 'Places, maps, and cultures.',
    eduWorldAnimals: 'Animals',
    eduWorldAnimalsDesc: 'Meet pets and wild friends.',
    eduWorldSpace: 'Space',
    eduWorldSpaceDesc: 'Planets, stars, and rockets.',
    eduWorldDinos: 'Dinosaurs',
    eduWorldDinosDesc: 'Roar into prehistoric fun.',
    eduWorldMusic: 'Music',
    eduWorldMusicDesc: 'Listen, rhythm, and melodies.',
    eduWorldNature: 'Nature',
    eduWorldNatureDesc: 'Plants, weather, and outdoors.',
    eduWorldCreativity: 'Creativity',
    eduWorldCreativityDesc: 'Imagine and create freely.',
    eduWorldEmotions: 'Emotions',
    eduWorldEmotionsDesc: 'Name and share feelings.',
    eduWorldKindness: 'Kindness',
    eduWorldKindnessDesc: 'Share, help, and care.',
    eduWorldCulture: 'Culture & Values',
    eduWorldCultureDesc: 'Words, values, and traditions.',
    eduPathLettersAF: 'Letters A–F',
    eduPathLettersGL: 'Letters G–L',
    eduPathLettersMR: 'Letters M–R',
    eduPathLettersSZ: 'Letters S–Z',
    eduPathAlphabetMaster: 'Alphabet Master',
    eduPathNumbers15: 'Numbers 1–5',
    eduPathNumbers610: 'Numbers 6–10',
    eduPathNumbersMaster: 'Numbers Master',
    eduPathColorsPrimary: 'Primary colors',
    eduPathColorsMix: 'Mix & match',
    eduPathColorsMaster: 'Color Master',
    eduPathShapesBasic: 'Basic shapes',
    eduPathShapesComplex: 'Shape hunt',
    eduPathShapesMaster: 'Shape Master',
    eduPathLogicPatterns: 'Patterns',
    eduPathLogicMemory: 'Memory',
    eduPathLogicMaster: 'Logic Master',
    eduPathMathCount: 'Counting',
    eduPathMathAdd: 'Adding',
    eduPathMathMaster: 'Math Genius',
    eduPathScienceObserve: 'Observe',
    eduPathScienceDiscover: 'Discover',
    eduPathScienceMaster: 'Science Star',
    eduPathGeoPlaces: 'Places',
    eduPathGeoWorld: 'Our world',
    eduPathGeoMaster: 'Explorer',
    eduPathAnimalsPets: 'Pets',
    eduPathAnimalsWild: 'Wild animals',
    eduPathAnimalsMaster: 'Animal Expert',
    eduPathSpacePlanets: 'Planets',
    eduPathSpaceStars: 'Stars',
    eduPathSpaceMaster: 'Space Explorer',
    eduPathDinoNames: 'Dino names',
    eduPathDinoFacts: 'Dino facts',
    eduPathDinoMaster: 'Dino Master',
    eduPathMusicListen: 'Listen',
    eduPathMusicRhythm: 'Rhythm',
    eduPathMusicMaster: 'Music Star',
    eduPathNaturePlants: 'Plants',
    eduPathNatureWeather: 'Weather',
    eduPathNatureMaster: 'Nature Friend',
    eduPathCreativityImagine: 'Imagine',
    eduPathCreativityCreate: 'Create',
    eduPathCreativityMaster: 'Creator',
    eduPathEmotionsFeelings: 'Feelings',
    eduPathEmotionsExpress: 'Express',
    eduPathEmotionsMaster: 'Heart Star',
    eduPathKindnessShare: 'Share',
    eduPathKindnessHelp: 'Help',
    eduPathKindnessMaster: 'Kindness Hero',
    eduPathCultureWords: 'Words',
    eduPathCultureValues: 'Values',
    eduPathCultureMaster: 'Culture Star',
    eduBadgeFirstStory: 'First Story',
    eduBadgeReadingExplorer: 'Reading Explorer',
    eduBadgeAnimalExpert: 'Animal Expert',
    eduBadgeSpaceExplorer: 'Space Explorer',
    eduBadgeMathGenius: 'Math Genius',
    eduBadgeDailyReader: 'Daily Reader',
    eduBadgeStreak7: '7-Day Streak',
    eduBadgeQuizChampion: 'Quiz Champion',
    eduBadgeStoryCollector: 'Story Collector',
    eduBadgeAlphabetMaster: 'Alphabet Master',
    eduHubTitle: 'Educational Worlds',
    eduHubSubtitle: 'Pick a world, play challenges, earn stars!',
    eduContinueLearning: 'Continue Learning',
    eduRecommended: 'Recommended For You',
    eduPracticeAgain: 'Practice Again',
    eduNewChallenge: 'New Challenge',
    eduExploreMore: 'Explore More',
    eduLearningPath: 'Learning Path',
    eduChallenges: 'Challenges',
    eduActivities: 'Activities',
    eduLevel: 'Level {level}',
    eduXp: '{xp} XP',
    eduStars: 'Stars',
    eduDailyReward: 'Daily reward',
    eduClaimReward: 'Claim +{xp} XP',
    eduRewardClaimed: 'Reward claimed today!',
    eduDashboardTitle: 'My Learning',
    eduStoriesDone: 'Activities done',
    eduChallengesDone: 'Challenges done',
    eduQuizScore: 'Quiz score',
    eduWorldsExplored: 'Worlds explored',
    eduTimeSpent: 'Time learning',
    eduWeekly: 'This week',
    eduMonthly: 'This month',
    eduNextRec: 'Next for you',
    eduBackWorlds: 'All worlds',
    eduMatchTitle: 'Match the pairs',
    eduMatchHint: 'Tap one, then its match',
    eduFindTitle: 'Find the right one',
    eduCountTitle: 'How many?',
    eduSequenceTitle: 'Complete the sequence',
    eduParentLearningTitle: 'Educational progress',
    eduParentLearningDesc: 'Worlds, challenges, quiz results, and time spent learning.',
    eduParentFavoriteWorlds: 'Favorite worlds',
    eduParentBySubject: 'Time by subject',
    eduParentAchievements: 'Achievements',
    eduMinutes: '{n} min',
    eduMasterUnlocked: 'Master badge unlocked!',
    eduPlayChallenge: 'Play',
    eduChallengeComplete: 'Challenge complete!',
  },
  fr: {
    eduWorldAlphabet: 'Alphabet',
    eduWorldAlphabetDesc: 'Découvre les lettres en s’amusant.',
    eduWorldNumbers: 'Chiffres',
    eduWorldNumbersDesc: 'Compte et joue avec les nombres.',
    eduWorldColors: 'Couleurs',
    eduWorldColorsDesc: 'Associe et nomme les couleurs.',
    eduWorldShapes: 'Formes',
    eduWorldShapesDesc: 'Trouve cercles, carrés et plus.',
    eduWorldLogic: 'Logique',
    eduWorldLogicDesc: 'Suites, mémoire et réflexion.',
    eduWorldMath: 'Mathématiques',
    eduWorldMathDesc: 'Douces aventures de maths.',
    eduWorldScience: 'Sciences',
    eduWorldScienceDesc: 'Observe et découvre le monde.',
    eduWorldGeography: 'Géographie',
    eduWorldGeographyDesc: 'Lieux, cartes et cultures.',
    eduWorldAnimals: 'Animaux',
    eduWorldAnimalsDesc: 'Animaux de compagnie et sauvages.',
    eduWorldSpace: 'Espace',
    eduWorldSpaceDesc: 'Planètes, étoiles et fusées.',
    eduWorldDinos: 'Dinosaures',
    eduWorldDinosDesc: 'Aventures préhistoriques.',
    eduWorldMusic: 'Musique',
    eduWorldMusicDesc: 'Écoute, rythme et mélodies.',
    eduWorldNature: 'Nature',
    eduWorldNatureDesc: 'Plantes, météo et plein air.',
    eduWorldCreativity: 'Créativité',
    eduWorldCreativityDesc: 'Imagine et crée librement.',
    eduWorldEmotions: 'Émotions',
    eduWorldEmotionsDesc: 'Nomme et partage tes émotions.',
    eduWorldKindness: 'Gentillesse',
    eduWorldKindnessDesc: 'Partage, aide et bienveillance.',
    eduWorldCulture: 'Culture & Valeurs',
    eduWorldCultureDesc: 'Mots, valeurs et traditions.',
    eduPathLettersAF: 'Lettres A–F',
    eduPathLettersGL: 'Lettres G–L',
    eduPathLettersMR: 'Lettres M–R',
    eduPathLettersSZ: 'Lettres S–Z',
    eduPathAlphabetMaster: 'Maître Alphabet',
    eduPathNumbers15: 'Nombres 1–5',
    eduPathNumbers610: 'Nombres 6–10',
    eduPathNumbersMaster: 'Maître Nombres',
    eduPathColorsPrimary: 'Couleurs primaires',
    eduPathColorsMix: 'Mélange & associe',
    eduPathColorsMaster: 'Maître Couleurs',
    eduPathShapesBasic: 'Formes de base',
    eduPathShapesComplex: 'Chasse aux formes',
    eduPathShapesMaster: 'Maître Formes',
    eduPathLogicPatterns: 'Suites',
    eduPathLogicMemory: 'Mémoire',
    eduPathLogicMaster: 'Maître Logique',
    eduPathMathCount: 'Compter',
    eduPathMathAdd: 'Additionner',
    eduPathMathMaster: 'Génie Maths',
    eduPathScienceObserve: 'Observer',
    eduPathScienceDiscover: 'Découvrir',
    eduPathScienceMaster: 'Étoile Sciences',
    eduPathGeoPlaces: 'Lieux',
    eduPathGeoWorld: 'Notre monde',
    eduPathGeoMaster: 'Explorateur',
    eduPathAnimalsPets: 'Animaux familiers',
    eduPathAnimalsWild: 'Animaux sauvages',
    eduPathAnimalsMaster: 'Expert Animaux',
    eduPathSpacePlanets: 'Planètes',
    eduPathSpaceStars: 'Étoiles',
    eduPathSpaceMaster: 'Explorateur Spatial',
    eduPathDinoNames: 'Noms de dinos',
    eduPathDinoFacts: 'Faits dinos',
    eduPathDinoMaster: 'Maître Dinos',
    eduPathMusicListen: 'Écouter',
    eduPathMusicRhythm: 'Rythme',
    eduPathMusicMaster: 'Étoile Musique',
    eduPathNaturePlants: 'Plantes',
    eduPathNatureWeather: 'Météo',
    eduPathNatureMaster: 'Ami Nature',
    eduPathCreativityImagine: 'Imaginer',
    eduPathCreativityCreate: 'Créer',
    eduPathCreativityMaster: 'Créateur',
    eduPathEmotionsFeelings: 'Sentiments',
    eduPathEmotionsExpress: 'Exprimer',
    eduPathEmotionsMaster: 'Étoile Cœur',
    eduPathKindnessShare: 'Partager',
    eduPathKindnessHelp: 'Aider',
    eduPathKindnessMaster: 'Héros Gentillesse',
    eduPathCultureWords: 'Mots',
    eduPathCultureValues: 'Valeurs',
    eduPathCultureMaster: 'Étoile Culture',
    eduBadgeFirstStory: 'Première Histoire',
    eduBadgeReadingExplorer: 'Explorateur Lecture',
    eduBadgeAnimalExpert: 'Expert Animaux',
    eduBadgeSpaceExplorer: 'Explorateur Spatial',
    eduBadgeMathGenius: 'Génie Maths',
    eduBadgeDailyReader: 'Lecteur du Jour',
    eduBadgeStreak7: 'Série 7 Jours',
    eduBadgeQuizChampion: 'Champion Quiz',
    eduBadgeStoryCollector: 'Collectionneur',
    eduBadgeAlphabetMaster: 'Maître Alphabet',
    eduHubTitle: 'Mondes éducatifs',
    eduHubSubtitle: 'Choisis un monde, relève des défis, gagne des étoiles !',
    eduContinueLearning: 'Continuer à apprendre',
    eduRecommended: 'Recommandé pour toi',
    eduPracticeAgain: 'Réviser',
    eduNewChallenge: 'Nouveau défi',
    eduExploreMore: 'Explorer plus',
    eduLearningPath: 'Parcours',
    eduChallenges: 'Défis',
    eduActivities: 'Activités',
    eduLevel: 'Niveau {level}',
    eduXp: '{xp} XP',
    eduStars: 'Étoiles',
    eduDailyReward: 'Récompense du jour',
    eduClaimReward: 'Récupérer +{xp} XP',
    eduRewardClaimed: 'Récompense déjà prise !',
    eduDashboardTitle: 'Mon apprentissage',
    eduStoriesDone: 'Activités terminées',
    eduChallengesDone: 'Défis terminés',
    eduQuizScore: 'Score quiz',
    eduWorldsExplored: 'Mondes explorés',
    eduTimeSpent: 'Temps d’apprentissage',
    eduWeekly: 'Cette semaine',
    eduMonthly: 'Ce mois',
    eduNextRec: 'Ensuite pour toi',
    eduBackWorlds: 'Tous les mondes',
    eduMatchTitle: 'Associe les paires',
    eduMatchHint: 'Touche un élément, puis son match',
    eduFindTitle: 'Trouve le bon',
    eduCountTitle: 'Combien ?',
    eduSequenceTitle: 'Complète la suite',
    eduParentLearningTitle: 'Progression éducative',
    eduParentLearningDesc: 'Mondes, défis, quiz et temps d’apprentissage.',
    eduParentFavoriteWorlds: 'Mondes favoris',
    eduParentBySubject: 'Temps par matière',
    eduParentAchievements: 'Badges',
    eduMinutes: '{n} min',
    eduMasterUnlocked: 'Badge maître débloqué !',
    eduPlayChallenge: 'Jouer',
    eduChallengeComplete: 'Défi terminé !',
  },
  ar: {
    eduWorldAlphabet: 'الحروف',
    eduWorldAlphabetDesc: 'اكتشف الحروف بمرح.',
    eduWorldNumbers: 'الأرقام',
    eduWorldNumbersDesc: 'عد والعب مع الأرقام.',
    eduWorldColors: 'الألوان',
    eduWorldColorsDesc: 'طابق وسمِّ الألوان.',
    eduWorldShapes: 'الأشكال',
    eduWorldShapesDesc: 'ابحث عن الدوائر والمربعات.',
    eduWorldLogic: 'المنطق',
    eduWorldLogicDesc: 'أنماط وذاكرة وتفكير.',
    eduWorldMath: 'الرياضيات',
    eduWorldMathDesc: 'مغامرات حساب لطيفة.',
    eduWorldScience: 'العلوم',
    eduWorldScienceDesc: 'راقب واكتشف العالم.',
    eduWorldGeography: 'الجغرافيا',
    eduWorldGeographyDesc: 'أماكن وخرائط وثقافات.',
    eduWorldAnimals: 'الحيوانات',
    eduWorldAnimalsDesc: 'حيوانات أليفة وبرية.',
    eduWorldSpace: 'الفضاء',
    eduWorldSpaceDesc: 'كواكب ونجوم وصواريخ.',
    eduWorldDinos: 'الديناصورات',
    eduWorldDinosDesc: 'مرح ما قبل التاريخ.',
    eduWorldMusic: 'الموسيقى',
    eduWorldMusicDesc: 'استمع وإيقاع وألحان.',
    eduWorldNature: 'الطبيعة',
    eduWorldNatureDesc: 'نباتات وطقس وخارج المنزل.',
    eduWorldCreativity: 'الإبداع',
    eduWorldCreativityDesc: 'تخيّل وابتكر بحرية.',
    eduWorldEmotions: 'المشاعر',
    eduWorldEmotionsDesc: 'سمِّ وشارك مشاعرك.',
    eduWorldKindness: 'اللطف',
    eduWorldKindnessDesc: 'شارك وساعد واهتم.',
    eduWorldCulture: 'الثقافة والقيم',
    eduWorldCultureDesc: 'كلمات وقيم وتقاليد.',
    eduPathLettersAF: 'الحروف أ–و',
    eduPathLettersGL: 'الحروف ز–ل',
    eduPathLettersMR: 'الحروف م–ر',
    eduPathLettersSZ: 'الحروف س–ي',
    eduPathAlphabetMaster: 'بطل الحروف',
    eduPathNumbers15: 'الأرقام 1–5',
    eduPathNumbers610: 'الأرقام 6–10',
    eduPathNumbersMaster: 'بطل الأرقام',
    eduPathColorsPrimary: 'ألوان أساسية',
    eduPathColorsMix: 'امزج وطابق',
    eduPathColorsMaster: 'بطل الألوان',
    eduPathShapesBasic: 'أشكال أساسية',
    eduPathShapesComplex: 'صيد الأشكال',
    eduPathShapesMaster: 'بطل الأشكال',
    eduPathLogicPatterns: 'أنماط',
    eduPathLogicMemory: 'ذاكرة',
    eduPathLogicMaster: 'بطل المنطق',
    eduPathMathCount: 'العد',
    eduPathMathAdd: 'الجمع',
    eduPathMathMaster: 'عبقري الرياضيات',
    eduPathScienceObserve: 'راقب',
    eduPathScienceDiscover: 'اكتشف',
    eduPathScienceMaster: 'نجم العلوم',
    eduPathGeoPlaces: 'أماكن',
    eduPathGeoWorld: 'عالمنا',
    eduPathGeoMaster: 'مستكشف',
    eduPathAnimalsPets: 'حيوانات أليفة',
    eduPathAnimalsWild: 'حيوانات برية',
    eduPathAnimalsMaster: 'خبير الحيوانات',
    eduPathSpacePlanets: 'كواكب',
    eduPathSpaceStars: 'نجوم',
    eduPathSpaceMaster: 'مستكشف الفضاء',
    eduPathDinoNames: 'أسماء الديناصورات',
    eduPathDinoFacts: 'حقائق الديناصورات',
    eduPathDinoMaster: 'بطل الديناصورات',
    eduPathMusicListen: 'استمع',
    eduPathMusicRhythm: 'إيقاع',
    eduPathMusicMaster: 'نجم الموسيقى',
    eduPathNaturePlants: 'نباتات',
    eduPathNatureWeather: 'طقس',
    eduPathNatureMaster: 'صديق الطبيعة',
    eduPathCreativityImagine: 'تخيّل',
    eduPathCreativityCreate: 'ابتكر',
    eduPathCreativityMaster: 'مبدع',
    eduPathEmotionsFeelings: 'مشاعر',
    eduPathEmotionsExpress: 'عبّر',
    eduPathEmotionsMaster: 'نجم القلب',
    eduPathKindnessShare: 'شارك',
    eduPathKindnessHelp: 'ساعد',
    eduPathKindnessMaster: 'بطل اللطف',
    eduPathCultureWords: 'كلمات',
    eduPathCultureValues: 'قيم',
    eduPathCultureMaster: 'نجم الثقافة',
    eduBadgeFirstStory: 'أول قصة',
    eduBadgeReadingExplorer: 'مستكشف القراءة',
    eduBadgeAnimalExpert: 'خبير الحيوانات',
    eduBadgeSpaceExplorer: 'مستكشف الفضاء',
    eduBadgeMathGenius: 'عبقري الرياضيات',
    eduBadgeDailyReader: 'قارئ اليوم',
    eduBadgeStreak7: 'سلسلة 7 أيام',
    eduBadgeQuizChampion: 'بطل الاختبار',
    eduBadgeStoryCollector: 'جامع القصص',
    eduBadgeAlphabetMaster: 'بطل الحروف',
    eduHubTitle: 'عوالم تعليمية',
    eduHubSubtitle: 'اختر عالماً، العب التحديات، واجمع النجوم!',
    eduContinueLearning: 'تابع التعلم',
    eduRecommended: 'موصى به لك',
    eduPracticeAgain: 'تمرّن مجدداً',
    eduNewChallenge: 'تحدٍّ جديد',
    eduExploreMore: 'استكشف المزيد',
    eduLearningPath: 'مسار التعلم',
    eduChallenges: 'التحديات',
    eduActivities: 'الأنشطة',
    eduLevel: 'المستوى {level}',
    eduXp: '{xp} نقطة',
    eduStars: 'نجوم',
    eduDailyReward: 'مكافأة اليوم',
    eduClaimReward: 'احصل على +{xp}',
    eduRewardClaimed: 'تم أخذ المكافأة اليوم!',
    eduDashboardTitle: 'تعلّمي',
    eduStoriesDone: 'أنشطة مكتملة',
    eduChallengesDone: 'تحديات مكتملة',
    eduQuizScore: 'درجة الاختبار',
    eduWorldsExplored: 'عوالم مستكشفة',
    eduTimeSpent: 'وقت التعلم',
    eduWeekly: 'هذا الأسبوع',
    eduMonthly: 'هذا الشهر',
    eduNextRec: 'التالي لك',
    eduBackWorlds: 'كل العوالم',
    eduMatchTitle: 'طابق الأزواج',
    eduMatchHint: 'المس عنصراً ثم مطابقته',
    eduFindTitle: 'ابحث عن الصحيح',
    eduCountTitle: 'كم عددها؟',
    eduSequenceTitle: 'أكمل التسلسل',
    eduParentLearningTitle: 'التقدم التعليمي',
    eduParentLearningDesc: 'عوالم وتحديات واختبارات ووقت التعلم.',
    eduParentFavoriteWorlds: 'عوالم مفضلة',
    eduParentBySubject: 'الوقت حسب المادة',
    eduParentAchievements: 'الإنجازات',
    eduMinutes: '{n} د',
    eduMasterUnlocked: 'تم فتح شارة الماستر!',
    eduPlayChallenge: 'العب',
    eduChallengeComplete: 'اكتمل التحدي!',
  },
};

export function eduLabel(key, language = 'fr', vars = {}) {
  const lang = normalizeLanguage(language);
  let text = labels[lang]?.[key] || labels.fr[key] || labels.en[key] || key;
  Object.entries(vars).forEach(([k, v]) => {
    text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  });
  return text;
}
