export const KID_CATEGORIES = [
  {
    id: 'dinosaurs',
    label: 'Dinosaures',
    shortLabel: 'Dino',
    pictogram: '🦖',
    cue: 'Roar',
    gradient: 'from-lime-400 via-emerald-500 to-green-600',
    ring: 'ring-lime-200',
    match: ['dinosaur', 'dinosaure', 'dino'],
  },
  {
    id: 'space',
    label: 'Espace',
    shortLabel: 'Fusee',
    pictogram: '🚀',
    cue: 'Zoom',
    gradient: 'from-indigo-500 via-sky-500 to-cyan-400',
    ring: 'ring-sky-200',
    match: ['space', 'espace', 'rocket', 'fusee', 'planete', 'planet'],
  },
  {
    id: 'animals',
    label: 'Animaux',
    shortLabel: 'Animaux',
    pictogram: '🐻',
    cue: 'Coucou',
    gradient: 'from-accent-300 via-accent-400 to-rose-400',
    ring: 'ring-accent-200',
    match: ['animal', 'animaux', 'nature'],
  },
  {
    id: 'princesses',
    label: 'Princesses',
    shortLabel: 'Conte',
    pictogram: '👸',
    cue: 'Magie',
    gradient: 'from-secondary-400 via-rose-500 to-fuchsia-500',
    ring: 'ring-secondary-200',
    match: ['princess', 'princesse', 'fairy', 'conte'],
  },
  {
    id: 'jobs',
    label: 'Metiers',
    shortLabel: 'Metiers',
    pictogram: '🚒',
    cue: 'Action',
    gradient: 'from-primary-500 via-accent-500 to-yellow-400',
    ring: 'ring-accent-200',
    match: ['job', 'metier', 'doctor', 'pompier', 'teacher'],
  },
  {
    id: 'world',
    label: 'Decouverte du monde',
    shortLabel: 'Monde',
    pictogram: '🌍',
    cue: 'Explore',
    gradient: 'from-teal-400 via-primary-500 to-violet-500',
    ring: 'ring-teal-200',
    match: ['world', 'monde', 'culture', 'voyage', 'science'],
  },
];

export function getKidCategory(categoryId) {
  return KID_CATEGORIES.find((category) => category.id === categoryId) || null;
}
