export const KID_CATEGORIES = [
  {
    id: 'dinosaurs',
    label: 'Dinosaures',
    shortLabel: 'Dino',
    pictogram: '🦖',
    cue: 'Roar',
    gradient: 'from-lime-400 via-emerald-500 to-green-600',
    ring: 'ring-lime-200',
    match: ['dinosaur', 'dinosaure', 'dino'],
  },
  {
    id: 'space',
    label: 'Espace',
    shortLabel: 'Fusee',
    pictogram: '🚀',
    cue: 'Zoom',
    gradient: 'from-indigo-500 via-sky-500 to-cyan-400',
    ring: 'ring-sky-200',
    match: ['space', 'espace', 'rocket', 'fusee', 'planete', 'planet'],
  },
  {
    id: 'animals',
    label: 'Animaux',
    shortLabel: 'Animaux',
    pictogram: '🐻',
    cue: 'Coucou',
    gradient: 'from-accent-300 via-accent-400 to-rose-400',
    ring: 'ring-accent-200',
    match: ['animal', 'animaux', 'nature'],
  },
  {
    id: 'princesses',
    label: 'Princesses',
    shortLabel: 'Conte',
    pictogram: '👸',
    cue: 'Magie',
    gradient: 'from-secondary-400 via-rose-500 to-fuchsia-500',
    ring: 'ring-secondary-200',
    match: ['princess', 'princesse', 'fairy', 'conte'],
  },
  {
    id: 'jobs',
    label: 'Métiers',
    shortLabel: 'Métiers',
    pictogram: '🚒',
    cue: 'Action',
    gradient: 'from-primary-500 via-accent-500 to-yellow-400',
    ring: 'ring-accent-200',
    match: ['job', 'metier', 'doctor', 'pompier', 'teacher'],
  },
  {
    id: 'world',
    label: 'Découverte du monde',
    shortLabel: 'Monde',
    pictogram: '🌍',
    cue: 'Explore',
    gradient: 'from-teal-400 via-primary-500 to-violet-500',
    ring: 'ring-teal-200',
    match: ['world', 'monde', 'culture', 'voyage', 'science'],
  },
  {
    id: 'rhymes',
    label: 'Comptines',
    shortLabel: 'Chansons',
    pictogram: '🎵',
    cue: 'Musique',
    gradient: 'from-pink-400 via-rose-500 to-red-500',
    ring: 'ring-pink-200',
    match: ['rhyme', 'comptine', 'chanson', 'musique', 'music'],
  },
  {
    id: 'alphabet',
    label: 'Alphabet',
    shortLabel: 'Lettres',
    pictogram: '🔤',
    cue: 'ABC',
    gradient: 'from-blue-400 via-indigo-500 to-violet-600',
    ring: 'ring-blue-200',
    match: ['alphabet', 'lettre', 'abc', 'letter'],
  },
  {
    id: 'numbers',
    label: 'Chiffres',
    shortLabel: 'Compter',
    pictogram: '🔢',
    cue: '123',
    gradient: 'from-orange-400 via-amber-500 to-yellow-500',
    ring: 'ring-orange-200',
    match: ['number', 'chiffre', 'nombre', 'compter', 'math'],
  },
  {
    id: 'colors',
    label: 'Couleurs',
    shortLabel: 'Couleurs',
    pictogram: '🎨',
    cue: 'Peinture',
    gradient: 'from-fuchsia-400 via-purple-500 to-indigo-500',
    ring: 'ring-fuchsia-200',
    match: ['color', 'couleur', 'peinture', 'dessin', 'art'],
  },
];

export function getKidCategory(categoryId) {
  return KID_CATEGORIES.find((category) => category.id === categoryId) || null;
}
