import { normalizeLanguage } from '../utils/translations';

const labels = {
  en: {
    luExplore: 'Explorer',
    luExploreTitle: 'Learning Universe',
    luExploreSubtitle: 'Play, learn, and collect stars!',
    luTabUniverses: 'Worlds',
    luTabGames: 'Games',
    luTabQuiz: 'Quiz',
    luTabMe: 'My progress',
    luDailyChest: 'Surprise chest',
    luOpenChest: 'Open!',
    luChestClaimed: 'Come back tomorrow!',
    luChestXp: 'Bonus stars',
    luChestBadge: 'A badge',
    luChestAvatar: 'A new avatar',
    luChestSticker: 'A sticker',
    luChestSound: 'A fun sound',
    luChestStory: 'A story idea',
    luYouWon: 'You won',
    luAvatars: 'Avatars',
    luSelectAvatar: 'Choose',
    luDashboard: 'Today',
    luThisWeek: 'This week',
    luBooks: 'Books',
    luQuiz: 'Quiz',
    luXp: 'XP',
    luBadges: 'Badges',
    luListenTime: 'Listening',
    luReadTime: 'Reading',
    luStreak: 'Streak',
    luFavoriteWorlds: 'Favorite worlds',
    luGameMemory: 'Memory',
    luGamePuzzle: 'Puzzle',
    luGameFindAnimal: 'Find the animal',
    luGameImageWord: 'Picture → word',
    luGameCount: 'Count',
    luGameAlphabet: 'Alphabet',
    luGameColors: 'Colors',
    luGameShadows: 'Shadows',
    luGameSizes: 'Sizes',
    luGameShapes: 'Shapes',
    luPlay: 'Play',
    luStoryQuizWho: 'Who was in the story?',
    luStoryQuizWhat: 'What was in the story?',
    luStoryQuizHero: 'Pick the story star!',
    luCorrect: 'Yes!',
    luTryAgain: 'Try again',
    luSkipQuiz: 'Continue',
    luBadgeFirstBook: 'First book',
    luBadgeBooks10: '10 books',
    luBadgeBooks100: '100 books',
    luBadgeFirstQuiz: 'First quiz',
    luBadgeQuiz100: '100 correct answers',
    luBadgeExplorer: 'Explorer',
    luBadgeDinoExpert: 'Dino Expert',
    luBadgeAstronaut: 'Astronaut',
    luBadgeScientist: 'Little scientist',
    luBadgeMusicStar: 'Music star',
    luBadgeStreak3: '3-day streak',
    luBadgeChest: 'Chest opener',
    luAvatarPuppy: 'Puppy',
    luAvatarKitten: 'Kitten',
    luAvatarRobot: 'Robot',
    luAvatarPrincess: 'Princess',
    luAvatarAstronaut: 'Astronaut',
    luAvatarDragon: 'Dragon',
    luAvatarUnicorn: 'Unicorn',
    luAvatarDino: 'Dino',
    luAvatarFox: 'Fox',
    luAvatarOwl: 'Owl',
    luStories: 'Stories',
    luColors: 'Colors',
    luAlphabet: 'Alphabet',
    luNumbers: 'Numbers',
    luAnimals: 'Animals',
    luSpace: 'Space',
    luDinosaurs: 'Dinosaurs',
    luGeography: 'World',
    luMusic: 'Music',
    luGames: 'Games',
    luDiscover: 'Discover',
    luLevel: 'Level {level}',
    luMinutes: '{n} min',
  },
  fr: {
    luExplore: 'Explorer',
    luExploreTitle: 'Univers d’apprentissage',
    luExploreSubtitle: 'Joue, apprends et collectionne les étoiles !',
    luTabUniverses: 'Mondes',
    luTabGames: 'Jeux',
    luTabQuiz: 'Quiz',
    luTabMe: 'Mes progrès',
    luDailyChest: 'Coffre surprise',
    luOpenChest: 'Ouvrir !',
    luChestClaimed: 'Reviens demain !',
    luChestXp: 'Étoiles bonus',
    luChestBadge: 'Un badge',
    luChestAvatar: 'Un nouvel avatar',
    luChestSticker: 'Un sticker',
    luChestSound: 'Un son amusant',
    luChestStory: 'Une idée d’histoire',
    luYouWon: 'Tu as gagné',
    luAvatars: 'Avatars',
    luSelectAvatar: 'Choisir',
    luDashboard: 'Aujourd’hui',
    luThisWeek: 'Cette semaine',
    luBooks: 'Livres',
    luQuiz: 'Quiz',
    luXp: 'XP',
    luBadges: 'Badges',
    luListenTime: 'Écoute',
    luReadTime: 'Lecture',
    luStreak: 'Série',
    luFavoriteWorlds: 'Mondes préférés',
    luGameMemory: 'Memory',
    luGamePuzzle: 'Puzzle',
    luGameFindAnimal: 'Trouver l’animal',
    luGameImageWord: 'Image → mot',
    luGameCount: 'Compter',
    luGameAlphabet: 'Alphabet',
    luGameColors: 'Couleurs',
    luGameShadows: 'Ombres',
    luGameSizes: 'Tailles',
    luGameShapes: 'Formes',
    luPlay: 'Jouer',
    luStoryQuizWho: 'Qui était dans l’histoire ?',
    luStoryQuizWhat: 'Qu’y avait-il dans l’histoire ?',
    luStoryQuizHero: 'Choisis l’étoile de l’histoire !',
    luCorrect: 'Oui !',
    luTryAgain: 'Essaie encore',
    luSkipQuiz: 'Continuer',
    luBadgeFirstBook: 'Premier livre',
    luBadgeBooks10: '10 livres',
    luBadgeBooks100: '100 livres',
    luBadgeFirstQuiz: 'Premier quiz',
    luBadgeQuiz100: '100 bonnes réponses',
    luBadgeExplorer: 'Explorateur',
    luBadgeDinoExpert: 'Expert dinos',
    luBadgeAstronaut: 'Astronaute',
    luBadgeScientist: 'Petit scientifique',
    luBadgeMusicStar: 'Étoile musique',
    luBadgeStreak3: 'Série 3 jours',
    luBadgeChest: 'Ouvreur de coffre',
    luAvatarPuppy: 'Chiot',
    luAvatarKitten: 'Chaton',
    luAvatarRobot: 'Robot',
    luAvatarPrincess: 'Princesse',
    luAvatarAstronaut: 'Astronaute',
    luAvatarDragon: 'Dragon',
    luAvatarUnicorn: 'Licorne',
    luAvatarDino: 'Dino',
    luAvatarFox: 'Renard',
    luAvatarOwl: 'Hibou',
    luStories: 'Histoires',
    luColors: 'Couleurs',
    luAlphabet: 'Alphabet',
    luNumbers: 'Nombres',
    luAnimals: 'Animaux',
    luSpace: 'Espace',
    luDinosaurs: 'Dinosaures',
    luGeography: 'Pays du monde',
    luMusic: 'Musique',
    luGames: 'Jeux',
    luDiscover: 'Découvrir',
    luLevel: 'Niveau {level}',
    luMinutes: '{n} min',
  },
  ar: {
    luExplore: 'استكشاف',
    luExploreTitle: 'عالم التعلّم',
    luExploreSubtitle: 'العب وتعلّم واجمع النجوم!',
    luTabUniverses: 'عوالم',
    luTabGames: 'ألعاب',
    luTabQuiz: 'اختبارات',
    luTabMe: 'تقدّمي',
    luDailyChest: 'صندوق المفاجآت',
    luOpenChest: 'افتح!',
    luChestClaimed: 'عد غداً!',
    luChestXp: 'نجوم إضافية',
    luChestBadge: 'شارة',
    luChestAvatar: 'صورة رمزية جديدة',
    luChestSticker: 'ملصق',
    luChestSound: 'صوت ممتع',
    luChestStory: 'فكرة قصة',
    luYouWon: 'لقد ربحت',
    luAvatars: 'الصور الرمزية',
    luSelectAvatar: 'اختر',
    luDashboard: 'اليوم',
    luThisWeek: 'هذا الأسبوع',
    luBooks: 'كتب',
    luQuiz: 'اختبار',
    luXp: 'نقاط',
    luBadges: 'شارات',
    luListenTime: 'استماع',
    luReadTime: 'قراءة',
    luStreak: 'سلسلة',
    luFavoriteWorlds: 'عوالم مفضلة',
    luGameMemory: 'الذاكرة',
    luGamePuzzle: 'أحجية',
    luGameFindAnimal: 'ابحث عن الحيوان',
    luGameImageWord: 'صورة → كلمة',
    luGameCount: 'عدّ',
    luGameAlphabet: 'الحروف',
    luGameColors: 'الألوان',
    luGameShadows: 'الظلال',
    luGameSizes: 'الأحجام',
    luGameShapes: 'الأشكال',
    luPlay: 'العب',
    luStoryQuizWho: 'من كان في القصة؟',
    luStoryQuizWhat: 'ماذا كان في القصة؟',
    luStoryQuizHero: 'اختر نجم القصة!',
    luCorrect: 'نعم!',
    luTryAgain: 'حاول مجدداً',
    luSkipQuiz: 'متابعة',
    luBadgeFirstBook: 'أول كتاب',
    luBadgeBooks10: '10 كتب',
    luBadgeBooks100: '100 كتاب',
    luBadgeFirstQuiz: 'أول اختبار',
    luBadgeQuiz100: '100 إجابة صحيحة',
    luBadgeExplorer: 'مستكشف',
    luBadgeDinoExpert: 'خبير الديناصورات',
    luBadgeAstronaut: 'رائد فضاء',
    luBadgeScientist: 'عالم صغير',
    luBadgeMusicStar: 'نجم الموسيقى',
    luBadgeStreak3: 'سلسلة 3 أيام',
    luBadgeChest: 'فاتح الصندوق',
    luAvatarPuppy: 'جرو',
    luAvatarKitten: 'قطة',
    luAvatarRobot: 'روبوت',
    luAvatarPrincess: 'أميرة',
    luAvatarAstronaut: 'رائد فضاء',
    luAvatarDragon: 'تنين',
    luAvatarUnicorn: 'وحيد القرن',
    luAvatarDino: 'ديناصور',
    luAvatarFox: 'ثعلب',
    luAvatarOwl: 'بومة',
    luStories: 'قصص',
    luColors: 'ألوان',
    luAlphabet: 'حروف',
    luNumbers: 'أرقام',
    luAnimals: 'حيوانات',
    luSpace: 'فضاء',
    luDinosaurs: 'ديناصورات',
    luGeography: 'دول العالم',
    luMusic: 'موسيقى',
    luGames: 'ألعاب',
    luDiscover: 'اكتشف',
    luLevel: 'المستوى {level}',
    luMinutes: '{n} د',
  },
};

const TILE_LABEL = {
  stories: 'luStories',
  colors: 'luColors',
  alphabet: 'luAlphabet',
  numbers: 'luNumbers',
  animals: 'luAnimals',
  space: 'luSpace',
  dinosaurs: 'luDinosaurs',
  geography: 'luGeography',
  music: 'luMusic',
  games: 'luGames',
  quiz: 'luQuiz',
  discover: 'luDiscover',
};

export function luLabel(key, language = 'fr', vars = {}) {
  const lang = normalizeLanguage(language);
  let text = labels[lang]?.[key] || labels.fr[key] || labels.en[key] || key;
  Object.entries(vars).forEach(([k, v]) => {
    text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  });
  return text;
}

export function luTileLabel(tileId, language = 'fr') {
  return luLabel(TILE_LABEL[tileId] || tileId, language);
}
