import { normalizeLanguage } from '../utils/translations';

const labels = {
  en: {
    premNav: 'Premium',
    premHeroTitle: 'Premium worlds for little explorers',
    premHeroBody: 'Collections, seasons, AI stories, and exclusive play — unlock the magic.',
    premPopular: 'Popular Premium',
    premNew: 'New Premium',
    premSeasonal: 'Seasonal',
    premAi: 'AI Stories',
    premCollections: 'Collections',
    premRecommended: 'Recommended',
    premLocked: 'Premium',
    premPreview: 'Preview',
    premUnlock: 'Unlock Premium',
    premOpen: 'Open pack',
    premIncludes: 'Includes',
    premRibbon: 'Premium',
    premCompareTitle: 'Free vs Premium',
    premCompareLibrary: 'Story library',
    premCompareBooks: 'Premium book packs',
    premCompareSeasonal: 'Seasonal packs',
    premCompareAi: 'AI Story Creator',
    premCompareGames: 'Premium games',
    premCompareAvatars: 'Exclusive avatars',
    premCompareNarrators: 'Premium narrators',
    premCompareQuizzes: 'Premium quizzes',
    premYes: 'Yes',
    premNo: '—',
    premLimited: 'Limited',
    premStatusActive: 'Premium active',
    premStatusFree: 'Free plan',
    premRestore: 'Restore purchases',
    premManage: 'Manage subscription',
    premPacksTitle: 'Premium packs',
    premFlagsTitle: 'Feature flags',
    premAdminTitle: 'Premium packs',
    premAdminSubtitle: 'Create, publish, feature, and archive packs without code changes.',
    premPublish: 'Publish',
    premArchive: 'Archive',
    premFeature: 'Feature',
    premUnfeature: 'Unfeature',
    premCreate: 'Create pack',
    premSeasonalMark: 'Seasonal',
    premParentHistory: 'Premium history',
    premParentLocked: 'Locked for your family',
    premParentPreview: 'Preview pack',
    premPackDinos: 'Dinosaur Collection',
    premPackDinosDesc: 'Roaring stories, games, and dino badges.',
    premPackSpace: 'Space Explorer',
    premPackSpaceDesc: 'Rockets, planets, and star quizzes.',
    premPackPrincess: 'Princess Stories',
    premPackPrincessDesc: 'Fairy tales and magical adventures.',
    premPackBedtime: 'Bedtime Premium',
    premPackBedtimeDesc: 'Calm night stories and soft narrators.',
    premPackMusic: 'Music & Rhymes',
    premPackMusicDesc: 'Songs, rhymes, and musical play.',
    premPackValues: 'Values & Spiritual Stories',
    premPackValuesDesc: 'Kindness, values, and gentle wisdom.',
    premPackWorld: 'Around the World',
    premPackWorldDesc: 'Cultures, places, and discovery.',
    premPackCreativity: 'Creativity Pack',
    premPackCreativityDesc: 'Art, colors, and creative play.',
    premPackBrain: 'Brain Games',
    premPackBrainDesc: 'Logic, puzzles, and smart quizzes.',
    premPackAi: 'AI Story Creator',
    premPackAiDesc: 'Create personalized magical stories.',
    premPackRamadan: 'Ramadan Pack',
    premPackRamadanDesc: 'Stories, quizzes, and seasonal badges.',
    premPackEid: 'Eid Celebration',
    premPackEidDesc: 'Joyful Eid stories and stickers.',
    premPackSummer: 'Summer Adventures',
    premPackSummerDesc: 'Sunny tales and beach games.',
    premPackSchool: 'Back To School',
    premPackSchoolDesc: 'Alphabet, numbers, and learning fun.',
    premPackHalloween: 'Halloween Fun',
    premPackHalloweenDesc: 'Playful spooky stories for kids.',
    premPackChristmas: 'Christmas Magic',
    premPackChristmasDesc: 'Warm winter tales and gifts.',
    premPackNewYear: 'New Year Sparkle',
    premPackNewYearDesc: 'Celebrate new beginnings.',
    premPackSpring: 'Spring Bloom',
    premPackSpringDesc: 'Nature stories and soft colors.',
    premPackWinter: 'Winter Wonders',
    premPackWinterDesc: 'Snowy adventures and cozy reads.',
    premSeasonRamadan: 'Ramadan',
    premSeasonEid: 'Eid',
    premSeasonSummer: 'Summer',
    premSeasonBackToSchool: 'Back To School',
    premSeasonHalloween: 'Halloween',
    premSeasonChristmas: 'Christmas',
    premSeasonNewYear: 'New Year',
    premSeasonSpring: 'Spring',
    premSeasonWinter: 'Winter',
    premIncludeStory: 'Stories',
    premIncludeQuiz: 'Quizzes',
    premIncludeGame: 'Games',
    premIncludeIllustration: 'Art',
    premIncludeBadge: 'Badges',
    premIncludeAvatar: 'Avatars',
  },
  fr: {
    premNav: 'Premium',
    premHeroTitle: 'Des mondes Premium pour explorer',
    premHeroBody: 'Collections, saisons, histoires IA et jeux exclusifs — débloque la magie.',
    premPopular: 'Premium populaire',
    premNew: 'Nouveau Premium',
    premSeasonal: 'Saisonnier',
    premAi: 'Histoires IA',
    premCollections: 'Collections',
    premRecommended: 'Recommandé',
    premLocked: 'Premium',
    premPreview: 'Aperçu',
    premUnlock: 'Débloquer Premium',
    premOpen: 'Ouvrir le pack',
    premIncludes: 'Inclus',
    premRibbon: 'Premium',
    premCompareTitle: 'Gratuit vs Premium',
    premCompareLibrary: 'Bibliothèque',
    premCompareBooks: 'Packs de livres Premium',
    premCompareSeasonal: 'Packs saisonniers',
    premCompareAi: 'Créateur d’histoires IA',
    premCompareGames: 'Jeux Premium',
    premCompareAvatars: 'Avatars exclusifs',
    premCompareNarrators: 'Narrateurs Premium',
    premCompareQuizzes: 'Quiz Premium',
    premYes: 'Oui',
    premNo: '—',
    premLimited: 'Limité',
    premStatusActive: 'Premium actif',
    premStatusFree: 'Offre gratuite',
    premRestore: 'Restaurer les achats',
    premManage: 'Gérer l’abonnement',
    premPacksTitle: 'Packs Premium',
    premFlagsTitle: 'Fonctionnalités',
    premAdminTitle: 'Packs Premium',
    premAdminSubtitle: 'Crée, publie, mets en avant et archive des packs sans changer le code.',
    premPublish: 'Publier',
    premArchive: 'Archiver',
    premFeature: 'Mettre en avant',
    premUnfeature: 'Retirer',
    premCreate: 'Créer un pack',
    premSeasonalMark: 'Saisonnier',
    premParentHistory: 'Historique Premium',
    premParentLocked: 'Verrouillé pour la famille',
    premParentPreview: 'Aperçu du pack',
    premPackDinos: 'Collection Dinosaures',
    premPackDinosDesc: 'Histoires, jeux et badges dinos.',
    premPackSpace: 'Explorateur Spatial',
    premPackSpaceDesc: 'Fusées, planètes et quiz étoilés.',
    premPackPrincess: 'Histoires de Princesses',
    premPackPrincessDesc: 'Contes et aventures magiques.',
    premPackBedtime: 'Coucher Premium',
    premPackBedtimeDesc: 'Histoires douces et narrateurs calmes.',
    premPackMusic: 'Musique & Comptines',
    premPackMusicDesc: 'Chansons, rythmes et jeux musicaux.',
    premPackValues: 'Valeurs & Spiritualité',
    premPackValuesDesc: 'Gentillesse, valeurs et sagesse.',
    premPackWorld: 'Autour du Monde',
    premPackWorldDesc: 'Cultures, lieux et découvertes.',
    premPackCreativity: 'Pack Créativité',
    premPackCreativityDesc: 'Art, couleurs et jeux créatifs.',
    premPackBrain: 'Jeux de Cerveau',
    premPackBrainDesc: 'Logique, puzzles et quiz malins.',
    premPackAi: 'Créateur d’histoires IA',
    premPackAiDesc: 'Crée des histoires magiques personnalisées.',
    premPackRamadan: 'Pack Ramadan',
    premPackRamadanDesc: 'Histoires, quiz et badges de saison.',
    premPackEid: 'Célébration Aïd',
    premPackEidDesc: 'Histoires joyeuses et stickers.',
    premPackSummer: 'Aventures d’été',
    premPackSummerDesc: 'Contes ensoleillés et jeux de plage.',
    premPackSchool: 'Retour à l’école',
    premPackSchoolDesc: 'Alphabet, nombres et apprentissages.',
    premPackHalloween: 'Halloween Fun',
    premPackHalloweenDesc: 'Histoires amusantes un peu frisson.',
    premPackChristmas: 'Magie de Noël',
    premPackChristmasDesc: 'Contes d’hiver et cadeaux.',
    premPackNewYear: 'Nouvel An',
    premPackNewYearDesc: 'Célébrer les nouveaux départs.',
    premPackSpring: 'Printemps',
    premPackSpringDesc: 'Nature et couleurs douces.',
    premPackWinter: 'Merveilles d’hiver',
    premPackWinterDesc: 'Aventures neigeuses et lectures cosy.',
    premSeasonRamadan: 'Ramadan',
    premSeasonEid: 'Aïd',
    premSeasonSummer: 'Été',
    premSeasonBackToSchool: 'Rentrée',
    premSeasonHalloween: 'Halloween',
    premSeasonChristmas: 'Noël',
    premSeasonNewYear: 'Nouvel An',
    premSeasonSpring: 'Printemps',
    premSeasonWinter: 'Hiver',
    premIncludeStory: 'Histoires',
    premIncludeQuiz: 'Quiz',
    premIncludeGame: 'Jeux',
    premIncludeIllustration: 'Illustrations',
    premIncludeBadge: 'Badges',
    premIncludeAvatar: 'Avatars',
  },
  ar: {
    premNav: 'مميز',
    premHeroTitle: 'عوالم مميزة للمستكشفين الصغار',
    premHeroBody: 'مجموعات ومواسم وقصص ذكاء اصطناعي وألعاب حصرية.',
    premPopular: 'الأكثر شعبية',
    premNew: 'جديد مميز',
    premSeasonal: 'موسمي',
    premAi: 'قصص الذكاء الاصطناعي',
    premCollections: 'مجموعات',
    premRecommended: 'موصى به',
    premLocked: 'مميز',
    premPreview: 'معاينة',
    premUnlock: 'فتح المميز',
    premOpen: 'فتح الحزمة',
    premIncludes: 'يشمل',
    premRibbon: 'مميز',
    premCompareTitle: 'مجاني مقابل مميز',
    premCompareLibrary: 'مكتبة القصص',
    premCompareBooks: 'حزم الكتب المميزة',
    premCompareSeasonal: 'حزم موسمية',
    premCompareAi: 'منشئ قصص الذكاء الاصطناعي',
    premCompareGames: 'ألعاب مميزة',
    premCompareAvatars: 'صور رمزية حصرية',
    premCompareNarrators: 'رواة مميزون',
    premCompareQuizzes: 'اختبارات مميزة',
    premYes: 'نعم',
    premNo: '—',
    premLimited: 'محدود',
    premStatusActive: 'مميز نشط',
    premStatusFree: 'خطة مجانية',
    premRestore: 'استعادة المشتريات',
    premManage: 'إدارة الاشتراك',
    premPacksTitle: 'حزم مميزة',
    premFlagsTitle: 'ميزات',
    premAdminTitle: 'حزم مميزة',
    premAdminSubtitle: 'أنشئ وانشر وأبرز وأرشِف الحزم دون تغيير الكود.',
    premPublish: 'نشر',
    premArchive: 'أرشفة',
    premFeature: 'إبراز',
    premUnfeature: 'إلغاء الإبراز',
    premCreate: 'إنشاء حزمة',
    premSeasonalMark: 'موسمي',
    premParentHistory: 'سجل المميز',
    premParentLocked: 'مقفل لعائلتك',
    premParentPreview: 'معاينة الحزمة',
    premPackDinos: 'مجموعة الديناصورات',
    premPackDinosDesc: 'قصص وألعاب وشارات ديناصورات.',
    premPackSpace: 'مستكشف الفضاء',
    premPackSpaceDesc: 'صواريخ وكواكب واختبارات نجوم.',
    premPackPrincess: 'قصص الأميرات',
    premPackPrincessDesc: 'حكايات ومغامرات سحرية.',
    premPackBedtime: 'ما قبل النوم المميز',
    premPackBedtimeDesc: 'قصص هادئة ورواة لطيفون.',
    premPackMusic: 'موسيقى وأناشيد',
    premPackMusicDesc: 'أغانٍ وإيقاع وألعاب موسيقية.',
    premPackValues: 'قيم وروحانيات',
    premPackValuesDesc: 'لطف وقيم وحكمة لطيفة.',
    premPackWorld: 'حول العالم',
    premPackWorldDesc: 'ثقافات وأماكن واكتشاف.',
    premPackCreativity: 'حزمة الإبداع',
    premPackCreativityDesc: 'فن وألوان ولعب إبداعي.',
    premPackBrain: 'ألعاب العقل',
    premPackBrainDesc: 'منطق وألغاز واختبارات ذكية.',
    premPackAi: 'منشئ قصص الذكاء الاصطناعي',
    premPackAiDesc: 'أنشئ قصصاً سحرية مخصصة.',
    premPackRamadan: 'حزمة رمضان',
    premPackRamadanDesc: 'قصص واختبارات وشارات موسمية.',
    premPackEid: 'احتفال العيد',
    premPackEidDesc: 'قصص مبهجة وملصقات.',
    premPackSummer: 'مغامرات الصيف',
    premPackSummerDesc: 'حكايات مشمسة وألعاب الشاطئ.',
    premPackSchool: 'العودة إلى المدرسة',
    premPackSchoolDesc: 'حروف وأرقام وتعلم ممتع.',
    premPackHalloween: 'مرح الهالوين',
    premPackHalloweenDesc: 'قصص مرحة للأطفال.',
    premPackChristmas: 'سحر الكريسماس',
    premPackChristmasDesc: 'حكايات شتوية وهدايا.',
    premPackNewYear: 'تألق رأس السنة',
    premPackNewYearDesc: 'احتفل ببدايات جديدة.',
    premPackSpring: 'ازدهار الربيع',
    premPackSpringDesc: 'قصص طبيعة وألوان ناعمة.',
    premPackWinter: 'عجائب الشتاء',
    premPackWinterDesc: 'مغامرات ثلجية وقراءات دافئة.',
    premSeasonRamadan: 'رمضان',
    premSeasonEid: 'عيد',
    premSeasonSummer: 'صيف',
    premSeasonBackToSchool: 'العودة للمدرسة',
    premSeasonHalloween: 'هالوين',
    premSeasonChristmas: 'كريسماس',
    premSeasonNewYear: 'رأس السنة',
    premSeasonSpring: 'ربيع',
    premSeasonWinter: 'شتاء',
    premIncludeStory: 'قصص',
    premIncludeQuiz: 'اختبارات',
    premIncludeGame: 'ألعاب',
    premIncludeIllustration: 'رسوم',
    premIncludeBadge: 'شارات',
    premIncludeAvatar: 'صور رمزية',
  },
};

const INCLUDE_KEYS = {
  story: 'premIncludeStory',
  quiz: 'premIncludeQuiz',
  game: 'premIncludeGame',
  illustration: 'premIncludeIllustration',
  badge: 'premIncludeBadge',
  avatar: 'premIncludeAvatar',
};

export function premLabel(key, language = 'fr', vars = {}) {
  const lang = normalizeLanguage(language);
  let text = labels[lang]?.[key] || labels.fr[key] || labels.en[key] || key;
  Object.entries(vars).forEach(([k, v]) => {
    text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  });
  return text;
}

export function packDisplayTitle(pack, language = 'fr') {
  if (pack?.title) return pack.title;
  return premLabel(pack?.labelKey || pack?.id, language);
}

export function packDisplayDesc(pack, language = 'fr') {
  if (pack?.description) return pack.description;
  return premLabel(pack?.descKey || '', language);
}

export function packIncludesLabels(pack, language = 'fr') {
  return (pack?.includes || []).map((id) => premLabel(INCLUDE_KEYS[id] || id, language));
}

export function withPremiumLabels(t, language = 'fr') {
  return (key, vars) => {
    if (labels.en[key] || labels.fr[key]) return premLabel(key, language, vars || {});
    return typeof t === 'function' ? t(key, vars) : key;
  };
}
