/**
 * HKids Plus 100 — Catalog expansion (100 original titles).
 * Original French prose with EN/AR localizations.
 */
import { buildLocalizations, buildTags } from './catalogMeta.js';

const AUTHOR = 'Le Lit Qui Lit';

const CATEGORY = {
  dinosaurs: 'Dinosaures',
  space: 'Espace',
  animals: 'Animaux',
  princesses: 'Contes',
  bedtime: 'Histoires',
  spirituality: 'Spiritualite',
  ocean: 'Contes',
  vehicles: 'Histoires',
  world: 'Contes',
  colors: 'Histoires',
  rhymes: 'Comptines',
  alphabet: 'Histoires',
  numbers: 'Histoires',
  jobs: 'Histoires',
};

const GRADIENTS = [
  ['#7b3eb8', '#389d85'], ['#1e3a8a', '#7b3eb8'], ['#f76219', '#fbbf24'],
  ['#ec4899', '#8b5cf6'], ['#db2777', '#7b3eb8'], ['#389d85', '#34d399'],
  ['#dc2626', '#f97316'], ['#2563eb', '#06b6d4'], ['#7c3aed', '#a855f7'],
  ['#312e81', '#6366f1'], ['#92400e', '#d97706'], ['#059669', '#10b981'],
  ['#f59e0b', '#f76219'], ['#0f766e', '#14b8a6'], ['#be185d', '#f472b6'],
  ['#0ea5e9', '#38bdf8'], ['#65a30d', '#a3e635'], ['#ea580c', '#fb923c'],
];

function book(index, d) {
  const type = d.type || 'story';
  const level = `${d.min}-${d.max}`;
  const flags = d.flags || '';
  const item = {
    slug: d.slug,
    title: d.titleFr,
    author: AUTHOR,
    description: d.descFr,
    content_type: type,
    language: 'fr',
    theme: d.theme,
    category_name: CATEGORY[d.theme],
    age_group_min: d.min,
    age_group_max: d.max,
    emoji: d.emoji,
    gradient: GRADIENTS[index % GRADIENTS.length],
    pages: d.pages.map((text) => ({ text })),
    tags: buildTags({
      level,
      theme: d.theme,
      extra: d.extraTags || [],
      difficulty: d.difficulty || 'easy',
    }),
    is_recommended: flags.includes('rec'),
    is_popular: flags.includes('pop'),
    is_new: flags.includes('new'),
    is_premium: Boolean(d.premium),
    duration_seconds: d.duration ?? (type === 'story' ? 220 : 12),
    localizations: buildLocalizations({
      titleEn: d.titleEn,
      descEn: d.descEn,
      titleAr: d.titleAr,
      descAr: d.descAr,
      audioEn: d.audioEn,
      audioAr: d.audioAr,
    }),
  };
  if (type === 'audio_story' || type === 'song') {
    item.audio_text = d.audioFr;
  }
  return item;
}

const DEFS = [
  {
    slug: "plus-panda-bambou",
    theme: "animals",
    min: 3,
    max: 5,
    emoji: "🐼",
    titleFr: "Panda et la forêt de bambou",
    descFr: "Un panda curieux découvre un sentier secret entre les tiges vertes.",
    titleEn: "Panda and the bamboo forest",
    descEn: "A curious panda discovers a secret path among green stalks.",
    titleAr: "الباندا وغابة الخيزران",
    descAr: "باندا فضولي يكتشف مساراً سرياً بين السيقان الخضراء.",
    flags: "rec",
    premium: true,
    duration: 176,
    pages: [
      "Petit Panda se réveille au parfum du bambou frais du matin.",
      "Il suit une trace de rosée jusqu'à une clairière inconnue.",
      "Un vieux panda lui montre comment grignoter sans abîmer la forêt.",
      "Ensemble, ils plantent une pousse pour les oiseaux et les lièvres.",
      "Panda rentre le ventre plein et le cœur plus léger qu'hier.",
      "La forêt murmure merci à chaque brin qui pousse encore."
    ],
  },
  {
    slug: "plus-flamingo-danse",
    theme: "animals",
    min: 4,
    max: 7,
    emoji: "🦩",
    titleFr: "Flamingo danse au lac rose",
    descFr: "Un flamant rose apprend une chorégraphie pour le festival du lac.",
    titleEn: "Flamingo dances at the pink lake",
    descEn: "A pink flamingo learns a dance for the lake festival.",
    titleAr: "فلامنجو يرقص عند البحيرة الوردية",
    descAr: "فلامنجو وردي يتعلم رقصة لمهرجان البحيرة.",
    flags: "pop",
    duration: 259,
    pages: [
      "Au lever du soleil, le lac brille comme une confiserie rose.",
      "Flamingo bouscule ses pas, un peu maladroit mais joyeux.",
      "Une grue sage lui dit : « Écoute le rythme de l'eau. »",
      "Il bat des ailes au bon moment et fait rire toute la colonie.",
      "Le festival commence : cent flamants glissent en cercle.",
      "Flamingo comprend que danser, c'est aussi inviter les autres."
    ],
  },
  {
    slug: "plus-koala-eucalyptus",
    theme: "animals",
    min: 2,
    max: 4,
    emoji: "🐨",
    titleFr: "Koala et l'arbre qui chuchote",
    descFr: "Un koala entend des histoires dans les feuilles d'eucalyptus.",
    titleEn: "Koala and the whispering tree",
    descEn: "A koala hears stories in eucalyptus leaves.",
    titleAr: "الكوالا والشجرة التي تهمس",
    descAr: "كوالا يسمع قصصاً في أوراق الكافور.",
    difficulty: "easy",
    duration: 199,
    pages: [
      "Koala grimpe lentement, les pattes accrochées à l'écorce chaude.",
      "Une feuille frémit : « Il était une fois un vent très doux. »",
      "Il ferme les yeux et voit des nuages qui jouent au cache-cache.",
      "Sa maman le serre : « Les arbres racontent quand on écoute. »",
      "Koala s'endort, bercé par le parfum mentholé du feuillage.",
      "Dans ses rêves, toute la cime danse comme une berceuse verte."
    ],
  },
  {
    slug: "plus-pingouin-glacier",
    theme: "animals",
    min: 5,
    max: 8,
    emoji: "🐧",
    titleFr: "Pingouin sur le glacier bleu",
    descFr: "Un pingouin audacieux explore une crevasse scintillante.",
    titleEn: "Penguin on the blue glacier",
    descEn: "A bold penguin explores a sparkling crevasse.",
    titleAr: "البطريق على الجبل الجليدي الأزرق",
    descAr: "بطريق جريء يستكشف شقاً متلألئاً.",
    difficulty: "medium",
    premium: true,
    duration: 255,
    pages: [
      "Pingouin enfile ses lunettes et part vers le glacier bleu.",
      "Sous la glace transparente, des poissons dessinent des arabesques.",
      "Son ami phoque l'avertit : « Reste près du groupe, c'est plus sûr. »",
      "Ils glissent ensemble sur une pente polie comme un miroir.",
      "Pingouin ramène un joli caillou pour la bibliothèque du rocher.",
      "Le soir, toute la colonie applaudit leurs petites découvertes."
    ],
  },
  {
    slug: "plus-tortue-patience",
    theme: "animals",
    min: 3,
    max: 6,
    emoji: "🐢",
    titleFr: "Tortue et le chemin long",
    descFr: "Une tortue lente dépasse un lièvre impatient grâce à sa patience.",
    titleEn: "Turtle and the long path",
    descEn: "A slow turtle passes an impatient hare thanks to patience.",
    titleAr: "السلحفاة والطريق الطويل",
    descAr: "سلحفاة بطيئة تتجاوز أرنباً متسرعاً بفضل صبرها.",
    duration: 257,
    pages: [
      "Tortue avance d'un pas sûr sur le sentier poussiéreux.",
      "Lièvre sprinte, s'arrête, s'ennuie, puis s'allonge au soleil.",
      "Tortue boit une gorgée, respire, et continue sans se plaindre.",
      "Elle croise des fleurs qu'il aurait manquées en courant.",
      "Lièvre la rejoint, honteux : « Tu vois tout quand tu ralentis. »",
      "Ils finissent côte à côte, amis malgré leurs différences."
    ],
  },
  {
    slug: "plus-chouette-bibliotheque",
    theme: "animals",
    min: 4,
    max: 7,
    emoji: "🦉",
    titleFr: "Chouette et la bibliothèque nocturne",
    descFr: "Une chouette lit des contes aux animaux de la nuit.",
    titleEn: "Owl and the night library",
    descEn: "An owl reads tales to the animals of the night.",
    titleAr: "البومة ومكتبة الليل",
    descAr: "بومة تقرأ حكايات لحيوانات الليل.",
    flags: "new",
    duration: 207,
    pages: [
      "Quand la lune se lève, Chouette ouvre la bibliothèque du chêne.",
      "Les souris s'installent sur des coussins de mousse parfumée.",
      "Elle lit une histoire de rivière qui chante des berceuses.",
      "Un hérisson timide ose poser une question sur les étoiles.",
      "Chouette répond doucement, une plume à la main.",
      "À l'aube, les livres se ferment, pleins de rêves empruntés."
    ],
  },
  {
    slug: "plus-loutre-riviere",
    theme: "animals",
    min: 3,
    max: 5,
    emoji: "🦦",
    titleFr: "Loutre et le pont de pierres",
    descFr: "Une loutre construit un pont pour aider ses amis à traverser.",
    titleEn: "Otter and the stone bridge",
    descEn: "An otter builds a bridge to help friends cross.",
    titleAr: "قضرب النهر وجسر الحجارة",
    descAr: "قضرب يبني جسراً ليساعد أصدقاءه على العبور.",
    duration: 176,
    pages: [
      "La rivière grossit après la pluie et bloque le chemin du village.",
      "Loutre plonge, remonte des pierres lisses et les aligne avec soin.",
      "Castor l'aide à colmater les interstices avec des brindilles.",
      "Grenouille teste le pont : « Solide et un peu glissant ! »",
      "Les enfants du bois passent en riant, mains jointes.",
      "Loutre sait qu'un petit geste peut devenir un grand pont."
    ],
  },
  {
    slug: "plus-papillon-metamorphose",
    theme: "animals",
    min: 5,
    max: 8,
    emoji: "🦋",
    titleFr: "Papillon et la métamorphose",
    descFr: "Une chenille patiente devient papillon au milieu du jardin.",
    titleEn: "Butterfly and metamorphosis",
    descEn: "A patient caterpillar becomes a butterfly in the garden.",
    titleAr: "الفراشة والتحول",
    descAr: "يرقة صبورة تصبح فراشة في وسط الحديقة.",
    premium: true,
    duration: 242,
    pages: [
      "Chenille grignote une feuille, rêvant déjà du ciel.",
      "Elle tisse un cocon doux comme un pull d'hiver.",
      "Des jours passent ; à l'intérieur, tout se transforme lentement.",
      "Un matin, le cocon s'ouvre et Papillon étire ses ailes.",
      "Il vole au-dessus des roses, léger comme un souffle.",
      "Chenille n'est plus là, mais Papillon se souvient du chemin."
    ],
  },
  {
    slug: "plus-elephant-souvenirs",
    theme: "animals",
    min: 4,
    max: 7,
    emoji: "🐘",
    titleFr: "Éléphant et la mémoire des étoiles",
    descFr: "Un éléphant garde les souvenirs du troupeau sous les étoiles.",
    titleEn: "Elephant and the memory of stars",
    descEn: "An elephant keeps the herd's memories under the stars.",
    titleAr: "الفيل وذاكرة النجوم",
    descAr: "فيل يحفظ ذكريات القطيع تحت النجوم.",
    type: "audio_story",
    duration: 232,
    audioFr: "Grand Éléphant, tu te souviens de chaque sentier. Sous les étoiles, tu racontes nos histoires au vent doux.",
    audioEn: "Great Elephant, you remember every path. Under the stars, you tell our stories to the gentle wind.",
    audioAr: "أيها الفيل العظيم، تتذكر كل درب. تحت النجوم، تروي قصصنا للريح اللطيفة.",
    pages: [
      "Éléphant promène sa trompe sur de vieilles traces dans la savane.",
      "Il se souvient d'un lac qui a séché, puis revenu avec la pluie.",
      "Les petits lèvent le museau : « Raconte encore, s'il te plaît. »",
      "Il parle d'une nuit où les étoiles ont guidé le troupeau.",
      "Sa voix grave berce la poussière dorée du crépuscule.",
      "Les souvenirs voyagent mieux quand on les partage ensemble."
    ],
  },
  {
    slug: "plus-cameleon-couleurs",
    theme: "animals",
    min: 3,
    max: 6,
    emoji: "🦎",
    titleFr: "Caméléon et la fête des couleurs",
    descFr: "Un caméléon hésite entre mille teintes pour une fête du village.",
    titleEn: "Chameleon and the color festival",
    descEn: "A chameleon chooses among a thousand hues for a village party.",
    titleAr: "الحرباء ومهرجان الألوان",
    descAr: "حرباء تختار بين ألف لون لمهرجان القرية.",
    duration: 221,
    pages: [
      "Caméléon regarde les guirlandes : rouge, vert, violet, tout brille.",
      "Il change de couleur à chaque coin de rue, un peu stressé.",
      "Grand-mère lézard dit : « Sois celui que tu aimes aujourd'hui. »",
      "Il choisit un vert pomme avec des taches dorées, unique et joyeux.",
      "Les voisins applaudissent : « Tu es parfait comme tu es ! »",
      "Caméléon danse, sachant que changer reste aussi une force."
    ],
  },
  {
    slug: "plus-triceratops-bouclier",
    theme: "dinosaurs",
    min: 3,
    max: 6,
    emoji: "🦕",
    titleFr: "Tricératops et le bouclier fraternel",
    descFr: "Un tricératops protège son petit frère lors d'un orage de cendres.",
    titleEn: "Triceratops and the brother shield",
    descEn: "A triceratops protects his little brother during an ash storm.",
    titleAr: "تريسيراتops والدرع الأخوي",
    descAr: "تريسيراتops يحمي أخاه الصغير أثناء عاصفة رماد.",
    flags: "rec",
    premium: true,
    duration: 255,
    pages: [
      "Le ciel devient gris ; des cendres tombent sur la vallée verte.",
      "Grand Tricératops incline ses cornes comme un toit solide.",
      "Petit frère se blottit sous le bouclier vivant et chaud.",
      "La tempête gronde, mais ils respirent calmement ensemble.",
      "Quand le silence revient, des fleurs sauvages pointent déjà.",
      "Frère cadet murmure : « Ton bouclier est plus fort que la peur. »"
    ],
  },
  {
    slug: "plus-brachiosaure-nuages",
    theme: "dinosaurs",
    min: 4,
    max: 7,
    emoji: "🦕",
    titleFr: "Brachiosaure touche les nuages",
    descFr: "Un brachiosaure curieux croit pouvoir mordre les nuages du matin.",
    titleEn: "Brachiosaurus touches the clouds",
    descEn: "A curious brachiosaurus tries to bite the morning clouds.",
    titleAr: "برachiosaure يلمس السحب",
    descAr: "برachiosaure فضولي يظن أنه يستطيع عض سحب الصباح.",
    duration: 215,
    pages: [
      "Brachiosaure étire son long cou au-dessus des cimes moussues.",
      "Les nuages ressemblent à des boules de coton sucré.",
      "Il souffle dessus : ils s'écartent en riant presque.",
      "Un ptérosaure crie : « Ils sont faits de vent, pas de gâteau ! »",
      "Brachiosaure rit et arrose les fougères avec sa trompe d'eau.",
      "Le matin sent la pluie fine et les promesses de soleil."
    ],
  },
  {
    slug: "plus-pteranodon-ciel",
    theme: "dinosaurs",
    min: 5,
    max: 8,
    emoji: "🦖",
    titleFr: "Ptéranodon et la carte du ciel",
    descFr: "Un ptéranodon dessine les routes du vent pour les oisillons.",
    titleEn: "Pteranodon and the sky map",
    descEn: "A pteranodon draws wind routes for fledglings.",
    titleAr: "بتيرانodon وخريطة السماء",
    descAr: "بتيرانodon يرسم مسارات الريح للفراخ.",
    difficulty: "medium",
    duration: 272,
    pages: [
      "Ptéranodon déplie ses ailes larges comme des voiles légères.",
      "Il observe où le vent monte le long des falaises calcaires.",
      "Avec une griffe, il trace des flèches sur le sable humide.",
      "Les petits hésitent ; il leur fait une démonstration en spirale.",
      "Premier envol réussi : cris de joie au-dessus de la baie.",
      "Le ciel devient une bibliothèque de chemins à apprendre."
    ],
  },
  {
    slug: "plus-stegosaure-etoiles",
    theme: "dinosaurs",
    min: 3,
    max: 5,
    emoji: "🦕",
    titleFr: "Stégosaure compte les étoiles",
    descFr: "Un stégosaure utilise ses plaques pour réfléchir la lumière des étoiles.",
    titleEn: "Stegosaurus counts the stars",
    descEn: "A stegosaurus uses its plates to reflect starlight.",
    titleAr: "ستegosaur يعد النجوم",
    descAr: "ستegosaur يستخدم صفائحه ليعكس ضوء النجوم.",
    flags: "pop",
    duration: 150,
    pages: [
      "Nuit claire : Steg compte une étoile, puis deux, puis dix.",
      "Ses plaques brillent comme des miroirs polis par la lune.",
      "Petit dinosaure peur du noir s'approche timidement.",
      "Steg lui montre une constellation en forme de feuille.",
      "Ensemble, ils inventent des noms drôles pour chaque groupe.",
      "Le sommeil arrive quand le ciel devient une couverture rassurante."
    ],
  },
  {
    slug: "plus-ankylosaure-armure",
    theme: "dinosaurs",
    min: 4,
    max: 7,
    emoji: "🦖",
    titleFr: "Ankylosaure et le cœur sous l'armure",
    descFr: "Un ankylosaure robuste apprend que sa douceur vaut autant que sa carapace.",
    titleEn: "Ankylosaurus and the heart under armor",
    descEn: "A sturdy ankylosaurus learns gentleness matches his armor.",
    titleAr: "أnkylosaur والقلب تحت الدرع",
    descAr: "أnkylosaur قوي يتعلم أن لطفه يعادل درعه.",
    premium: true,
    duration: 251,
    pages: [
      "Ankylo ressemble à un rocher vivant qui roule dans les herbes.",
      "Les autres le croient dur, alors il garde ses sourires secrets.",
      "Un oisillon tombe près de lui ; Ankylo le couve avec chaleur.",
      "Tout le troupeau voit sa tendresse cachée sous les plaques.",
      "Ankylo n'a plus honte de montrer son cœur tendre.",
      "Parfois, la plus belle armure, c'est un geste gentil."
    ],
  },
  {
    slug: "plus-parasaurolophus-chant",
    theme: "dinosaurs",
    min: 5,
    max: 9,
    emoji: "🦕",
    titleFr: "Parasaurolophus chante la vallée",
    descFr: "Un parasaurolophus compose des mélodies avec sa crête creuse.",
    titleEn: "Parasaurolophus sings the valley",
    descEn: "A parasaurolophus composes melodies with his hollow crest.",
    titleAr: "parasaurolophus يغني الوادي",
    descAr: "parasaurolophus يؤلف ألحاناً بعرفه المجوف.",
    type: "audio_story",
    duration: 276,
    audioFr: "Para chante, la vallée répond. Chaque note traverse les fougères comme un vent ami.",
    audioEn: "Para sings, the valley answers. Each note crosses the ferns like a friendly wind.",
    audioAr: "para يغني، الوادي يرد. كل نغمة تعبر السرخس كريح ودود.",
    pages: [
      "Para souffle dans sa crête ; le son vibre comme une flûte.",
      "Les dinosaures lèvent la tête, surpris par la mélodie douce.",
      "Il compose un refrain pour annoncer la pluie bienfaisante.",
      "Même les nuages semblent ralentir pour écouter.",
      "Para offre un concert au crépuscule rose.",
      "La vallée retient la chanson longtemps après le silence."
    ],
  },
  {
    slug: "plus-lune-fromage",
    theme: "space",
    min: 2,
    max: 4,
    emoji: "🌙",
    titleFr: "Léo croit que la lune est en fromage",
    descFr: "Léo prépare une échelle pour goûter la lune ronde.",
    titleEn: "Leo thinks the moon is cheese",
    descEn: "Leo builds a ladder to taste the round moon.",
    titleAr: "ليو يظن أن القمر جبن",
    descAr: "ليو يبني سلماً ليتذوق القمر المدور.",
    flags: "new",
    duration: 154,
    pages: [
      "Léo regarde la lune et dit : « Elle a l'air fondante. »",
      "Il empile des coussins pour atteindre le ciel de sa chambre.",
      "Papa rit : « Goûte d'abord avec les yeux et l'imagination. »",
      "Ils préparent des crêpes rondes comme des lunes miniatures.",
      "Léo mord dedans : « Moins poussiéreux que je pensais ! »",
      "La vraie lune brille, contente d'être admirée de loin."
    ],
  },
  {
    slug: "plus-mars-jardin",
    theme: "space",
    min: 5,
    max: 8,
    emoji: "🔴",
    titleFr: "Jardin secret sur Mars",
    descFr: "Des enfants imaginent des tomates rouges poussant sur la planète rouge.",
    titleEn: "Secret garden on Mars",
    descEn: "Children imagine red tomatoes growing on the red planet.",
    titleAr: "حديقة سرية على المريخ",
    descAr: "أطفال يتخيلون طماطم حمراء تنمو على الكوكب الأحمر.",
    premium: true,
    duration: 213,
    pages: [
      "Dans la salle de classe, ils dessinent des serres sur Mars.",
      "Un robot arrose des plants avec de la glace fondue propre.",
      "Ils calculent combien de soleil il faudrait par jour.",
      "Le professeur ajoute : « La science commence par un dessin. »",
      "Les enfants rient en signant leur projet « Tomates martiennes ».",
      "Rêver loin aide parfois à mieux soigner la Terre ici."
    ],
  },
  {
    slug: "plus-comete-souhait",
    theme: "space",
    min: 4,
    max: 7,
    emoji: "☄️",
    titleFr: "Comète des petits souhaits",
    descFr: "Une comète passe et collecte les vœux des enfants du quartier.",
    titleEn: "Comet of little wishes",
    descEn: "A comet passes and collects children's wishes from the neighborhood.",
    titleAr: "مذنب الأمنيات الصغيرة",
    descAr: "مذنب يمر ويجمع أمنيات أطفال الحي.",
    duration: 207,
    pages: [
      "Ce soir, la comète traîne une queue de lumière bleue.",
      "Chaque enfant murmure un souhait sans le crier trop fort.",
      "Nina souhaite que sa grand-mère guérisse ; Sam souhaite la paix.",
      "La comète scintille, comme si elle prenait des notes.",
      "Papa dit : « Les souhaits travaillent aussi quand on agit bien. »",
      "Les enfants se couchent, confiants comme après une promesse."
    ],
  },
  {
    slug: "plus-galaxie-spirale",
    theme: "space",
    min: 6,
    max: 10,
    emoji: "🌌",
    titleFr: "Voyage dans la galaxie spirale",
    descFr: "Une équipe de jeunes astronomes suit une carte stellaire imaginaire.",
    titleEn: "Journey in the spiral galaxy",
    descEn: "Young astronomers follow an imaginary star map.",
    titleAr: "رحلة في المجرة الحلزونية",
    descAr: "فريق من الفلكيين الصغار يتبع خريطة نجوم خيالية.",
    difficulty: "medium",
    premium: true,
    duration: 359,
    pages: [
      "Dans l'observatoire, ils allument une carte holographique douce.",
      "Chaque bras de la galaxie brille d'une couleur différente.",
      "Ils nomment une nébuleuse « Nuage de lait chaud » par jeu.",
      "Le guide explique comment les étoiles naissent et dansent.",
      "Un silence respectueux s'installe devant tant de beauté.",
      "Ils repartent avec des carnets pleins de questions lumineuses."
    ],
  },
  {
    slug: "plus-station-potager",
    theme: "space",
    min: 7,
    max: 10,
    emoji: "🛸",
    titleFr: "Station spatiale et potager orbital",
    descFr: "Des astronautes juniors cultivent des salades en apesanteur.",
    titleEn: "Space station and orbital garden",
    descEn: "Junior astronauts grow lettuce in zero gravity.",
    titleAr: "محطة فضائية وحديقة مدارية",
    descAr: "رواد فضاء صغار يزرعون خساً في انعدام الجاذبية.",
    duration: 329,
    pages: [
      "Dans la station, les plantes flottent dans des capsules transparentes.",
      "Lina fixe les racines avec un filet délicat pour qu'elles grandissent.",
      "Tom mesure la lumière artificielle comme un chef jardinier.",
      "Une feuille pousse droite malgré l'absence de haut et bas.",
      "Ils préparent une salade pour le dîner de l'équipage entier.",
      "Manger ce qu'on a fait pousser goûte encore plus l'espace."
    ],
  },
  {
    slug: "plus-anneaux-saturne",
    theme: "space",
    min: 5,
    max: 8,
    emoji: "🪐",
    titleFr: "Promenade sur les anneaux de Saturne",
    descFr: "Deux sœurs imaginent patiner sur les anneaux glacés de Saturne.",
    titleEn: "Walk on Saturn's rings",
    descEn: "Two sisters imagine skating on Saturn's icy rings.",
    titleAr: "نزهة على حلقات زحل",
    descAr: "أختان تتخيلان التزلج على حلقات زحل الجليدية.",
    type: "audio_story",
    duration: 268,
    audioFr: "Anneaux de glace, piste sans fin. Nous glissons doucement entre les étoiles sœurs.",
    audioEn: "Rings of ice, endless track. We glide gently between sister stars.",
    audioAr: "حلقات من الجليد، مسار بلا نهاية. ننزلق بلطف بين نجوم شقيقة.",
    pages: [
      "Les sœurs collent des anneaux dorés sur une affiche de Saturne.",
      "Elles enfilent des chaussons et glissent sur le parquet.",
      "L'aînée dit : « Ici, la gravité est presque un murmure. »",
      "Elles s'envolent dans leur imagination, mains jointes.",
      "Une poussière d'étoiles les entoure comme une écharpe.",
      "Rentrer au dîner est plus difficile que quitter les anneaux."
    ],
  },
  {
    slug: "plus-princesse-lumiere",
    theme: "princesses",
    min: 4,
    max: 7,
    emoji: "👑",
    titleFr: "Princesse Lumière et la lampe du soir",
    descFr: "Princesse Lumière allume des lanternes pour les villageois.",
    titleEn: "Princess Light and the evening lamp",
    descEn: "Princess Light lights lanterns for villagers.",
    titleAr: "أميرة النور ومصباح المساء",
    descAr: "أميرة النور تُضيء فوانيس للقرويين.",
    flags: "rec",
    premium: true,
    duration: 226,
    pages: [
      "Princesse Lumière porte une cape couleur aurore sur les toits.",
      "Elle descend dans le village où les ombres s'allongent tôt.",
      "Chaque lanterne reçoit une mèche et un sourire chaleureux.",
      "Un enfant peur du noir lui confie son ours en peluche.",
      "Elle place une petite lampe près de son lit de paille.",
      "Le royaume brille sans magie cruelle, seulement avec du soin."
    ],
  },
  {
    slug: "plus-princesse-vent",
    theme: "princesses",
    min: 5,
    max: 8,
    emoji: "🌬️",
    titleFr: "Princesse Vent et le moulin du roi",
    descFr: "Princesse Vent répare un moulin grâce au souffle du ciel.",
    titleEn: "Princess Wind and the king's mill",
    descEn: "Princess Wind fixes a mill with the sky's breath.",
    titleAr: "أميرة الريح وطاحونة الملك",
    descAr: "أميرة الريح تصلح طاحونة بأنفاس السماء.",
    duration: 262,
    pages: [
      "Le moulin du roi s'est arrêté depuis trois jours de calme.",
      "Princesse Vent monte la colline, cheveux libres comme des drapeaux.",
      "Elle écoute le ciel et ouvre les volet au bon moment.",
      "Le vent revient, doux mais assez fort pour tourner les pales.",
      "Le meunier crie merci en offrant du pain chaud.",
      "Elle apprend qu'une princesse peut être aussi utile qu'un chevalier."
    ],
  },
  {
    slug: "plus-princesse-montagne",
    theme: "princesses",
    min: 4,
    max: 6,
    emoji: "⛰️",
    titleFr: "Princesse Montagne et le sentier secret",
    descFr: "Princesse Montagne guide des voyageurs sur un chemin oublié.",
    titleEn: "Princess Mountain and the secret path",
    descEn: "Princess Mountain guides travelers on a forgotten path.",
    titleAr: "أميرة الجبل والدرب السري",
    descAr: "أميرة الجبل ترشد مسافرين على درب منسي.",
    flags: "pop",
    duration: 251,
    pages: [
      "La brume recouvre les pics ; les marchands sont perdus.",
      "Princesse Montagne connaît chaque pierre par cœur.",
      "Elle marque le sol avec des rubans bleus discrets.",
      "Un aigle les accompagne, gardien silencieux du sentier.",
      "Ils atteignent l'auberge avant la nuit glacée.",
      "La montagne respecte ceux qui marchent avec humilité."
    ],
  },
  {
    slug: "plus-princesse-encre",
    theme: "princesses",
    min: 6,
    max: 9,
    emoji: "📜",
    titleFr: "Princesse Encre et le livre vivant",
    descFr: "Princesse Encre écrit des contes qui s'animent à la lecture.",
    titleEn: "Princess Ink and the living book",
    descEn: "Princess Ink writes tales that come alive when read.",
    titleAr: "أميرة الحبر والكتاب الحي",
    descAr: "أميرة الحبر تكتب حكايات تنبض بالحياة عند القراءة.",
    difficulty: "medium",
    premium: true,
    duration: 280,
    pages: [
      "Dans la tour bibliothèque, Princesse Encre trempe sa plume.",
      "Elle trace un dragon minuscule qui cligne des yeux sur la page.",
      "Les serviteurs sursautent, puis rient devant la magie douce.",
      "Elle promet que chaque histoire appartient au lecteur aussi.",
      "Un page timide lit à voix haute ; le dragon s'envole en origami.",
      "Le royaume découvre que les mots peuvent ouvrir des portes."
    ],
  },
  {
    slug: "plus-princesse-miroir",
    theme: "princesses",
    min: 3,
    max: 5,
    emoji: "🪞",
    titleFr: "Princesse Miroir et la vérité gentille",
    descFr: "Princesse Miroir apprend à se voir avec bienveillance.",
    titleEn: "Princess Mirror and kind truth",
    descEn: "Princess Mirror learns to see herself with kindness.",
    titleAr: "أميرة المرآة والحقيقة اللطيفة",
    descAr: "أميرة المرآة تتعلم أن ترى نفسها بلطف.",
    duration: 173,
    pages: [
      "Princesse Miroir regarde son reflet, un peu sévère ce matin.",
      "La fée du château dit : « Dis-toi trois choses vraies et douces. »",
      "Elle murmure : « Je suis curieuse, j'aide, j'apprends encore. »",
      "Le miroir semble sourire comme après la pluie.",
      "Elle invite une amie à faire le même exercice au goûter.",
      "Être princesse, c'est aussi être amie de soi-même."
    ],
  },
  {
    slug: "plus-princesse-sable",
    theme: "princesses",
    min: 4,
    max: 7,
    emoji: "🏖️",
    titleFr: "Princesse Sable et la dune chantante",
    descFr: "Princesse Sable écoute la musique cachée des dunes au crépuscule.",
    titleEn: "Princess Sand and the singing dune",
    descEn: "Princess Sand hears music hidden in dunes at dusk.",
    titleAr: "أميرة الرمل والكثبان المغنية",
    descAr: "أmيرة الرمل تسمع موسيقى مخفية في الكثبان عند الغروب.",
    type: "audio_story",
    duration: 239,
    audioFr: "Princesse Sable, le vent te chante. Ferme les yeux, la dune te berce comme une mélodie.",
    audioEn: "Princess Sand, the wind sings to you. Close your eyes, the dune rocks you like a melody.",
    audioAr: "أميرة الرمل، الريح تغنيك. أغمضي عينيك، الكثيب يهديك كأنغام.",
    pages: [
      "Le désert rose vibre quand le soleil descend derrière l'horizon.",
      "Princesse Sable retire ses sandales et marche pieds nus.",
      "Le sable chante un frisson grave sous ses pas légers.",
      "Elle ferme les yeux et devine la direction du puits.",
      "Les étoiles s'allument une à une au-dessus des palmiers.",
      "Elle sait que certains royaumes tiennent dans un grain de sable."
    ],
  },
  {
    slug: "plus-dodo-lune-miel",
    theme: "bedtime",
    min: 2,
    max: 4,
    emoji: "🍯",
    titleFr: "Dodo à la lune de miel",
    descFr: "Un enfant imagine une lune douce comme du miel pour s'endormir.",
    titleEn: "Sleep with the honey moon",
    descEn: "A child imagines a moon soft as honey to fall asleep.",
    titleAr: "نام مع قمر العسل",
    descAr: "طفل يتخيل قمراً ناعماً كالعسل لينام.",
    flags: "rec",
    duration: 156,
    pages: [
      "Maman étend une couverture bleu nuit sur le petit lit.",
      "Elle raconte une lune qui coule lentement, dorée et tiède.",
      "L'enfant lèche ses doigts imaginaires, riant tout bas.",
      "Les paupières deviennent lourdes comme des ailes d'oiseau.",
      "Un chat ronronne au pied du lit, gardien du sommeil.",
      "La lune de miel veille sans bruit jusqu'au matin clair."
    ],
  },
  {
    slug: "plus-berceuse-nuage",
    theme: "bedtime",
    min: 3,
    max: 5,
    emoji: "☁️",
    titleFr: "Berceuse du nuage passage",
    descFr: "Un nuage lent passe devant la fenêtre et chante une berceuse.",
    titleEn: "Lullaby of the passing cloud",
    descEn: "A slow cloud passes the window and sings a lullaby.",
    titleAr: "تهويدة الغيمة العابرة",
    descAr: "غيمة بطيئة تعبر النافذة وتغني تهويدة.",
    premium: true,
    duration: 183,
    pages: [
      "Le ciel est gris clair ; un nuage s'arrête un instant.",
      "Il murmure : « Ferme les yeux, je fais de l'ombre douce. »",
      "L'enfant compte trois gouttes de pluie sur la vitre.",
      "Le nuage dessine un ours blanc qui s'étire paresseusement.",
      "La respiration devient régulière, calme comme la mer.",
      "Quand le nuage part, il laisse un parfum de pluie fine."
    ],
  },
  {
    slug: "plus-pyjama-etoiles",
    theme: "bedtime",
    min: 4,
    max: 6,
    emoji: "👕",
    titleFr: "Pyjama aux étoiles brodées",
    descFr: "Un pyjama magique projette des constellations au plafond.",
    titleEn: "Pajamas with embroidered stars",
    descEn: "Magic pajamas project constellations on the ceiling.",
    titleAr: "بيجاما بنجوم مطرزة",
    descAr: "بيجاما سحرية ت proyect نجوماً على السقف.",
    duration: 233,
    pages: [
      "Le pyjama neuf brille légèrement quand on éteint la lampe.",
      "Des étoiles brodées montent doucement vers le plafond.",
      "Papa nomme la Grande Ourse et la Petite Casserole.",
      "L'enfant invente une constellation en forme de vélo.",
      "Les étoiles clignotent au rythme d'une respiration lente.",
      "Endormi, il rêve qu'il pédale entre deux galaxies amicales."
    ],
  },
  {
    slug: "plus-chuchotis-nuit",
    theme: "bedtime",
    min: 3,
    max: 6,
    emoji: "🤫",
    titleFr: "Chuchotis de la nuit polie",
    descFr: "La nuit demande aux bruits de parler doucement pour laisser dormir.",
    titleEn: "Whispers of the polite night",
    descEn: "Night asks sounds to speak softly so sleep can come.",
    titleAr: "همسات الليل المهذب",
    descAr: "الليل يطلب من الأصوات أن تهمس لتدع النوم يأتي.",
    flags: "new",
    duration: 207,
    pages: [
      "La nuit descend et pose un doigt sur les lèvres du monde.",
      "La porte grince moins ; le frigo ronronne comme un chat.",
      "Même le vent dans les arbres se fait plus discret.",
      "L'enfant chuchote son dernier mot : « Merci, nuit. »",
      "Les paupières se ferment comme des rideaux de velours.",
      "Silence n'est pas vide : il est plein de rêves qui attendent."
    ],
  },
  {
    slug: "plus-ours-doudou-voyage",
    theme: "bedtime",
    min: 2,
    max: 4,
    emoji: "🧸",
    titleFr: "Ours doudou part en voyage",
    descFr: "Un doudou explore le couvre-lit avant de ramener des rêves.",
    titleEn: "Teddy goes on a journey",
    descEn: "A teddy explores the blanket before bringing back dreams.",
    titleAr: "دبدوب يسافر",
    descAr: "دبدوب يستكشف اللحاف قبل أن يعود بالأحلام.",
    duration: 187,
    pages: [
      "Ours Doudou reçoit un passeport dessiné au crayon vert.",
      "Il traverse la montagne du coussin avec courage et laine.",
      "Il rencontre un poisson nuage qui lui prête une écaille brillante.",
      "Il revient avant minuit, fièrement posé contre la joue.",
      "L'enfant serre Doudou ; les rêves commencent aussitôt.",
      "Au matin, une écaille de pluie brille encore sur l'oreiller."
    ],
  },
  {
    slug: "plus-lanterne-reves",
    theme: "bedtime",
    min: 5,
    max: 8,
    emoji: "🏮",
    titleFr: "Lanterne aux rêves suspendus",
    descFr: "Une lanterne accroche les rêves comme des lucioles dans un bocal.",
    titleEn: "Lantern of hanging dreams",
    descEn: "A lantern catches dreams like fireflies in a jar.",
    titleAr: "فانوس الأحلام المعلقة",
    descAr: "فانوس يجمع الأحلام كاليراعات في مرطبان.",
    premium: true,
    duration: 216,
    pages: [
      "Grand-père accroche une lanterne en papier au-dessus du lit.",
      "Il dit : « Les bons rêves aiment la lumière chaude. »",
      "La nuit, de petites étincelles dorées tournent autour.",
      "L'enfant attrape une étincelle : elle sent la vanille.",
      "Les mauvais rêves s'effacent devant cette lueur patiente.",
      "Au matin, la lanterne est vide, car les rêves ont été vécus."
    ],
  },
  {
    slug: "plus-souffle-dormir",
    theme: "bedtime",
    min: 3,
    max: 5,
    emoji: "💨",
    titleFr: "Souffle pour dormir",
    descFr: "Un exercice de respiration guide l'enfant vers le sommeil.",
    titleEn: "Breath for sleep",
    descEn: "A breathing exercise guides the child toward sleep.",
    titleAr: "نفس للنوم",
    descAr: "تمرين تنفس يرشد الطفل نحو النوم.",
    type: "audio_story",
    duration: 158,
    audioFr: "Inspire doucement, retiens, expire lentement. Le sommeil arrive comme une vague calme.",
    audioEn: "Breathe in gently, hold, breathe out slowly. Sleep arrives like a calm wave.",
    audioAr: "تنفس بلطف، اhold، زفر ببطء. النوم يأتي كموجة هادئة.",
    pages: [
      "Assis dans le lit, l'enfant pose une main sur le ventre.",
      "Inspire par le nez : le ventre se gonfle comme une bulle.",
      "Expire par la bouche : la bulle retombe doucement.",
      "Quatre souffles, puis cinq ; les épaules se détendent enfin.",
      "Les pensées s'alignent comme des dominos qui s'allongent.",
      "Le dernier souffle emporte la journée vers la porte fermée."
    ],
  },
  {
    slug: "plus-veilleuse-lune",
    theme: "bedtime",
    min: 4,
    max: 7,
    emoji: "🌛",
    titleFr: "Veilleuse en forme de lune",
    descFr: "Une veilleuse veille sur la chambre et chasse les ombres inquiètes.",
    titleEn: "Moon-shaped nightlight",
    descEn: "A nightlight watches the room and chases worried shadows.",
    titleAr: "مصباح ليلي على شكل قمر",
    descAr: "مصباح ليلي يسهر على الغرفة ويطرد الظلال القلقة.",
    flags: "pop",
    duration: 263,
    pages: [
      "La veilleuse lune s'allume d'une lueur jaune rassurante.",
      "Une ombre sur le mur ressemble à un monstre un peu ridicule.",
      "L'enfant rit et lui dessine un chapeau de fête.",
      "La lune veilleuse clignote comme pour applaudir.",
      "Les monstres deviennent des nuages qui s'endorment debout.",
      "La chambre entière respire au rythme d'une marée lente."
    ],
  },
  {
    slug: "plus-recif-corail",
    theme: "ocean",
    min: 4,
    max: 7,
    emoji: "🪸",
    titleFr: "Récif de corail et le bal des poissons",
    descFr: "Un récif coloreux accueille un bal sous la lumière filtrée.",
    titleEn: "Coral reef and the fish ball",
    descEn: "A colorful reef hosts a dance under filtered light.",
    titleAr: "الشعاب المرجانية و حفل الأسماك",
    descAr: "شعاب مرجانية ملونة تستضيف حفلاً تحت الضوء المنفّذ.",
    flags: "rec",
    premium: true,
    duration: 239,
    pages: [
      "Le soleil perce l'eau et peint le corail en orange vif.",
      "Poisson-clown invite ses voisins sur une piste de sable fin.",
      "Une pieuvre joue du tambour avec deux coquillages polis.",
      "Les algues ondulent comme des rubans au rythme de la musique.",
      "Même le requin timide tourne une pirouette maladroite.",
      "Le réf s'endort heureux, gardant ses couleurs pour demain."
    ],
  },
  {
    slug: "plus-pieuvre-peinture",
    theme: "ocean",
    min: 3,
    max: 6,
    emoji: "🐙",
    titleFr: "Pieuvre peintre des fonds marins",
    descFr: "Une pieuvre crée des fresques avec de l'encre naturelle.",
    titleEn: "Octopus painter of the deep",
    descEn: "An octopus creates murals with natural ink.",
    titleAr: "الأخطبوط رسام أعماق البحر",
    descAr: "أخطبوط يرسم جداريات بحبر طبيعي.",
    duration: 210,
    pages: [
      "Pieuvre Octo sort huit pinceaux de ses tentacules souples.",
      "Elle peint des vagues bleues sur un rocher lisse.",
      "Les crabes applaudissent en claquant des pinces joyeuses.",
      "Un poisson-lune demande un portrait avec des taches d'argent.",
      "Octo signe d'une petite tache en bas à droite.",
      "L'océan devient galerie d'art sous la lumière du matin."
    ],
  },
  {
    slug: "plus-meduse-lumiere",
    theme: "ocean",
    min: 5,
    max: 8,
    emoji: "🪼",
    titleFr: "Méduse lumière et la nuit bleue",
    descFr: "Une méduse bioluminescente guide les plongeurs de nuit.",
    titleEn: "Light jellyfish and the blue night",
    descEn: "A bioluminescent jellyfish guides night divers.",
    titleAr: "قنديل النور والليل الأزرق",
    descAr: "قنديل مضيء يرشد غواصي الليل.",
    difficulty: "medium",
    duration: 266,
    pages: [
      "La nuit, l'eau devient velours noir parsemé d'étincelles.",
      "Médusa pulse d'une lueur verte douce et régulière.",
      "Les plongeurs suivent sa danse sans toucher ses filaments.",
      "Elle les mène vers un banc de poissons endormis debout.",
      "Un enfant en surface applaudit en voyant les lumières.",
      "La mer montre qu'il existe des soleils sous l'eau aussi."
    ],
  },
  {
    slug: "plus-crabe-tresor",
    theme: "ocean",
    min: 4,
    max: 6,
    emoji: "🦀",
    titleFr: "Crabe et le trésor des coquillages",
    descFr: "Un crabe découvre que le vrai trésor est une collection de coquillages uniques.",
    titleEn: "Crab and the shell treasure",
    descEn: "A crab finds the real treasure is a collection of unique shells.",
    titleAr: "السلطعون وكنز الأصداف",
    descAr: "سلطعون يكتشف أن الكنز الحقيقي مجموعة أصداف فريدة.",
    flags: "new",
    duration: 230,
    pages: [
      "Crabe Clac fouille le sable après la marée basse.",
      "Il trouve une spirale parfaite, puis une coquille rose striée.",
      "Son ami étoile de mer prête un emplacement sur un rocher plat.",
      "Ensemble, ils classent les coquillages par forme et couleur.",
      "Un touriste veut acheter ; Crac refuse poliment.",
      "Certains trésors ne se vendent pas : ils se contemplent."
    ],
  },
  {
    slug: "plus-algue-danse",
    theme: "ocean",
    min: 3,
    max: 5,
    emoji: "🌿",
    titleFr: "Danse des algues au courant",
    descFr: "Des algues dansent au rythme du courant comme des ballerines vertes.",
    titleEn: "Seaweed dance in the current",
    descEn: "Seaweed dances to the current like green ballerinas.",
    titleAr: "رقصة الأعشاب مع التيار",
    descAr: "أعشاب بحرية ترقص مع التيار كراقصات خضر.",
    duration: 164,
    pages: [
      "Le courant se lève ; les algues inclinent leurs feuilles fines.",
      "Poisson argenté slalome entre elles, invité d'honneur.",
      "La chorégraphie change quand la marée tourne doucement.",
      "Une tortue de mer s'arrête pour regarder, amusée.",
      "Les algues saluent en frémissant, puis reprennent leur ballet.",
      "La mer sait danser même sans musique audible."
    ],
  },
  {
    slug: "plus-phare-baleine",
    theme: "ocean",
    min: 5,
    max: 9,
    emoji: "🐋",
    titleFr: "Phare et chanson de baleine",
    descFr: "Un phare et une baleine échangent des signaux lumineux et sonores.",
    titleEn: "Lighthouse and whale song",
    descEn: "A lighthouse and a whale exchange light and sound signals.",
    titleAr: "المنارة وأغنية الحوت",
    descAr: "منارة وحوت يتبادلان إشارات ضوئية وصوتية.",
    type: "audio_story",
    premium: true,
    duration: 246,
    audioFr: "Baleine lointaine, ta voix traverse l'eau. Phare fidèle, je réponds par deux éclats doux.",
    audioEn: "Distant whale, your voice crosses the water. Faithful lighthouse, I answer with two soft flashes.",
    audioAr: "أيتها الحوت البعيدة، صوتك يعبر الماء. أيها المنارة المخلص، أرد بوميضين لطيفين.",
    pages: [
      "Le phare tourne ; sa lumière dessine un cercle sur les vagues.",
      "Au loin, une baleine chante une note grave et longue.",
      "Le gardien note l'heure dans un carnet usé par le sel.",
      "Les pêcheurs disent que ce duo protège les bateaux.",
      "Une enfant dessine les deux amis sur une carte marine.",
      "La nuit entière devient conversation entre ciel et mer."
    ],
  },
  {
    slug: "plus-velo-parc",
    theme: "vehicles",
    min: 3,
    max: 6,
    emoji: "🚲",
    titleFr: "Vélo rouge dans le parc",
    descFr: "Un enfant apprend à pédaler sans roues stabilisatrices.",
    titleEn: "Red bike in the park",
    descEn: "A child learns to pedal without training wheels.",
    titleAr: "دراجة حمراء في الحديقة",
    descAr: "طفل يتعلم الد pedaling بدون عجلات مساعدة.",
    flags: "rec",
    duration: 203,
    pages: [
      "Le vélo rouge brille près du banc en bois du parc.",
      "Papa tient le siège ; l'enfant pédale, un peu tremblant.",
      "Un lapin traverse la piste ; ils s'arrêtent en riant ensemble.",
      "Au troisième essai, l'équilibre reste plus longtemps.",
      "Papa lâche ; le vélo avance comme un oiseau au sol.",
      "La victoire goûte le vent et la confiance tiède."
    ],
  },
  {
    slug: "plus-bus-ecole",
    theme: "vehicles",
    min: 4,
    max: 7,
    emoji: "🚌",
    titleFr: "Bus de l'école et les voisins",
    descFr: "Un bus scolaire recueille des histoires à chaque arrêt.",
    titleEn: "School bus and the neighbors",
    descEn: "A school bus collects stories at every stop.",
    titleAr: "حافلة المدرسة والجيران",
    descAr: "حافلة مدرسية تجمع قصصاً عند كل محطة.",
    duration: 230,
    pages: [
      "Le bus jaune siffle doucement devant la boulangerie.",
      "Chaque arrêt apporte un bonjour et un sac coloré.",
      "Le chauffeur connaît le prénom de tous les passagers.",
      "Une fille raconte son chat ; un garçon montre un dessin.",
      "Le bus devient un salon roulant avant les leçons.",
      "Arriver ensemble rend l'école moins intimidante."
    ],
  },
  {
    slug: "plus-avion-papier",
    theme: "vehicles",
    min: 5,
    max: 8,
    emoji: "✈️",
    titleFr: "Avion en papier traverse les nuages",
    descFr: "Un avion plié vole plus loin que prévu grâce au vent amical.",
    titleEn: "Paper plane crosses the clouds",
    descEn: "A folded plane flies farther than expected on a friendly wind.",
    titleAr: "طائرة ورقية تعبر السحب",
    descAr: "طائرة مطوية تطير أبعد من المتوقع بفضل ريح ودودة.",
    premium: true,
    duration: 232,
    pages: [
      "Des mains habiles plient une feuille en ailes symétriques.",
      "L'enfant souffle dessus depuis le haut de la colline verte.",
      "L'avion glisse, monte, frôle un nuage cotonneux.",
      "Il atterrit près d'un banc où une fille lit un livre.",
      "Elle le renvoie avec un sourire et un mot gentil.",
      "Parfois, un petit voyage relie deux inconnus amicaux."
    ],
  },
  {
    slug: "plus-bateau-voile",
    theme: "vehicles",
    min: 4,
    max: 7,
    emoji: "⛵",
    titleFr: "Bateau à voile et le vent juste",
    descFr: "Deux amis règlent la voile pour une promenade sereine.",
    titleEn: "Sailboat and the right wind",
    descEn: "Two friends adjust the sail for a serene ride.",
    titleAr: "قارب شراعي والريح المناسبة",
    descAr: "صديقان يضبطان الشراع لرحلة هادئة.",
    duration: 272,
    pages: [
      "Le bateau craque doucement contre le ponton en bois.",
      "Ils hissent la voile blanche, tendue comme une feuille.",
      "Le vent arrive enfin ; l'eau murmure le long de la coque.",
      "Un dauphin les salue de loin sans les effrayer.",
      "Ils mangent des sandwichs en regardant la côte reculer.",
      "Rentrer au port, c'est déjà préparer la prochaine sortie."
    ],
  },
  {
    slug: "plus-tracteur-champ",
    theme: "vehicles",
    min: 3,
    max: 5,
    emoji: "🚜",
    titleFr: "Tracteur vert et le champ qui pousse",
    descFr: "Un tracteur aide à semer des graines sous la pluie fine.",
    titleEn: "Green tractor and the growing field",
    descEn: "A tractor helps sow seeds under fine rain.",
    titleAr: "جرار أخضر والحقل النامي",
    descAr: "جرار يساعد في زرع البذور تحت المطر الخفيف.",
    flags: "pop",
    duration: 184,
    pages: [
      "Le tracteur vert toussote, puis ronronne comme un gros chat.",
      "Le fermier remplit le réservoir de graines dorées.",
      "La pluie fine arrose le sillon fraîchement tracé.",
      "Des oiseaux suivent, espérant une graine perdue.",
      "Les enfants regardent depuis la clôture, fascinés.",
      "Demain, le champ comptera des milliers de petits espoirs verts."
    ],
  },
  {
    slug: "plus-metro-reves",
    theme: "vehicles",
    min: 6,
    max: 10,
    emoji: "🚇",
    titleFr: "Métro des rêves éveillés",
    descFr: "Un métro imaginaire transporte des rêves entre les stations.",
    titleEn: "Subway of waking dreams",
    descEn: "An imaginary subway carries dreams between stations.",
    titleAr: "مترو الأحلام اليقظة",
    descAr: "مترو خيالي ينقل الأحلام بين المحطات.",
    type: "audio_story",
    difficulty: "medium",
    duration: 354,
    audioFr: "Métro des rêves, roule sans bruit. Chaque station ouvre une porte vers demain.",
    audioEn: "Dream subway, roll in silence. Each station opens a door to tomorrow.",
    audioAr: "مترو الأحلام، تحرك بصمت. كل محطة تفتح باباً نحو الغد.",
    pages: [
      "La rame glisse ; les fenêtres montrent des paysages changeants.",
      "Station Nuage : les passagers descendent en chaussons.",
      "Station Livre : des histoires flottent comme des affiches.",
      "Un contrôleur souriant tamponne des billets en forme d'étoile.",
      "L'enfant redescend avec un rêve neuf dans sa poche.",
      "Le métro repart, laissant une odeur de pluie sur les rails."
    ],
  },
  {
    slug: "plus-maroc-souks",
    theme: "world",
    min: 5,
    max: 8,
    emoji: "🇲🇦",
    titleFr: "Souks du Maroc et les couleurs",
    descFr: "Yasmine découvre les parfums et les tissus des souks animés.",
    titleEn: "Moroccan souks and colors",
    descEn: "Yasmine discovers scents and fabrics in lively souks.",
    titleAr: "أسواق المغرب والألوان",
    descAr: "يasmine تكتشف عطور الأسواق المغربية وأقمشتها.",
    flags: "rec",
    premium: true,
    duration: 207,
    pages: [
      "Yasmine serre la main de son père dans l'étroite ruelle.",
      "Les épices sentent le safran, le cumin et l'aventure.",
      "Un tisserand lui montre un fil bleu comme la mer.",
      "Elle goûte un cornet de pâtisserie au miel parfumé.",
      "Le muezzin chante au loin ; les chats dorment au soleil.",
      "Yasmine note trois mots nouveaux dans son carnet de voyage."
    ],
  },
  {
    slug: "plus-japon-cerisiers",
    theme: "world",
    min: 4,
    max: 7,
    emoji: "🇯🇵",
    titleFr: "Cerisiers en fleurs au Japon",
    descFr: "Kenji pique-nique sous les sakura avec sa famille.",
    titleEn: "Cherry blossoms in Japan",
    descEn: "Kenji picnics under sakura with his family.",
    titleAr: "أزهار الكرز في اليابان",
    descAr: "kenji يتنزه تحت أزهار الكرز مع عائلته.",
    duration: 231,
    pages: [
      "Les pétales roses tombent comme une pluie silencieuse.",
      "Kenji déroule un tapis bleu sous l'arbre centenaire.",
      "Grand-mère prépare des onigiri triangulaires bien serrés.",
      "Des amis jouent au ballon loin, sans bruit excessif.",
      "Kenji ferme les yeux : le parfum est doux et fugace.",
      "Il promet de revenir chaque printemps, même grand."
    ],
  },
  {
    slug: "plus-kenya-safari",
    theme: "world",
    min: 6,
    max: 10,
    emoji: "🇰🇪",
    titleFr: "Safari au Kenya avec Amina",
    descFr: "Amina observe les girafes et apprend à respecter la savane.",
    titleEn: "Safari in Kenya with Amina",
    descEn: "Amina watches giraffes and learns to respect the savanna.",
    titleAr: "سفari في كينيا مع أمينة",
    descAr: "أmina تراقب الزرافات وتتعلم احترام السavanna.",
    difficulty: "medium",
    duration: 282,
    pages: [
      "Le jeep avance lentement ; poussière dorée et chants d'oiseaux.",
      "Amina lève les jumelles : trois girafes broutent près d'un acacia.",
      "Le guide chuchote les règles : silence, respect, pas de déchets.",
      "Un zèbre traverse la piste, rayé comme un code secret.",
      "Amina dessine la scène avant que la lumière ne change.",
      "Elle comprend que voyager, c'est aussi écouter la terre."
    ],
  },
  {
    slug: "plus-canada-erables",
    theme: "world",
    min: 4,
    max: 7,
    emoji: "🇨🇦",
    titleFr: "Érables rouges au Canada",
    descFr: "Léo ramasse des feuilles d'érable pour un herbier d'automne.",
    titleEn: "Red maples in Canada",
    descEn: "Leo collects maple leaves for an autumn herbarium.",
    titleAr: "القيقب الأحمر في كندا",
    descAr: "leo يجمع أوراق القيقب لherbarium خريفي.",
    duration: 245,
    pages: [
      "L'air sent le bois brûlé et la pomme caramélisée.",
      "Léo choisit une feuille en forme d'étoile à cinq branches.",
      "Sa sœur le défie : qui trouvera la plus grande ?",
      "Ils collent les feuilles dans un cahier avec du ruban.",
      "Maman prépare des crêpes au sirop d'érable le soir.",
      "L'automne devient saison de trésors, pas de tristesse."
    ],
  },
  {
    slug: "plus-perou-montagnes",
    theme: "world",
    min: 5,
    max: 9,
    emoji: "🇵🇪",
    titleFr: "Montagnes du Pérou et le lama",
    descFr: "Mateo monte un sentier andin avec un lama pacifique.",
    titleEn: "Peruvian mountains and the llama",
    descEn: "Mateo climbs an Andean trail with a peaceful llama.",
    titleAr: "جبال البيرu واللاما",
    descAr: "mateo يصعد درباً أندياً مع lama هادئ.",
    premium: true,
    duration: 233,
    pages: [
      "Le sentier serpente ; le souffle devient plus court mais joyeux.",
      "Lama Kusi porte le sac léger avec une dignité drôle.",
      "Mateo boit de l'eau claire puisque la montagne la filtre.",
      "Ils croisent des terrasses vertes sculptées par les ancêtres.",
      "Le vent apporte une musique de flûte très lointaine.",
      "Au sommet, Mateo crie bonjour sans peur, juste gratitude."
    ],
  },
  {
    slug: "plus-inde-festival",
    theme: "world",
    min: 4,
    max: 6,
    emoji: "🇮🇳",
    titleFr: "Festival des lumières en Inde",
    descFr: "Priya allume des diyas avec sa famille pour célébrer Diwali.",
    titleEn: "Festival of lights in India",
    descEn: "Priya lights diyas with her family to celebrate Diwali.",
    titleAr: "مهرجان الأنوار في الهند",
    descAr: "priya تُضيء diyas مع عائلتها للاحتفال بdewali.",
    flags: "new",
    duration: 239,
    pages: [
      "Priya peint un rangoli coloré devant la porte en bois.",
      "Chaque diya reçoit une goutte d'huile et une mèche fine.",
      "La maison brille ; les voisins échangent des douceurs.",
      "Papa raconte pourquoi la lumière chasse la peur ancienne.",
      "Priya souffle presque sur une flamme, puis s'arrête.",
      "La nuit devient amie quand des milliers de feux dansent."
    ],
  },
  {
    slug: "plus-egypte-pyramides",
    theme: "world",
    min: 6,
    max: 10,
    emoji: "🇪🇬",
    titleFr: "Pyramides d'Égypte et le sphinx",
    descFr: "Nour visite les pyramides et écoute les contes du sphinx.",
    titleEn: "Egyptian pyramids and the sphinx",
    descEn: "Nour visits pyramids and hears the sphinx's tales.",
    titleAr: "أهرامات مصر وأبو الهول",
    descAr: "nour يزور الأهرامات ويسمع حكايات أبو الهول.",
    duration: 347,
    pages: [
      "Le sable chauffe les sandales ; Nour avance sous un parasol.",
      "Les pyramides triangulaires découpent le ciel bleu pâle.",
      "Un guide raconte comment les pierres voyagent lentement.",
      "Nour touche le sphinx avec respect, sans grimper dessus.",
      "Elle écrit une question dans son carnet pour plus tard.",
      "L'histoire humaine est grande ; Nour se sent petit mais curieux."
    ],
  },
  {
    slug: "plus-bresil-carnaval",
    theme: "world",
    min: 5,
    max: 8,
    emoji: "🇧🇷",
    titleFr: "Carnaval au Brésil et les plumes",
    descFr: "Lucas prépare un costume de plumes pour défiler joyeusement.",
    titleEn: "Carnival in Brazil and feathers",
    descEn: "Lucas prepares a feather costume to parade joyfully.",
    titleAr: "الكرnaval في البرازيل والريش",
    descAr: "lucas يعد زي ريش للمشاركة في العرض.",
    flags: "pop",
    duration: 216,
    pages: [
      "Lucas colle des plumes bleues sur un masque en carton.",
      "Sa mère coud des sequins qui brillent comme des étoiles.",
      "La fanfare répète ; les tambours font vibrer la rue.",
      "Lucas danse maladroitement, puis de mieux en mieux.",
      "La foule applaudit ; la joie devient contagieuse.",
      "Il comprend que fêter ensemble unit les cœurs différents."
    ],
  },
  {
    slug: "plus-rouge-grenade",
    theme: "colors",
    min: 2,
    max: 4,
    emoji: "🔴",
    titleFr: "Rouge comme une grenade",
    descFr: "Lina découvre le rouge dans les fruits et les fleurs du jardin.",
    titleEn: "Red like a pomegranate",
    descEn: "Lina discovers red in fruits and flowers of the garden.",
    titleAr: "أحمر كالرمان",
    descAr: "lina تكتشف اللون الأحمر في ثمار الحديقة وزهورها.",
    flags: "rec",
    duration: 182,
    pages: [
      "Lina touche une grenade ouverte : grains rouges comme des perles.",
      "Elle compare avec une rose, une fraise et un ballon usé.",
      "Papa dit : « Le rouge crie doucement : regarde-moi ! »",
      "Lina dessine un soleil rouge au crayon gras.",
      "Elle range les objets rouges dans une boîte en bois.",
      "Le rouge devient son mot préféré pour les matins joyeux."
    ],
  },
  {
    slug: "plus-bleu-ocean-ciel",
    theme: "colors",
    min: 3,
    max: 5,
    emoji: "🔵",
    titleFr: "Bleu océan, bleu ciel",
    descFr: "Noé mélange les bleus pour peindre mer et ciel ensemble.",
    titleEn: "Ocean blue, sky blue",
    descEn: "Noah mixes blues to paint sea and sky together.",
    titleAr: "أزرق المحيط، أزرق السماء",
    descAr: "noé يmezج درجات الأزرق ليرسم البحر والسماء.",
    duration: 190,
    pages: [
      "Noé dispose trois pots : bleu clair, bleu moyen, bleu nuit.",
      "Il essuie son pinceau entre chaque nuance avec patience.",
      "La mer prend des vagues sombres ; le ciel reste plus pâle.",
      "Un voilier blanc relie les deux zones bleues.",
      "Maman accroche le tableau près de la fenêtre ouverte.",
      "Noé décide que le bleu est la couleur du calme."
    ],
  },
  {
    slug: "plus-vert-foret",
    theme: "colors",
    min: 4,
    max: 6,
    emoji: "🟢",
    titleFr: "Vert forêt et la mousse",
    descFr: "Zoé explore les verts d'une forêt après la pluie.",
    titleEn: "Forest green and moss",
    descEn: "Zoe explores greens in a forest after rain.",
    titleAr: "أخضر الغابة والطحلب",
    descAr: "zoé تستكشف درجات الأخضر في غابة بعد المطر.",
    premium: true,
    duration: 226,
    pages: [
      "La forêt sent la terre humide et les feuilles écrasées.",
      "Zoé compare mousse, fougère, sapin et herbe fraîche.",
      "Une coccinelle rouge se détache sur le vert profond.",
      "Elle prend une photo sans arracher la moindre plante.",
      "Papa explique que le vert est le repos des yeux fatigués.",
      "Zoé rentre les bottes pleines de boue et le cœur apaisé."
    ],
  },
  {
    slug: "plus-jaune-soleil-mais",
    theme: "colors",
    min: 3,
    max: 5,
    emoji: "🟡",
    titleFr: "Jaune soleil et maïs",
    descFr: "Sam collectionne les objets jaunes dans la ferme de tante.",
    titleEn: "Yellow sun and corn",
    descEn: "Sam collects yellow objects at aunt's farm.",
    titleAr: "أصفر الشمس والذرة",
    descAr: "sam يجمع الأشياء الصفراء في مزرعة خالته.",
    duration: 187,
    pages: [
      "Sam court entre les poules et les bottes de paille dorée.",
      "Il trouve un tournesol, un citron et un tracteur jaune.",
      "Tante rit : « Tu fais un arc-en-ciel inversé ! »",
      "Sam aligne ses trésors sur la table de la grange.",
      "Le soleil de midi fait briller chaque objet.",
      "Le jaune lui rappelle de sourire même les jours gris."
    ],
  },
  {
    slug: "plus-violet-reve-lavande",
    theme: "colors",
    min: 5,
    max: 8,
    emoji: "🟣",
    titleFr: "Violet rêve et lavande",
    descFr: "Inès sent la lavande et peint des rêves violets.",
    titleEn: "Violet dream and lavender",
    descEn: "Ines smells lavender and paints violet dreams.",
    titleAr: "بنفسجي الحلم والخزامى",
    descAr: "inès تشم الخزامى وترسم أحلاماً بنفسجية.",
    difficulty: "medium",
    duration: 246,
    pages: [
      "Inès marche entre les rangées de lavande au couchant.",
      "Les abeilles bourdonnent ; l'air vibre de parfum doux.",
      "Elle mélange du rouge et du bleu sur sa palette usée.",
      "Le violet naît, mystérieux comme la nuit qui arrive.",
      "Elle peint une porte vers un rêve qu'elle nommera demain.",
      "Violet devient la couleur des questions sans réponse pressée."
    ],
  },
  {
    slug: "plus-boulanger-matin",
    theme: "jobs",
    min: 3,
    max: 6,
    emoji: "🥖",
    titleFr: "Boulanger du matin aux mains farinées",
    descFr: "Monsieur Paul pétrit le pain avant l'aube.",
    titleEn: "Morning baker with floury hands",
    descEn: "Mr. Paul kneads bread before dawn.",
    titleAr: "خباز الصباح بيدين ملطختين",
    descAr: "السيد paul يعجن الخبز قبل الفجر.",
    flags: "pop",
    duration: 212,
    pages: [
      "À quatre heures, le four ronronne déjà dans la boulangerie.",
      "Monsieur Paul pétrit la pâte avec des gestes précis et lents.",
      "La farine danse dans l'air comme une neige chaude.",
      "Les premiers clients sentent le pain avant de voir la vitrine.",
      "Une enfant reçoit un petit pain en forme de tortue.",
      "Le quartier se réveille grâce à ce travail silencieux."
    ],
  },
  {
    slug: "plus-infirmiere-soin",
    theme: "jobs",
    min: 5,
    max: 8,
    emoji: "🩺",
    titleFr: "Infirmière Clara et le pansement doux",
    descFr: "Clara apprend à soigner avec des mots gentils.",
    titleEn: "Nurse Clara and the gentle bandage",
    descEn: "Clara learns to heal with kind words.",
    titleAr: "الممرضة كلara والضمادة اللطيفة",
    descAr: "كلara تتعلم العلاج بكلمات لطيفة.",
    premium: true,
    duration: 228,
    pages: [
      "Clara prépare un plateau : coton, pansement, sourire.",
      "Un garçon a peur ; elle lui montre d'abord sur une poupée.",
      "Elle explique chaque geste sans jamais se presser.",
      "Le pansement est posé ; le garçon respire enfin.",
      "Clara lui offre un sticker d'étoile pour le courage.",
      "Soigner, c'est aussi écouter ce que le corps murmure."
    ],
  },
  {
    slug: "plus-pompier-courage",
    theme: "jobs",
    min: 4,
    max: 7,
    emoji: "🚒",
    titleFr: "Pompier Léo et l'échelle haute",
    descFr: "Léo apprend le courage calme lors d'un exercice.",
    titleEn: "Firefighter Leo and the tall ladder",
    descEn: "Leo learns calm courage during a drill.",
    titleAr: "رجل الإطفاء leo والسلم العالي",
    descAr: "leo يتعلم الشجاعة الهادئة في تمرين.",
    flags: "rec",
    duration: 213,
    pages: [
      "La sirène retentit pour un exercice, pas une vraie urgence.",
      "Léo enfile sa veste lourde, fière mais un peu nerveux.",
      "Le capitaine rappelle : « On avance ensemble, jamais seul. »",
      "L'échelle monte ; Léo respire lentement comme appris.",
      "Il descend, tremblant de fierté plus que de peur.",
      "Le courage, ce n'est pas ne jamais trembler."
    ],
  },
  {
    slug: "plus-jardinier-graines",
    theme: "jobs",
    min: 3,
    max: 5,
    emoji: "🌱",
    titleFr: "Jardinier des graines patientes",
    descFr: "Omar plante des graines et attend avec la pluie.",
    titleEn: "Gardener of patient seeds",
    descEn: "Omar plants seeds and waits with the rain.",
    titleAr: "بستاني البذور الصبورة",
    descAr: "omar يزرع البذور وينتظر مع المطر.",
    duration: 191,
    pages: [
      "Omar creuse de petits trous réguliers dans la terre meuble.",
      "Chaque graine reçoit un nom murmuré : tomate, basilic, tournesol.",
      "Il arrose avec un arrosoir vert troué de soleil.",
      "Des jours passent ; rien ne montre encore.",
      "Une pousse verte perce enfin, minuscule victoire.",
      "Omar apprend que patience et soin font pousser les miracles."
    ],
  },
  {
    slug: "plus-musicien-notes",
    theme: "jobs",
    min: 5,
    max: 9,
    emoji: "🎵",
    titleFr: "Musicien des notes voyageuses",
    descFr: "Elias compose une mélodie qui traverse les continents.",
    titleEn: "Musician of traveling notes",
    descEn: "Elias composes a melody crossing continents.",
    titleAr: "موسيقي النغمات الرحالة",
    descAr: "elias يؤلف لحناً يعبر القارات.",
    difficulty: "medium",
    duration: 265,
    pages: [
      "Elias tape des doigts sur la table : tac, tac, tac, tac.",
      "Il écrit des notes sur une portée qui serpente.",
      "Chaque mesure rappelle un voyage : Maroc, Brésil, Japon.",
      "Sa sœur fredonne le refrain sans partition.",
      "Le chat bat la queue au bon tempo, amusant.",
      "La musique devient carte pour les oreilles curieuses."
    ],
  },
  {
    slug: "plus-bibliothecaire-livres",
    theme: "jobs",
    min: 4,
    max: 7,
    emoji: "📚",
    titleFr: "Bibliothécaire et le livre perdu",
    descFr: "Madame Lin retrouve un livre égaré et le bon lecteur.",
    titleEn: "Librarian and the lost book",
    descEn: "Ms. Lin finds a lost book and the right reader.",
    titleAr: "أمينة المكتبة والكتاب المفقود",
    descAr: "السيدة lin تعثر على كتاب ضائع والقارئ المناسب.",
    premium: true,
    duration: 243,
    pages: [
      "Madame Lin range les livres par couleur, puis par sujet.",
      "Un volume bleu manque ; elle consulte le registre usé.",
      "Elle le retrouve sous un coussin de lecture, pages cornées.",
      "Un enfant timide avoue l'avoir emprunté sans carte.",
      "Elle lui fabrique une carte avec un tampon étoile.",
      "Les livres perdues retrouvent parfois le cœur qui en a besoin."
    ],
  },
  {
    slug: "plus-a-abeille",
    theme: "alphabet",
    min: 2,
    max: 4,
    emoji: "🅰️",
    titleFr: "A comme Abeille et arbre",
    descFr: "La lettre A se cache dans le jardin entre fleurs et ruches.",
    titleEn: "A for Bee and tree",
    descEn: "Letter A hides in the garden among flowers and hives.",
    titleAr: "أ مثل نحلة وشجرة",
    descAr: "حرف أ يختبئ في الحديقة بين الزهور والخلايا.",
    duration: 170,
    pages: [
      "Amina cherche la lettre A sur des étiquettes colorées.",
      "Elle la trouve sur Arbre, Abeille et Avion en papier.",
      "Elle trace A majuscule dans le sable du bac à lettres.",
      "Papa lui chante : « A ouvre le mot amour aussi. »",
      "Amina colle une abeille dessinée à côté du A fière.",
      "Demain, elle cherchera B avec la même curiosité joyeuse."
    ],
  },
  {
    slug: "plus-b-baleine",
    theme: "alphabet",
    min: 3,
    max: 5,
    emoji: "🅱️",
    titleFr: "B comme Baleine et ballon",
    descFr: "Boris collectionne les mots qui commencent par B.",
    titleEn: "B for Whale and balloon",
    descEn: "Boris collects words starting with B.",
    titleAr: "ب مثل حوت وبالون",
    descAr: "boris يجمع كلمات تبدأ بب.",
    flags: "new",
    duration: 190,
    pages: [
      "Boris ouvre un carnet bleu pour la chasse aux B.",
      "Baleine, ballon, bonbon, bibliothèque remplissent la page.",
      "Il mord un bonbon sans oublier de brosser ses dents.",
      "Sa maîtresse applaudit : « B brille dans ta liste ! »",
      "Il dessine un B avec une queue de baleine espiègle.",
      "Chaque lettre est une porte vers des mots amis."
    ],
  },
  {
    slug: "plus-c-chateau-chat",
    theme: "alphabet",
    min: 4,
    max: 6,
    emoji: "©️",
    titleFr: "C comme Château et chat",
    descFr: "Camille construit un château de lettres C en carton.",
    titleEn: "C for Castle and cat",
    descEn: "Camille builds a castle of letter C in cardboard.",
    titleAr: "ج مثل قلعة وقطة",
    descAr: "camille تبني قلعة من حرف ج بالكarton.",
    duration: 212,
    pages: [
      "Camille découpe des C géants avec des ciseaux arrondis.",
      "Elle les assemble en tour avec de la colle blanche.",
      "Son chat Caramel dort sur le toit en forme de croissant.",
      "Elle ajoute des drapeaux : C pour courage, aussi.",
      "Les voisins admirent le château depuis la clôture.",
      "L'alphabet devient jeu de construction sans fin."
    ],
  },
  {
    slug: "plus-d-dragon-dodo",
    theme: "alphabet",
    min: 3,
    max: 5,
    emoji: "🔤",
    titleFr: "D comme Dragon qui fait dodo",
    descFr: "Un dragon gentil apprend la lettre D avant de dormir.",
    titleEn: "D for Dragon who sleeps",
    descEn: "A gentle dragon learns letter D before sleep.",
    titleAr: "د مثل تنين ينام",
    descAr: "تنين لطيف يتعلم حرف د قبل النوم.",
    duration: 166,
    pages: [
      "Dragon Dodo a des écailles en forme de D minuscule.",
      "Il souffle des bulles, pas de feu, pour amuser les enfants.",
      "On lui lit un dictionnaire illustré des mots doux.",
      "Dodo, doudou, douceur : la liste s'allonge paisiblement.",
      "Dragon bâille ; sa queue dessine un D dans la poussière.",
      "Même les dragons obéissent à l'alphabet du sommeil."
    ],
  },
  {
    slug: "plus-un-etoile-compte",
    theme: "numbers",
    min: 2,
    max: 4,
    emoji: "1️⃣",
    titleFr: "Un, une étoile à compter",
    descFr: "Un enfant apprend le nombre un avec une étoile veilleuse.",
    titleEn: "One star to count",
    descEn: "A child learns number one with a watchful star.",
    titleAr: "واحد، نجمة للعد",
    descAr: "طفل يتعلم الرقم واحد بنجمة ساهرة.",
    duration: 199,
    pages: [
      "Une seule étoile brille au-dessus du toit ce soir.",
      "L'enfant lève un doigt : « Un, comme mon souhait. »",
      "Maman place une assiette, une cuillère, un verre d'eau.",
      "Le chat a une queue qui fait un cercle parfait.",
      "Ils chantent : « Un petit pas, un grand câlin. »",
      "Le nombre un devient ami, pas une énigme."
    ],
  },
  {
    slug: "plus-deux-mains-aide",
    theme: "numbers",
    min: 3,
    max: 5,
    emoji: "2️⃣",
    titleFr: "Deux paniers, dix doigts",
    descFr: "Deux amis comptent sur leurs doigts pour partager équitablement.",
    titleEn: "Two baskets, ten fingers",
    descEn: "Two friends count fingers to share fairly.",
    titleAr: "سلّتان وعشرة أصابع",
    descAr: "صديقان يعدّان الأصابع للمشاركة بعدالة.",
    duration: 184,
    pages: [
      "Deux paniers de pommes attendent sur la table en bois.",
      "Chaque enfant lève deux mains : dix doigts au total.",
      "Ils partagent en paires : deux pour toi, deux pour moi.",
      "Un oiseau pose deux pattes sur la barrière, curieux.",
      "Ils terminent avec deux sourires et zéro dispute.",
      "Deux, c'est aussi le nombre de mains pour porter un ami."
    ],
  },
  {
    slug: "plus-trois-amis-triangle",
    theme: "numbers",
    min: 4,
    max: 6,
    emoji: "3️⃣",
    titleFr: "Trois amis et le triangle",
    descFr: "Trois amis dessinent un triangle stable avec trois bâtons.",
    titleEn: "Three friends and the triangle",
    descEn: "Three friends draw a stable triangle with three sticks.",
    titleAr: "ثلاثة أصدقاء والمثلث",
    descAr: "ثلاثة أصدقاء يرسمون مثلثاً بثلاث عصي.",
    flags: "pop",
    duration: 235,
    pages: [
      "Ils ramassent trois bâtons de tailles presque égales.",
      "Sur le sable, ils forment un triangle bien fermé.",
      "Chaque côté a un nom : partage, écoute, rire.",
      "Le vent souffle ; le triangle tient grâce aux trois points.",
      "Ils sautent à l'intérieur sans le casser, fiers.",
      "Trois amis peuvent porter plus qu'une personne seule."
    ],
  },
  {
    slug: "plus-dix-doigts-compte",
    theme: "numbers",
    min: 5,
    max: 8,
    emoji: "🔟",
    titleFr: "Dix doigts pour compter jusqu'à dix",
    descFr: "Une comptine des doigts mène jusqu'au nombre dix.",
    titleEn: "Ten fingers to count to ten",
    descEn: "A finger rhyme leads up to number ten.",
    titleAr: "عشرة أصابع للعد حتى عشرة",
    descAr: "أنشودة أصابع تصل إلى الرقم عشرة.",
    difficulty: "medium",
    premium: true,
    duration: 214,
    pages: [
      "Assis en cercle, les enfants montrent leurs dix doigts.",
      "Un, deux, trois : on plie les doigts un par un.",
      "À six, on rit ; à huit, on chuchote ; à dix, on applaudit.",
      "La maîtresse trace dix petits cercles au tableau vert.",
      "Chaque cercle devient une planète ou une boule de jeu.",
      "Dix est grand, mais tient dans deux mains soudées."
    ],
  },
  {
    slug: "plus-comptine-vent",
    theme: "rhymes",
    min: 2,
    max: 4,
    emoji: "💨",
    titleFr: "Comptine du vent dans les arbres",
    descFr: "Une comptine pour écouter le vent jouer dans les feuilles.",
    titleEn: "Wind in the trees rhyme",
    descEn: "A rhyme to hear wind play in leaves.",
    titleAr: "أنشودة الريح في الأشجار",
    descAr: "أنشودة لسماع الريح تلعب في الأوراق.",
    type: "song",
    duration: 156,
    audioFr: "Vent léger, vent joueur, tu fais danser les feuilles en couleur. Souffle doux, souffle amis, tu nous fais rire sans bruit.",
    audioEn: "Light wind, playful wind, you dance the leaves in color. Blow soft, blow friend, you make us laugh without noise.",
    audioAr: "ريح خفيفة، ريح لعوبة، ترقص الأوراق ملونة. انفخي بلطف، انفخي يا صديقة، تضحكوننا بلا ضجيج.",
    pages: [
      "Vent léger, vent joueur, dans les branches ce matin.",
      "Tu fais tourbillonner une feuille orange comme un ballon.",
      "Les enfants ouvrent les bras et tournent avec toi.",
      "Vent s'arrête ; tout le monde retient son souffle.",
      "Puis il repart, plus doux qu'avant, comme un secret.",
      "La comptine finit quand les feuilles se posent en cercle."
    ],
  },
  {
    slug: "plus-comptine-riviere",
    theme: "rhymes",
    min: 3,
    max: 5,
    emoji: "🌊",
    titleFr: "Comptine de la rivière qui court",
    descFr: "La rivière court entre les pierres en comptine joyeuse.",
    titleEn: "Running river rhyme",
    descEn: "The river runs between stones in a joyful rhyme.",
    titleAr: "أنشودة النهر الجاري",
    descAr: "النهر يركض بين الحجارة في أنشودة مبهجة.",
    type: "song",
    duration: 193,
    extraTags: ["comptine","rhyme","song"],
    audioFr: "Rivière, rivière, tu glisses sans fatigue. Tu chatouilles les cailloux, les canards comptent leurs pas.",
    audioEn: "River, river, you glide without tiring. You tickle the stones, ducks count their steps.",
    audioAr: "يا نهر، تنزلق بلا تعب. تدغدغ الحجارة، البط يعد خطواته.",
    pages: [
      "Rivière, rivière, tu glisses sans te fatiguer.",
      "Tu chatouilles les cailloux ronds de tes vagues petites.",
      "Les canards nagent en ligne, comptant leurs petits pas.",
      "Un pont de bois te survole ; tu dis bonjour en murmurant.",
      "Les enfants battent des mains au rythme de ton eau.",
      "La comptine se termine quand la rivière rejoint la mer calme."
    ],
  },
  {
    slug: "plus-comptine-feux",
    theme: "rhymes",
    min: 4,
    max: 6,
    emoji: "🔥",
    titleFr: "Comptine du feu de camp",
    descFr: "Autour du feu, une comptine réchauffe les voix.",
    titleEn: "Campfire rhyme",
    descEn: "Around the fire, a rhyme warms voices.",
    titleAr: "أنشودة نار الم camp",
    descAr: "حول النار، أنشودة تدفئ الأصوات.",
    type: "song",
    premium: true,
    duration: 273,
    audioFr: "Feu de camp, flamme amie, tu danses avant de dormir. Nos voix s'entrelacent comme des braises qui rient.",
    audioEn: "Campfire, friend flame, you dance before sleep. Our voices weave like laughing embers.",
    audioAr: "نار الم camp، يا لهب صديق، ترقص قبل النوم. أصواتنا تتشابك كجمر يضحك.",
    pages: [
      "Le feu crépite ; chacun apporte une ligne à la comptine.",
      "Flamme amie, tu éclaires nos visages ronds.",
      "On tapote des genoux ; les étoiles applaudissent là-haut.",
      "Une étincelle s'envole ; on souffle un vœu discret.",
      "Le dernier couplet parle de marshmallows fondants.",
      "La nuit sent le bois brûlé et les chansons partagées."
    ],
  },
  {
    slug: "plus-comptine-papillon",
    theme: "rhymes",
    min: 3,
    max: 5,
    emoji: "🦋",
    titleFr: "Comptine du papillon volant",
    descFr: "Un papillon guide une comptine entre les fleurs du jardin.",
    titleEn: "Flying butterfly rhyme",
    descEn: "A butterfly guides a rhyme among garden flowers.",
    titleAr: "أنشودة الفراشة الطائرة",
    descAr: "فراشة ترشد أنشودة بين زهور الحديقة.",
    flags: "rec",
    duration: 166,
    pages: [
      "Papillon, papillon, où vas-tu ce matin clair ?",
      "Tu poses sur une marguerite, puis sur un tulipe rouge.",
      "Les enfants suivent en marchant sur la pointe des pieds.",
      "La comptine dit : « Ne casse pas les ailes du vent. »",
      "Papillon s'envole ; la dernière strophe reste en suspens.",
      "On la chuchote encore en rentrant pour le goûter."
    ],
  },
  {
    slug: "plus-comptine-lune-dodo",
    theme: "rhymes",
    min: 2,
    max: 4,
    emoji: "🌙",
    titleFr: "Comptine lune dodo",
    descFr: "Une berceuse comptine pour la lune et les paupières lourdes.",
    titleEn: "Moon sleep rhyme",
    descEn: "A lullaby rhyme for the moon and heavy eyelids.",
    titleAr: "أنشودة نوم القمر",
    descAr: "تهويدة للقمر والجفون الثقيلة.",
    type: "song",
    duration: 153,
    audioFr: "Lune dodo, étoile dodo, ferme les yeux petit bout. La nuit te couvre d un manteau tout doux.",
    audioEn: "Sleep moon, sleep star, close your eyes little one. Night covers you with a soft coat.",
    audioAr: "نامي يا قمر، نامي يا نجمة، أغمض عينيك يا صغير. الليل يغطيك بمعطف ناعم.",
    pages: [
      "Lune dodo accrochée au ciel comme une veilleuse ronde.",
      "Les nuages lui font un lit de coton gris clair.",
      "L'enfant ferme les yeux en même temps que la lune.",
      "La comptine ralentit mot après mot, souffle après souffle.",
      "Même le chat cesse de ronronner fort, par politesse.",
      "Silence doux ; la comptine continue dans les rêves."
    ],
  },
  {
    slug: "plus-gratitude-matin",
    theme: "spirituality",
    min: 3,
    max: 6,
    emoji: "🙏",
    titleFr: "Gratitude du matin calme",
    descFr: "Sara remercie pour trois petites choses avant l'école.",
    titleEn: "Calm morning gratitude",
    descEn: "Sara thanks for three small things before school.",
    titleAr: "امtنان الصباح الهادئ",
    descAr: "sara تشكر على ثلاث أشياء صغيرة قبل المدرسة.",
    flags: "rec",
    duration: 218,
    pages: [
      "Sara s'assoit près de la fenêtre ; le ciel est rose pâle.",
      "Elle murmure merci pour le pain, le chat, la pluie d'hier.",
      "Maman ajoute : « Tu peux remercier aussi pour l'effort. »",
      "Sara pense à sa maîtresse qui explique avec patience.",
      "Elle écrit trois mots dans un carnet jaune.",
      "La journée commence léger, comme un sac bien rangé."
    ],
  },
  {
    slug: "plus-partage-repas",
    theme: "spirituality",
    min: 4,
    max: 7,
    emoji: "🍲",
    titleFr: "Partage du repas du soir",
    descFr: "Une famille prépare un repas et en offre une part au voisin.",
    titleEn: "Sharing the evening meal",
    descEn: "A family cooks and shares a portion with a neighbor.",
    titleAr: "مشاركة وجبة المساء",
    descAr: "عائلة تطبخ وتشارك جزءاً مع الجار.",
    premium: true,
    duration: 206,
    pages: [
      "La marmite sent le cumin et les légumes du jardin.",
      "Papa coupe le pain en parts égales sur la nappe bleue.",
      "Ils préparent une assiette supplémentaire pour Monsieur Ali.",
      "L'enfant frappe à la porte voisine, un peu timide.",
      "Monsieur Ali sourit : « Merci, vos mains sont généreuses. »",
      "Partager nourrit corps et liens silencieux du quartier."
    ],
  },
  {
    slug: "plus-pardon-fleurs",
    theme: "spirituality",
    min: 5,
    max: 8,
    emoji: "🌸",
    titleFr: "Pardon et bouquet de fleurs",
    descFr: "Deux amis se réconcilient en plantant des fleurs ensemble.",
    titleEn: "Forgiveness and a flower bouquet",
    descEn: "Two friends reconcile by planting flowers together.",
    titleAr: "العفو وباقة الزهور",
    descAr: "صديقان يتصالحان بزراعة الزهور معاً.",
    difficulty: "medium",
    duration: 206,
    pages: [
      "Ils se sont disputés pour un crayon bleu ce matin.",
      "Le silence a duré trop longtemps à la récréation.",
      "La maîtresse propose : « Plantez quelque chose ensemble. »",
      "Ils creusent, posent des graines, arrosent sans se parler.",
      "Puis l'un dit pardon ; l'autre répond merci, les yeux mouillés.",
      "Les fleurs pousseront plus vite que la rancune restée."
    ],
  },
  {
    slug: "plus-patience-graine",
    theme: "spirituality",
    min: 3,
    max: 5,
    emoji: "🌱",
    titleFr: "Patience et graine de bonheur",
    descFr: "Youssef apprend à attendre qu'une graine devienne fleur.",
    titleEn: "Patience and the happiness seed",
    descEn: "Youssef learns to wait for a seed to become a flower.",
    titleAr: "الصبر وبذرة السعادة",
    descAr: "youssef يتعلم انتظار البذرة حتى تصبح زهرة.",
    duration: 160,
    pages: [
      "Youssef plante une graine dans un pot en terre rouge.",
      "Chaque matin, il regarde : rien, encore rien, patience.",
      "Grand-père dit : « Sous la terre, la magie travaille lentement. »",
      "Un jour, deux feuilles vertes percent enfin la surface.",
      "Youssef applaudit sans toucher, respectueux du temps.",
      "Patience devient amie, pas ennemie qui fait attendre."
    ],
  },
  {
    slug: "plus-humilite-montagne",
    theme: "spirituality",
    min: 6,
    max: 10,
    emoji: "⛰️",
    titleFr: "Humilité devant la montagne",
    descFr: "Un guide explique que la montagne enseigne la modestie.",
    titleEn: "Humility before the mountain",
    descEn: "A guide explains the mountain teaches modesty.",
    titleAr: "التواضع أمام الجبل",
    descAr: "مرشد ي explain أن الجبل ي enseign التواضع.",
    premium: true,
    duration: 288,
    pages: [
      "La montagne se dresse ; les nuages lui couvrent la tête.",
      "Le guide rappelle : « Nous marchons sur elle, pas contre elle. »",
      "Les enfants avancent en silence, bottes lourdes mais cœurs légers.",
      "Un aigle passe ; personne ne crie victoire prématurée.",
      "Au sommet, ils regardent la vallée sans se croire plus grands.",
      "Humilité, c'est admirer sans vouloir tout posséder."
    ],
  },
  {
    slug: "plus-esperance-lanterne",
    theme: "spirituality",
    min: 4,
    max: 7,
    emoji: "🏮",
    titleFr: "Espérance et lanterne du Ramadan",
    descFr: "Fatima allume une lanterne qui porte l'espoir du mois béni.",
    titleEn: "Hope and the Ramadan lantern",
    descEn: "Fatima lights a lantern carrying hope of the blessed month.",
    titleAr: "الأمل وفانوس رمضان",
    descAr: "fatima تُضيء فانوساً يحمل أمل الشهر المبارك.",
    type: "audio_story",
    duration: 268,
    extraTags: ["ramadan"],
    audioFr: "Lanterne d espoir, brille doucement. Ramadan apporte partage, prière et cœurs plus larges.",
    audioEn: "Lantern of hope, shine gently. Ramadan brings sharing, prayer, and wider hearts.",
    audioAr: "فانوس الأمل، أضيئي بلطف. رمضان ي brings المشاركة والصلاة وقلوباً أوسع.",
    pages: [
      "Fatima accroche la lanterne colorée au balcon familial.",
      "La ville s'illumine ; des voisins échangent des dattes.",
      "Elle prépare une soupe pour ceux qui jeûnent ce soir.",
      "Papa lit un verset doux ; Fatima écoute, les mains jointes.",
      "Les étoiles semblent plus nombreuses pendant ce mois.",
      "Espérance brille même quand le vent souffle fort dehors."
    ],
  },
  {
    slug: "plus-amis-arbre",
    theme: "animals",
    min: 4,
    max: 7,
    emoji: "🌳",
    titleFr: "Amis sous le grand arbre",
    descFr: "Deux animaux différents partagent un arbre et des histoires.",
    titleEn: "Friends under the big tree",
    descEn: "Two different animals share a tree and stories.",
    titleAr: "أصدقاء تحت الشجرة الكبيرة",
    descAr: "حيوانان مختلفان يت sharing شجرة وقصصاً.",
    duration: 214,
    extraTags: ["friendship"],
    pages: [
      "Écureuil et Corbeau se disputaient le même nid d'hier.",
      "Ils décident de partager l'ombre large du chêne centenaire.",
      "Écureuil apporte des noisettes ; Corbeau une chanson grave.",
      "Les autres animaux viennent écouter sans payer d'entrée.",
      "La pluie tombe ; ils restent sec sous les feuilles serrées.",
      "Amitié, c'est un toit commun quand le ciel gronde."
    ],
  },
  {
    slug: "plus-gentillesse-coeur",
    theme: "spirituality",
    min: 3,
    max: 5,
    emoji: "💝",
    titleFr: "Gentillesse du cœur ouvert",
    descFr: "Mila offre son goûter à un camarade qui a oublié le sien.",
    titleEn: "Kindness of an open heart",
    descEn: "Mila shares her snack with a classmate who forgot his.",
    titleAr: "لطف القلب المفتوح",
    descAr: "mila تشارك وجبتها مع زميل نسي طعامه.",
    flags: "new",
    duration: 161,
    extraTags: ["kindness"],
    pages: [
      "Mila ouvre sa boîte : deux biscuits et une pomme rouge.",
      "Tom rougit : il a oublié son sac sur la table de la maison.",
      "Mila coupe la pomme en deux parts presque égales.",
      "Tom murmure merci ; Mila hausse les épaules : « C'est normal. »",
      "La maîtresse voit le geste et sourit sans commenter.",
      "La gentillesse se mange parfois en silence, sucrée."
    ],
  },
  {
    slug: "plus-colere-vague",
    theme: "bedtime",
    min: 4,
    max: 6,
    emoji: "😤",
    titleFr: "Colère qui passe comme une vague",
    descFr: "Un enfant apprend à laisser passer la colère avant de dormir.",
    titleEn: "Anger that passes like a wave",
    descEn: "A child learns to let anger pass before sleep.",
    titleAr: "الغضب الذي يمر كموجة",
    descAr: "طفل يتعلم ترك الغضب يمر قبل النوم.",
    duration: 264,
    extraTags: ["emotions"],
    pages: [
      "La colère brûle comme un soleil rouge dans la poitrine.",
      "Maman dit : « Respire ; la vague monte, puis redescend. »",
      "L'enfant dessine la colère en gros nuage gris sur papier.",
      "Il froisse le papier et le pose dans la corbeille.",
      "Les épaules descendent ; la respiration redevient régulière.",
      "Dormir devient possible quand la vague s'est éloignée."
    ],
  },
  {
    slug: "plus-grands-parents-histoire",
    theme: "world",
    min: 3,
    max: 6,
    emoji: "👴",
    titleFr: "Grands-parents et la boîte à histoires",
    descFr: "Grand-mère sort des photos et raconte le passé de la famille.",
    titleEn: "Grandparents and the story box",
    descEn: "Grandma brings photos and tells the family past.",
    titleAr: "الأgrandparents وصندوق الحكايات",
    descAr: " الجدة تخرج صوراً وتحكي ماضي العائلة.",
    premium: true,
    duration: 251,
    extraTags: ["family"],
    pages: [
      "Grand-mère ouvre une boîte en bois pleine de photos pliées.",
      "Elle montre un mariage, une maison bleue, un bébé qui pleure.",
      "L'enfant pose mille questions ; elle répond avec patience.",
      "Grand-père ajoute une blague ; tout le monde rit fort.",
      "Ils collent une photo récente au fond de la boîte.",
      "Famille, c'est une histoire qu'on continue ensemble."
    ],
  },
  {
    slug: "plus-rentree-crayons",
    theme: "jobs",
    min: 5,
    max: 7,
    emoji: "✏️",
    titleFr: "Rentrée et crayons neufs",
    descFr: "La première journée d'école sent le bois et l'excitation.",
    titleEn: "Back to school and new pencils",
    descEn: "The first school day smells of wood and excitement.",
    titleAr: "العودة للمدرسة وأقلام جديدة",
    descAr: "أول يوم مدرسي ي ر smell الخشب والحماس.",
    duration: 263,
    extraTags: ["school"],
    pages: [
      "Le cartable est lourd de cahiers et de règles propres.",
      "Les crayons neufs sentent le bois taillé et la gomme.",
      "La maîtresse accueille chaque prénom à la porte de classe.",
      "Un nouvel élève serre sa main ; l'accueil est chaleureux.",
      "Ils dessinent leur été en dix minutes de silence joyeux.",
      "L'école redevient lieu de rencontres, pas de peur seule."
    ],
  },
  {
    slug: "plus-labo-couleurs",
    theme: "colors",
    min: 6,
    max: 9,
    emoji: "🔬",
    titleFr: "Labo des couleurs et volcan",
    descFr: "Des enfants mélangent bicarbonate et vinaigre pour un volcan safe.",
    titleEn: "Color lab and volcano",
    descEn: "Kids mix baking soda and vinegar for a safe volcano.",
    titleAr: "مختبر الألوان والبركان",
    descAr: "أطفال يmezجون bicarbonate وخل لبركان آمن.",
    difficulty: "medium",
    duration: 284,
    extraTags: ["science"],
    pages: [
      "Sur la table protégée, le volcan en papier mâché attend.",
      "Ils versent le vinaigre coloré en bleu puis en rouge.",
      "La mousse monte ; les enfants reculent en riant, émerveillés.",
      "La maîtresse explique la réaction sans mots compliqués.",
      "Ils notent ce qu'ils voient dans un carnet de scientifiques.",
      "Science, c'est regarder le monde avec des questions joyeuses."
    ],
  },
  {
    slug: "plus-automne-feuilles",
    theme: "world",
    min: 3,
    max: 5,
    emoji: "🍂",
    titleFr: "Automne et couronne de feuilles",
    descFr: "Les enfants fabriquent des couronnes avec les feuilles tombées.",
    titleEn: "Autumn and leaf crowns",
    descEn: "Children make crowns with fallen leaves.",
    titleAr: "الخريف وإكليل الأوراق",
    descAr: "أطفال يصنعون أكاليل من الأوراق المتساقطة.",
    duration: 188,
    extraTags: ["seasons"],
    pages: [
      "Le parc craque sous les bottes ; l'air sent la terre humide.",
      "Ils ramassent rouge, orange, jaune sans froisser trop.",
      "Avec du ruban adhésif, ils compose des couronnes royales.",
      "Un vent fort en emporte une ; ils courent la rattraper.",
      "Maman prend une photo ; les sourires sont aussi colorés.",
      "Automne n'est pas une fin : c'est une fête de couleurs."
    ],
  },
  {
    slug: "plus-orchestre-foret",
    theme: "rhymes",
    min: 4,
    max: 7,
    emoji: "🎻",
    titleFr: "Orchestre secret de la forêt",
    descFr: "Les animaux forment un orchestre au clair de lune.",
    titleEn: "Secret forest orchestra",
    descEn: "Animals form an orchestra in moonlight.",
    titleAr: "أوركستra الغابة السرية",
    descAr: "حيوانات تشكل أوركستra في ضوء القمر.",
    type: "audio_story",
    duration: 249,
    extraTags: ["music"],
    audioFr: "Forêt musicienne, joue ce soir. Grillon, hibou, rivière : votre symphonie berce la terre.",
    audioEn: "Musical forest, play tonight. Cricket, owl, river: your symphony rocks the earth.",
    audioAr: "أيتها الغابة الموسيقية، العزفي الليلة. صرصور، بومة، نهر: سимфонيتكم تهدهد الأرض.",
    pages: [
      "Le grillon dirige avec une brindille comme baguette.",
      "Hibou souffle dans une feuille enroulée, note grave.",
      "La rivière bat le tempo avec des cailloux ronds.",
      "Les lucioles éclairent la scène naturelle.",
      "Un renard ferme les yeux, public respectueux.",
      "La symphonie finit ; la forêt retient encore la mélodie."
    ],
  },
  {
    slug: "plus-peinture-mur",
    theme: "colors",
    min: 5,
    max: 8,
    emoji: "🎨",
    titleFr: "Peinture murale du quartier",
    descFr: "Des enfants peignent un mur avec l'accord des voisins.",
    titleEn: "Neighborhood mural painting",
    descEn: "Children paint a wall with neighbors' approval.",
    titleAr: "جدارية الحي",
    descAr: "أطفال يرسمون جداراً بموافقة الجيران.",
    premium: true,
    duration: 252,
    extraTags: ["arts"],
    pages: [
      "Le mur gris attend depuis des années une idée colorée.",
      "Les voisins votent : des oiseaux, des fleurs, des mains jointes.",
      "Chacun reçoit un pinceau et une zone à remplir.",
      "La peinture coule parfois ; on rit et on essuie.",
      "Le mur devient carte du quartier imaginaire.",
      "Art, c'est transformer un mur en invitation au rêve."
    ],
  },
  {
    slug: "plus-recyclage-mer",
    theme: "ocean",
    min: 6,
    max: 10,
    emoji: "♻️",
    titleFr: "Recyclage pour la mer propre",
    descFr: "Une classe ramasse des déchets sur la plage après la marée.",
    titleEn: "Recycling for a clean sea",
    descEn: "A class picks trash on the beach after the tide.",
    titleAr: "إعادة التدوير من أجل بحر نظيف",
    descAr: "صف يلتقط نفايات الشاطئ بعد المد.",
    duration: 347,
    extraTags: ["environment"],
    pages: [
      "Gants orange, sacs transparents, soleil doux du matin.",
      "Ils trouvent des bouchons, du fil, une bouteille écrasée.",
      "Le guide explique comment chaque déchet peut renaître.",
      "Un crabe observe, curieux, sans craindre les enfants.",
      "Ils pèsent le sac : dix kilos de moins dans l'eau.",
      "Protéger la mer commence par des mains qui ramassent."
    ],
  },
  {
    slug: "plus-carte-tresor",
    theme: "vehicles",
    min: 5,
    max: 8,
    emoji: "🗺️",
    titleFr: "Carte au trésor en vélo",
    descFr: "Deux frères suivent une carte dessinée à travers le quartier.",
    titleEn: "Treasure map by bike",
    descEn: "Two brothers follow a hand-drawn map through the neighborhood.",
    titleAr: "خريطة كنز بالدراجة",
    descAr: "أخوان يتبعان خريطة مرسومة في الحي.",
    flags: "pop",
    duration: 205,
    extraTags: ["adventure"],
    pages: [
      "La carte indique : arbre tordu, banc bleu, fontaine muette.",
      "Ils pédalent lentement, lisant les indices à voix basse.",
      "Au banc bleu, une boîte en métal attend sous une pierre.",
      "Dedans : des stickers, un mot du papa, zéro or.",
      "Ils rient : le trésor, c'était l'aventure à deux.",
      "Rentrer tard goûte encore mieux après une quête réussie."
    ],
  },
  {
    slug: "plus-ferme-matin",
    theme: "animals",
    min: 3,
    max: 5,
    emoji: "🐄",
    titleFr: "Ferme au lever du soleil",
    descFr: "Une visite à la ferme réveille tous les sens des enfants.",
    titleEn: "Farm at sunrise",
    descEn: "A farm visit wakes all the children's senses.",
    titleAr: "المزرعة عند شروق الشمس",
    descAr: "زيارة مزرعة توقظ حواس الأطفال.",
    duration: 156,
    extraTags: ["farm"],
    pages: [
      "Le coq chante ; les vaches mugissent doucement dans la brume.",
      "Les enfants traient une chèvre avec la fermière patiente.",
      "Ils caressent un poussin chaud, cœur battant vite.",
      "L'odeur de foin remplit le hangar en bois.",
      "Ils goûtent du lait frais et du fromage blanc.",
      "La ferme enseigne d'où viennent nos repas quotidiens."
    ],
  },
  {
    slug: "plus-tigre-sentier",
    theme: "animals",
    min: 6,
    max: 9,
    emoji: "🐯",
    titleFr: "Tigre et sentier de jungle",
    descFr: "Un guide montre un tigre de loin dans une réserve protégée.",
    titleEn: "Tiger and jungle trail",
    descEn: "A guide shows a tiger from afar in a protected reserve.",
    titleAr: "النمر ودرب الأدغال",
    descAr: "مرشد يُظهر نمراً من ب lejos في محمية.",
    difficulty: "medium",
    premium: true,
    duration: 342,
    extraTags: ["jungle"],
    pages: [
      "La jungle est humide ; les feuilles larges filtrent la lumière.",
      "Le guide chuchote : « Regardez, là-bas, près de l'eau. »",
      "Un tigre boit, rayures orange coupant l'ombre verte.",
      "Les enfants restent immobiles, respiration suspendue.",
      "Le tigre disparaît sans bruit, majestueux et libre.",
      "Respecter la jungle, c'est observer sans posséder."
    ],
  },
  {
    slug: "plus-ecole-jardin",
    theme: "spirituality",
    min: 4,
    max: 6,
    emoji: "🌻",
    titleFr: "Jardin de l'école et mains vertes",
    descFr: "Les élèves plantent un jardin pour nourrir la cantine.",
    titleEn: "School garden and green hands",
    descEn: "Students plant a garden to feed the cafeteria.",
    titleAr: "حديقة المدرسة وأيدي خضراء",
    descAr: "تلاميذ يزرعون حديقة لإطعام الم cantine.",
    duration: 200,
    extraTags: ["school","kindness"],
    pages: [
      "Chaque classe reçoit un carré de terre au soleil.",
      "Ils plantent radis, salade, fleurs pour les abeilles.",
      "L'eau du robinet coule ; les mains deviennent brunes.",
      "La directrice goûte une feuille : « Merci, c'est délicieux. »",
      "Les élèves comprennent le travail derrière chaque repas.",
      "Une école qui cultive apprend aussi à cultiver l'entraide."
    ],
  },
];


export function buildPlus100ExpansionCatalog() {
  return DEFS.map((d, i) => book(i, d));
}
