/**
 * Catalogue éditorial original HKids — contenu démo partenaire.
 * Textes originaux, libres de droits. Exécuter: npm run seed:catalog
 */

import { buildExtendedCatalog } from './catalogExtended.js';
import { buildPremiumExpansionCatalog } from './catalogPremiumExpansion.js';
import { buildPlus100ExpansionCatalog } from './catalogPlus100Expansion.js';
import { enrichCatalogWithPages } from './storyPages.js';

export const BASE_CATALOG = [
  {
    slug: 'demo-dino-courage',
    title: 'Le petit dinosaure courageux',
    author: 'Le Lit Qui Lit',
    description: 'Une histoire douce sur la confiance et la nuit.',
    content_type: 'story',
    language: 'fr',
    theme: 'dinosaurs',
    category_name: 'Dinosaures',
    age_group_min: 3,
    age_group_max: 6,
    is_recommended: true,
    is_new: true,
    emoji: '🦖',
    gradient: ['#7b3eb8', '#389d85'],
    pages: [
      { text: 'Il était une fois un petit dinosaure vert qui adorait jouer au soleil.' },
      { text: 'Le soir, il avait un peu peur du noir. Il serrait fort son doudou.' },
      { text: 'Sa maman lui dit : « Ta lumière, c est ton courage. » Il s endormit en souriant.' },
    ],
    localizations: {
      en: { title: 'The brave little dinosaur', description: 'A gentle story about confidence and nighttime.' },
      ar: { title: 'الديناصور الصغير الشجاع', description: 'قصة هادئة عن الثقة والليل.' },
    },
  },
  {
    slug: 'demo-voyage-lune',
    title: 'Voyage sur la lune',
    author: 'Le Lit Qui Lit',
    description: 'Un voyage calme dans l espace, parmi les étoiles.',
    content_type: 'story',
    language: 'fr',
    theme: 'space',
    category_name: 'Espace',
    age_group_min: 4,
    age_group_max: 8,
    is_popular: true,
    emoji: '🚀',
    gradient: ['#1e3a8a', '#7b3eb8'],
    pages: [
      { text: 'Ce soir, une petite fusée douce décolle vers la lune.' },
      { text: 'Par le hublot, les étoiles brillent comme des lucioles.' },
      { text: 'Sur la lune, tout est calme. Bonne nuit, petit astronaute.' },
    ],
    localizations: {
      en: { title: 'Trip to the moon', description: 'A calm journey through the stars.' },
      ar: { title: 'رحلة إلى القمر', description: 'رحلة هادئة بين النجوم.' },
    },
  },
  {
    slug: 'demo-trois-cochons',
    title: 'Les trois petits cochons',
    author: 'Le Lit Qui Lit',
    description: 'Un classique adapté aux tout-petits.',
    content_type: 'story',
    language: 'fr',
    theme: 'world',
    category_name: 'Histoires',
    age_group_min: 3,
    age_group_max: 7,
    emoji: '🐷',
    gradient: ['#f76219', '#fbbf24'],
    pages: [
      { text: 'Trois petits cochons construisent chacun une maison.' },
      { text: 'Le loup souffle fort. Paille et bois tombent.' },
      { text: 'La maison de briques tient bon. Les trois frères dansent de joie.' },
    ],
    localizations: {
      en: { title: 'The three little pigs', description: 'A toddler-friendly classic.' },
      ar: { title: 'الخنازير الثلاثة الصغيرة', description: 'كلاسيكية مناسبة للصغار.' },
    },
  },
  {
    slug: 'fee-des-couleurs',
    title: 'La fée des couleurs',
    author: 'Le Lit Qui Lit',
    description: 'Découvre le rouge, le bleu et le jaune avec Lila.',
    content_type: 'story',
    language: 'fr',
    theme: 'colors',
    category_name: 'Histoires',
    age_group_min: 2,
    age_group_max: 5,
    is_new: true,
    emoji: '🎨',
    gradient: ['#ec4899', '#8b5cf6'],
    pages: [
      { text: 'Lila la fée ouvre son coffre magique de couleurs.' },
      { text: 'Rouge comme une fraise, bleu comme la mer, jaune comme le soleil.' },
      { text: 'Elle peint un arc-en-ciel. Tous les enfants applaudissent.' },
    ],
    localizations: {
      en: { title: 'The color fairy', description: 'Learn red, blue and yellow with Lila.' },
      ar: { title: 'جنية الألوان', description: 'اكتشف الأحمر والأزرق والأصفر مع ليلى.' },
    },
  },
  {
    slug: 'princesse-lina',
    title: 'Princesse Lina et le dragon gentil',
    author: 'Le Lit Qui Lit',
    description: 'Une princesse courageuse et un dragon qui aime les fleurs.',
    content_type: 'story',
    language: 'fr',
    theme: 'princesses',
    category_name: 'Histoires',
    age_group_min: 4,
    age_group_max: 8,
    is_recommended: true,
    emoji: '👸',
    gradient: ['#db2777', '#7b3eb8'],
    pages: [
      { text: 'Princesse Lina vit dans un château tout en douceur.' },
      { text: 'Un dragon arrive. Il ne crache pas du feu : il offre des marguerites.' },
      { text: 'Ils deviennent amis et partagent un goûter au jardin.' },
    ],
    localizations: {
      en: { title: 'Princess Lina and the kind dragon', description: 'Friendship and flowers in a fairy tale.' },
      ar: { title: 'الأميرة لينا والتنين اللطيف', description: 'صداقة وزهور في حكاية خيالية.' },
    },
  },
  {
    slug: 'chat-curieux',
    title: 'Le chat curieux',
    author: 'Le Lit Qui Lit',
    description: 'Mimi le chat explore le jardin et rencontre un papillon.',
    content_type: 'story',
    language: 'fr',
    theme: 'animals',
    category_name: 'Histoires',
    age_group_min: 2,
    age_group_max: 5,
    emoji: '🐱',
    gradient: ['#389d85', '#34d399'],
    pages: [
      { text: 'Mimi le chat sort doucement dans le jardin.' },
      { text: 'Un papillon bleu vole autour de son nez. Mimi rigole.' },
      { text: 'Ils jouent ensemble puis font une sieste au soleil.' },
    ],
    localizations: {
      en: { title: 'The curious cat', description: 'Mimi explores the garden and meets a butterfly.' },
      ar: { title: 'القط الفضولي', description: 'ميمي يستكشف الحديقة ويلتقي فراشة.' },
    },
  },
  {
    slug: 'pompiers-heroes',
    title: 'Les pompiers héros',
    author: 'Le Lit Qui Lit',
    description: 'Découvre le métier de pompier avec Sami.',
    content_type: 'story',
    language: 'fr',
    theme: 'jobs',
    category_name: 'Histoires',
    age_group_min: 3,
    age_group_max: 7,
    emoji: '🚒',
    gradient: ['#dc2626', '#f97316'],
    pages: [
      { text: 'Sami porte un casque rouge. Il monte dans la grande échelle.' },
      { text: 'La sirène chante. Les pompiers aident tout le monde avec gentillesse.' },
    ],
    localizations: {
      en: { title: 'Hero firefighters', description: 'Discover firefighters with Sami.' },
      ar: { title: 'أبطال الإطفاء', description: 'اكتشف مهنة الإطفاء مع سامي.' },
    },
  },
  {
    slug: 'abc-jardin',
    title: 'ABC du jardin',
    author: 'Le Lit Qui Lit',
    description: 'A comme abeille, B comme bouton, C comme chenille.',
    content_type: 'story',
    language: 'fr',
    theme: 'alphabet',
    category_name: 'Histoires',
    age_group_min: 3,
    age_group_max: 6,
    emoji: '🔤',
    gradient: ['#2563eb', '#06b6d4'],
    pages: [
      { text: 'A comme Abeille qui butine. B comme Bouton doré.' },
      { text: 'C comme Chenille, D comme Dauphin dans la mare.' },
    ],
    localizations: {
      en: { title: 'Garden ABC', description: 'A for ant, B for bud, C for caterpillar.' },
      ar: { title: 'أبجدية الحديقة', description: 'أ للنحلة، ب للزهرة، ج لليرقة.' },
    },
  },
  {
    slug: 'compte-avec-moi',
    title: 'Compte avec moi',
    author: 'Le Lit Qui Lit',
    description: 'Un, deux, trois pommes dans le panier.',
    content_type: 'story',
    language: 'fr',
    theme: 'numbers',
    category_name: 'Histoires',
    age_group_min: 2,
    age_group_max: 5,
    emoji: '🔢',
    gradient: ['#7c3aed', '#a855f7'],
    pages: [
      { text: 'Un soleil, deux nuages, trois oiseaux dans le ciel.' },
      { text: 'Quatre fleurs, cinq gouttes de pluie. Comptons ensemble !' },
    ],
    localizations: {
      en: { title: 'Count with me', description: 'One, two, three apples in the basket.' },
      ar: { title: 'لنعد معاً', description: 'واحدة، اثنتان، ثلاث تفاحات في السلة.' },
    },
  },
  {
    slug: 'demo-comptine-etoiles',
    title: 'Comptine des étoiles',
    author: 'Le Lit Qui Lit',
    description: 'Une comptine douce pour s endormir.',
    content_type: 'audio_story',
    language: 'fr',
    theme: 'space',
    category_name: 'Comptines',
    age_group_min: 2,
    age_group_max: 6,
    is_popular: true,
    emoji: '⭐',
    gradient: ['#312e81', '#6366f1'],
    audio_text: 'Petite étoile, brillante étoile, je te vois là-haut. Ferme les yeux, bonne nuit, rêve tout doux.',
    duration_seconds: 12,
    localizations: {
      en: { title: 'Star lullaby', description: 'A soft bedtime rhyme.', audio_text: 'Little star, shining star, up above the world so high. Close your eyes, sleep tight, dream sweet dreams tonight.' },
      ar: { title: 'أنشودة النجوم', description: 'أنشودة هادئة للنوم.', audio_text: 'نجمة صغيرة تلمع في السماء. أغمض عينيك، تصبح على خير، أحلاماً سعيدة.' },
    },
  },
  {
    slug: 'demo-bonne-nuit-ours',
    title: 'Bonne nuit petit ours',
    author: 'Le Lit Qui Lit',
    description: 'Une berceuse pour les tout-petits.',
    content_type: 'audio_story',
    language: 'fr',
    theme: 'animals',
    category_name: 'Comptines',
    age_group_min: 2,
    age_group_max: 5,
    is_recommended: true,
    emoji: '🐻',
    gradient: ['#92400e', '#d97706'],
    audio_text: 'Dodo petit ours, dans ta grotte douce. La lune veille sur toi. Bonne nuit, fais de beaux rêves.',
    duration_seconds: 11,
    localizations: {
      en: { title: 'Good night little bear', description: 'A lullaby for toddlers.', audio_text: 'Sleep tight little bear, in your cozy den. The moon watches over you. Good night, sweet dreams.' },
      ar: { title: 'تصبح على خير أيها الدب', description: 'تهويدة للصغار.', audio_text: 'نم يا دب الصغير في عرينك الدافئ. القمر يحرسك. تصبح على خير، أحلاماً جميلة.' },
    },
  },
  {
    slug: 'comptine-animaux',
    title: 'Comptine des animaux',
    author: 'Le Lit Qui Lit',
    description: 'Le chat fait miaou, le chien fait ouaf.',
    content_type: 'audio_story',
    language: 'fr',
    theme: 'animals',
    category_name: 'Comptines',
    age_group_min: 2,
    age_group_max: 5,
    is_new: true,
    emoji: '🎵',
    gradient: ['#059669', '#10b981'],
    audio_text: 'Le chat fait miaou, le chien fait ouaf, la vache fait meuh. Chantons tous ensemble, c est rigolo !',
    duration_seconds: 10,
    localizations: {
      en: { title: 'Animal song', description: 'The cat says meow, the dog says woof.', audio_text: 'The cat says meow, the dog says woof, the cow says moo. Let us sing together, it is fun!' },
      ar: { title: 'أنشودة الحيوانات', description: 'القط يقول مواء، الكلب يقول نباح.', audio_text: 'القط يقول مواء، الكلب يقول نباح، البقرة تقول خوخ. لنغني معاً، إنه ممتع!' },
    },
  },
  {
    slug: 'chanson-du-matin',
    title: 'Chanson du matin',
    author: 'Le Lit Qui Lit',
    description: 'Un réveil joyeux pour commencer la journée.',
    content_type: 'song',
    language: 'fr',
    theme: 'rhymes',
    category_name: 'Comptines',
    age_group_min: 2,
    age_group_max: 6,
    emoji: '🌅',
    gradient: ['#f59e0b', '#f76219'],
    audio_text: 'Bonjour le soleil, bonjour la journée. On s étire, on sourit, c est parti pour jouer !',
    duration_seconds: 9,
    localizations: {
      en: { title: 'Morning song', description: 'A cheerful wake-up song.', audio_text: 'Hello sunshine, hello new day. We stretch, we smile, time to go and play!' },
      ar: { title: 'أغنية الصباح', description: 'استيقاظ مبهج لبداية اليوم.', audio_text: 'صباح الخير يا شمس، صباح الخير يا يوم. نتمطد ونبتسم، حان وقت اللعب!' },
    },
  },
];

export const CATALOG = enrichCatalogWithPages([
  ...BASE_CATALOG,
  ...buildExtendedCatalog(),
  ...buildPremiumExpansionCatalog(),
  ...buildPlus100ExpansionCatalog(),
]);

export const CATALOG_STATS = {
  total: CATALOG.length,
  illustrated_stories: CATALOG.filter((item) => item.content_type === 'story').length,
  audio_stories: CATALOG.filter((item) => item.content_type === 'audio_story').length,
  songs: CATALOG.filter((item) => item.content_type === 'song').length,
  religious: CATALOG.filter((item) => item.theme === 'spiritual' || item.theme === 'spirituality').length,
  premium_expansion: CATALOG.filter((item) => String(item.slug || '').startsWith('prem-')).length,
  plus_100_expansion: CATALOG.filter((item) => String(item.slug || '').startsWith('plus-')).length,
  premium_flagged: CATALOG.filter((item) => item.is_premium).length,
};
