import { buildLocalizations, buildTags, pickGradient } from './catalogMeta.js';

const AUTHOR = 'Le Lit Qui Lit';

const AREA_CONFIG = {
  audiobooks: { category: 'Livres audio', theme: 'bedtime', emoji: '🎧', type: 'audio_story' },
  languages: { category: 'Langues', theme: 'languages', emoji: '🗣️', type: 'audio_story' },
  religion: { category: 'Religion et valeurs', theme: 'spirituality', emoji: '🕊️', type: 'audio_story' },
  rhymes: { category: 'Comptines', theme: 'rhymes', emoji: '🎵', type: 'song' },
  science: { category: 'Sciences', theme: 'science', emoji: '🔬', type: 'story' },
  geography: { category: 'Géographie', theme: 'geography', emoji: '🗺️', type: 'story' },
  creativity: { category: 'Créativité', theme: 'creativity', emoji: '🎨', type: 'story' },
  characters: { category: 'Personnages premium', theme: 'characters', emoji: '✨', type: 'story' },
};

const DEFS = [
  {
    area: 'audiobooks', slug: 'final-audio-foret-endormie', min: 3, max: 6,
    titleFr: 'La forêt qui s’endort', titleEn: 'The forest falls asleep', titleAr: 'الغابة التي تنام',
    descFr: 'Une promenade sonore apaisante où chaque animal trouve son nid.',
    descEn: 'A soothing audio walk where every animal finds its nest.',
    descAr: 'جولة صوتية هادئة يجد فيها كل حيوان عشه.',
    audioFr: 'Le soleil descend. Le lapin rejoint son terrier, l’oiseau replie ses ailes et la forêt respire doucement. Bonne nuit, petits amis.',
    audioEn: 'The sun goes down. Rabbit returns to his burrow, bird folds its wings, and the forest breathes softly. Good night, little friends.',
    audioAr: 'تغيب الشمس. يعود الأرنب إلى جحره ويطوي العصفور جناحيه وتتنفس الغابة بهدوء. تصبحون على خير يا أصدقاء.',
    subjects: ['sleep', 'animals'], skills: ['listening', 'self-regulation'],
  },
  {
    area: 'audiobooks', slug: 'final-audio-ocean-calme', min: 4, max: 8,
    titleFr: 'Le secret de l’océan calme', titleEn: 'The secret of the calm ocean', titleAr: 'سر المحيط الهادئ',
    descFr: 'Mina écoute les baleines et apprend à protéger la mer.',
    descEn: 'Mina listens to whales and learns to protect the sea.',
    descAr: 'تستمع مينا إلى الحيتان وتتعلم حماية البحر.',
    audioFr: 'Mina écoute un chant profond sous les vagues. La baleine lui confie un secret : chaque petit geste protège l’océan.',
    audioEn: 'Mina hears a deep song beneath the waves. The whale shares a secret: every small action protects the ocean.',
    audioAr: 'تسمع مينا أغنية عميقة تحت الأمواج. يهمس الحوت بسر: كل عمل صغير يحمي المحيط.',
    subjects: ['ocean', 'environment'], skills: ['listening', 'responsibility'],
  },
  {
    area: 'audiobooks', slug: 'final-audio-train-histoires', min: 6, max: 10,
    titleFr: 'Le train des mille histoires', titleEn: 'The train of a thousand stories', titleAr: 'قطار الألف حكاية',
    descFr: 'Un voyage audio à travers des paysages et des récits du monde.',
    descEn: 'An audio journey through landscapes and stories from around the world.',
    descAr: 'رحلة صوتية عبر مناظر وحكايات من أنحاء العالم.',
    audioFr: 'Le train quitte la gare. À chaque fenêtre apparaît un nouveau pays, une voix, une musique et une histoire à partager.',
    audioEn: 'The train leaves the station. Every window reveals a new country, a voice, music, and a story to share.',
    audioAr: 'يغادر القطار المحطة. تكشف كل نافذة بلداً جديداً وصوتاً وموسيقى وحكاية نتشاركها.',
    subjects: ['world', 'cultures'], skills: ['listening', 'curiosity'],
  },
  {
    area: 'languages', slug: 'final-language-first-words', min: 2, max: 5,
    titleFr: 'Mes premiers mots en trois langues', titleEn: 'My first words in three languages', titleAr: 'كلماتي الأولى بثلاث لغات',
    descFr: 'Bonjour, hello et مرحبا dans une aventure sonore joyeuse.',
    descEn: 'Bonjour, hello, and مرحبا in a joyful sound adventure.',
    descAr: 'Bonjour وhello ومرحبا في مغامرة صوتية مرحة.',
    audioFr: 'Bonjour, hello, مرحبا. Merci, thank you, شكراً. Trois langues, trois façons de se faire un nouvel ami.',
    audioEn: 'Hello, bonjour, مرحبا. Thank you, merci, شكراً. Three languages, three ways to make a new friend.',
    audioAr: 'مرحبا، bonjour، hello. شكراً، merci، thank you. ثلاث لغات وثلاث طرق لصنع صديق جديد.',
    subjects: ['french', 'english', 'arabic'], skills: ['vocabulary', 'pronunciation'],
  },
  {
    area: 'languages', slug: 'final-language-market', min: 5, max: 8,
    titleFr: 'Au marché des langues', titleEn: 'At the language market', titleAr: 'في سوق اللغات',
    descFr: 'Apprendre les couleurs, les nombres et les formules de politesse.',
    descEn: 'Learn colors, numbers, and polite expressions.',
    descAr: 'تعلم الألوان والأرقام وعبارات الأدب.',
    audioFr: 'Une pomme rouge, a red apple, تفاحة حمراء. Deux pains, two loaves, رغيفان. Merci au revoir, thank you goodbye, شكراً إلى اللقاء.',
    audioEn: 'A red apple, une pomme rouge, تفاحة حمراء. Two loaves, deux pains, رغيفان. Thank you, merci, شكراً.',
    audioAr: 'تفاحة حمراء، une pomme rouge، a red apple. رغيفان، deux pains، two loaves. شكراً، merci، thank you.',
    subjects: ['vocabulary', 'numbers', 'colors'], skills: ['speaking', 'memory'],
  },
  {
    area: 'languages', slug: 'final-language-world-greetings', min: 7, max: 10,
    titleFr: 'Le tour du monde des bonjours', titleEn: 'Hello around the world', titleAr: 'تحيات من حول العالم',
    descFr: 'Découvrir comment saluer avec respect dans plusieurs cultures.',
    descEn: 'Discover respectful greetings in several cultures.',
    descAr: 'اكتشف طرق التحية باحترام في ثقافات متعددة.',
    audioFr: 'Bonjour, hello, مرحبا, hola, ciao. Un salut ouvre la conversation quand il est accompagné d’un sourire et de respect.',
    audioEn: 'Hello, bonjour, مرحبا, hola, ciao. A greeting opens a conversation when it comes with a smile and respect.',
    audioAr: 'مرحبا، hello، bonjour، hola، ciao. تفتح التحية باب الحديث عندما ترافقها ابتسامة واحترام.',
    subjects: ['languages', 'cultures'], skills: ['pronunciation', 'social-awareness'],
  },
  {
    area: 'religion', slug: 'final-values-kindness-light', min: 3, max: 6,
    titleFr: 'La petite lumière de bonté', titleEn: 'The little light of kindness', titleAr: 'نور اللطف الصغير',
    descFr: 'Une histoire inclusive sur la bonté, la gratitude et l’entraide.',
    descEn: 'An inclusive story about kindness, gratitude, and helping others.',
    descAr: 'قصة شاملة عن اللطف والامتنان ومساعدة الآخرين.',
    audioFr: 'Chaque geste gentil allume une petite lumière. Un merci, un partage, une main tendue : bientôt tout le quartier brille.',
    audioEn: 'Every kind act lights a little lamp. A thank you, sharing, a helping hand: soon the whole neighborhood glows.',
    audioAr: 'كل عمل لطيف يضيء نوراً صغيراً. كلمة شكر ومشاركة ويد مساعدة تجعل الحي كله يلمع.',
    subjects: ['values', 'gratitude'], skills: ['empathy', 'kindness'],
  },
  {
    area: 'religion', slug: 'final-values-peace-garden', min: 5, max: 8,
    titleFr: 'Le jardin de la paix', titleEn: 'The garden of peace', titleAr: 'حديقة السلام',
    descFr: 'Des enfants de traditions différentes cultivent un jardin commun.',
    descEn: 'Children from different traditions grow a shared garden.',
    descAr: 'أطفال من تقاليد مختلفة يزرعون حديقة مشتركة.',
    audioFr: 'Chacun apporte une graine et une parole de paix. Les fleurs sont différentes, mais elles partagent la même terre et la même pluie.',
    audioEn: 'Each child brings a seed and a word of peace. The flowers differ, but share the same soil and rain.',
    audioAr: 'يحضر كل طفل بذرة وكلمة سلام. تختلف الأزهار لكنها تتشارك الأرض والمطر.',
    subjects: ['faith', 'peace', 'diversity'], skills: ['respect', 'cooperation'],
  },
  {
    area: 'religion', slug: 'final-values-sharing-moon', min: 7, max: 10,
    titleFr: 'Sous la lune du partage', titleEn: 'Under the moon of sharing', titleAr: 'تحت قمر المشاركة',
    descFr: 'Une soirée de générosité, de réflexion et de liens familiaux.',
    descEn: 'An evening of generosity, reflection, and family connection.',
    descAr: 'أمسية من الكرم والتأمل والترابط العائلي.',
    audioFr: 'Sous la lune, la famille prépare un repas pour ses voisins. Le partage nourrit le corps et rapproche les cœurs.',
    audioEn: 'Under the moon, the family prepares a meal for their neighbors. Sharing feeds the body and brings hearts closer.',
    audioAr: 'تحت القمر تعد العائلة وجبة للجيران. المشاركة تغذي الجسد وتقرب القلوب.',
    subjects: ['generosity', 'family'], skills: ['reflection', 'citizenship'],
  },
  {
    area: 'rhymes', slug: 'final-rhyme-alphabet-dance', min: 2, max: 5,
    titleFr: 'La danse de l’alphabet', titleEn: 'The alphabet dance', titleAr: 'رقصة الحروف',
    descFr: 'Une comptine rythmée pour reconnaître les premières lettres.',
    descEn: 'A rhythmic rhyme for recognizing first letters.',
    descAr: 'أنشودة إيقاعية للتعرف على الحروف الأولى.',
    audioFr: 'A fait un pas, B frappe des mains, C tourne en rond. Les lettres dansent jusqu’au matin.',
    audioEn: 'A takes a step, B claps hands, C spins around. The letters dance until morning.',
    audioAr: 'أ يخطو خطوة، ب يصفق، ت يدور. ترقص الحروف حتى الصباح.',
    subjects: ['alphabet', 'music'], skills: ['phonological-awareness', 'movement'],
  },
  {
    area: 'rhymes', slug: 'final-rhyme-planets', min: 5, max: 8,
    titleFr: 'La ronde des planètes', titleEn: 'The planets go round', titleAr: 'دائرة الكواكب',
    descFr: 'Une chanson pour mémoriser les planètes du système solaire.',
    descEn: 'A song for remembering the planets in the solar system.',
    descAr: 'أغنية لحفظ كواكب المجموعة الشمسية.',
    audioFr: 'Mercure, Vénus, Terre et Mars, Jupiter danse avec Saturne, Uranus, Neptune tournent au loin.',
    audioEn: 'Mercury, Venus, Earth and Mars, Jupiter dances with Saturn, Uranus and Neptune spin afar.',
    audioAr: 'عطارد والزهرة والأرض والمريخ، يرقص المشتري مع زحل، ويدور أورانوس ونبتون بعيداً.',
    subjects: ['space', 'science'], skills: ['memory', 'rhythm'],
  },
  {
    area: 'rhymes', slug: 'final-rhyme-continents', min: 7, max: 10,
    titleFr: 'Sept continents en chanson', titleEn: 'Seven continents song', titleAr: 'أغنية القارات السبع',
    descFr: 'Une comptine géographique pour voyager en rythme.',
    descEn: 'A geography rhyme for traveling to the beat.',
    descAr: 'أنشودة جغرافية للسفر مع الإيقاع.',
    audioFr: 'Afrique, Europe, Asie, Amérique du Nord et du Sud, Océanie, Antarctique : sept continents fantastiques.',
    audioEn: 'Africa, Europe, Asia, North and South America, Oceania, Antarctica: seven fantastic continents.',
    audioAr: 'أفريقيا وأوروبا وآسيا وأمريكا الشمالية والجنوبية وأوقيانوسيا والقارة القطبية: سبع قارات رائعة.',
    subjects: ['geography', 'continents'], skills: ['memory', 'pronunciation'],
  },
  {
    area: 'science', slug: 'final-science-water-cycle', min: 5, max: 8,
    titleFr: 'La grande aventure d’une goutte', titleEn: 'A drop’s great adventure', titleAr: 'مغامرة قطرة الماء',
    descFr: 'Comprendre le cycle de l’eau avec Pluie, la petite goutte.',
    descEn: 'Understand the water cycle with Drippy, the little drop.',
    descAr: 'افهم دورة الماء مع قطرة الماء الصغيرة.',
    subjects: ['water-cycle', 'weather'], skills: ['observation', 'sequencing'],
  },
  {
    area: 'science', slug: 'final-science-body-team', min: 6, max: 9,
    titleFr: 'Mon corps, une équipe formidable', titleEn: 'My body, an amazing team', titleAr: 'جسمي فريق رائع',
    descFr: 'Le cœur, les poumons et le cerveau expliqués simplement.',
    descEn: 'The heart, lungs, and brain explained simply.',
    descAr: 'شرح مبسط للقلب والرئتين والدماغ.',
    subjects: ['human-body', 'health'], skills: ['scientific-vocabulary', 'self-care'],
  },
  {
    area: 'science', slug: 'final-science-seed-lab', min: 8, max: 10,
    titleFr: 'Le laboratoire des graines', titleEn: 'The seed laboratory', titleAr: 'مختبر البذور',
    descFr: 'Une expérience sûre pour observer la germination.',
    descEn: 'A safe experiment for observing germination.',
    descAr: 'تجربة آمنة لملاحظة إنبات البذور.',
    subjects: ['plants', 'experiment'], skills: ['hypothesis', 'measurement'],
  },
  {
    area: 'geography', slug: 'final-geo-river-journey', min: 4, max: 7,
    titleFr: 'Du ruisseau jusqu’à la mer', titleEn: 'From stream to sea', titleAr: 'من الجدول إلى البحر',
    descFr: 'Suivre une rivière de la montagne à l’océan.',
    descEn: 'Follow a river from the mountain to the ocean.',
    descAr: 'اتبع نهراً من الجبل إلى المحيط.',
    subjects: ['rivers', 'landforms'], skills: ['mapping', 'sequencing'],
  },
  {
    area: 'geography', slug: 'final-geo-map-neighborhood', min: 5, max: 8,
    titleFr: 'La carte de mon quartier', titleEn: 'My neighborhood map', titleAr: 'خريطة حيي',
    descFr: 'Lire une légende, des symboles et les points cardinaux.',
    descEn: 'Read a key, symbols, and cardinal directions.',
    descAr: 'تعلم قراءة مفتاح الخريطة والرموز والاتجاهات.',
    subjects: ['maps', 'community'], skills: ['orientation', 'spatial-reasoning'],
  },
  {
    area: 'geography', slug: 'final-geo-climates-world', min: 8, max: 10,
    titleFr: 'Les climats autour du monde', titleEn: 'Climates around the world', titleAr: 'مناخات حول العالم',
    descFr: 'Comparer déserts, forêts tropicales, régions polaires et tempérées.',
    descEn: 'Compare deserts, rainforests, polar, and temperate regions.',
    descAr: 'قارن بين الصحاري والغابات المطيرة والمناطق القطبية والمعتدلة.',
    subjects: ['climate', 'world'], skills: ['comparison', 'critical-thinking'],
  },
  {
    area: 'creativity', slug: 'final-create-shape-city', min: 3, max: 6,
    titleFr: 'La ville des formes', titleEn: 'The city of shapes', titleAr: 'مدينة الأشكال',
    descFr: 'Créer une ville avec des cercles, carrés et triangles.',
    descEn: 'Create a city with circles, squares, and triangles.',
    descAr: 'أنشئ مدينة من الدوائر والمربعات والمثلثات.',
    subjects: ['shapes', 'visual-arts'], skills: ['imagination', 'fine-motor'],
  },
  {
    area: 'creativity', slug: 'final-create-sound-orchestra', min: 5, max: 8,
    titleFr: 'L’orchestre des objets', titleEn: 'The everyday object orchestra', titleAr: 'أوركسترا الأشياء',
    descFr: 'Explorer rythme et timbre avec des objets sûrs du quotidien.',
    descEn: 'Explore rhythm and tone with safe everyday objects.',
    descAr: 'استكشف الإيقاع والنغمة بأشياء يومية آمنة.',
    subjects: ['music', 'sound'], skills: ['creativity', 'collaboration'],
  },
  {
    area: 'creativity', slug: 'final-create-story-lab', min: 7, max: 10,
    titleFr: 'Le laboratoire des histoires', titleEn: 'The story laboratory', titleAr: 'مختبر الحكايات',
    descFr: 'Inventer un personnage, un lieu, un problème et une solution.',
    descEn: 'Invent a character, setting, problem, and solution.',
    descAr: 'ابتكر شخصية ومكاناً ومشكلة وحلاً.',
    subjects: ['storytelling', 'writing'], skills: ['narrative-thinking', 'expression'],
  },
  {
    area: 'characters', slug: 'final-character-lumi', min: 3, max: 7, character: 'Lumi',
    titleFr: 'Lumi et la bibliothèque brillante', titleEn: 'Lumi and the shining library', titleAr: 'لومي والمكتبة المضيئة',
    descFr: 'Lumi, la luciole premium, rallume les histoires oubliées.',
    descEn: 'Lumi, the premium firefly, relights forgotten stories.',
    descAr: 'لومي، اليراعة المميزة، تعيد الضوء إلى الحكايات المنسية.',
    subjects: ['reading', 'confidence'], skills: ['curiosity', 'empathy'],
  },
  {
    area: 'characters', slug: 'final-character-nova', min: 5, max: 9, character: 'Nova',
    titleFr: 'Nova et la planète des questions', titleEn: 'Nova and the planet of questions', titleAr: 'نوفا وكوكب الأسئلة',
    descFr: 'Nova transforme chaque question scientifique en aventure.',
    descEn: 'Nova turns every science question into an adventure.',
    descAr: 'تحول نوفا كل سؤال علمي إلى مغامرة.',
    subjects: ['science', 'space'], skills: ['inquiry', 'problem-solving'],
  },
  {
    area: 'characters', slug: 'final-character-zayd-maya', min: 6, max: 10, character: 'Zayd & Maya',
    titleFr: 'Zayd et Maya, explorateurs du monde', titleEn: 'Zayd and Maya, world explorers', titleAr: 'زيد ومايا مستكشفا العالم',
    descFr: 'Le duo premium apprend à lire les cartes et respecter les cultures.',
    descEn: 'The premium duo learns to read maps and respect cultures.',
    descAr: 'يتعلم الثنائي المميز قراءة الخرائط واحترام الثقافات.',
    subjects: ['geography', 'cultures'], skills: ['teamwork', 'respect'],
  },
];

function defaultPages(def) {
  const subject = def.subjects[0].replace(/-/g, ' ');
  const skill = def.skills[0].replace(/-/g, ' ');
  return [
    `${def.titleFr} commence par une question simple et une grande envie de découvrir.`,
    `Nos jeunes explorateurs observent, écoutent et cherchent des indices autour d’eux.`,
    `Ils découvrent le thème « ${subject} » avec des mots adaptés à leur âge.`,
    `Une petite difficulté les invite à essayer, comparer et demander de l’aide.`,
    `Ensemble, ils trouvent une solution et exercent leur capacité de ${skill}.`,
    `L’aventure se termine par une idée à retenir et une activité à refaire en famille.`,
  ].map((text) => ({ text }));
}

export function buildFinalExpansionCatalog() {
  return DEFS.map((def, index) => {
    const config = AREA_CONFIG[def.area];
    const type = def.type || config.type;
    const isAudio = type === 'audio_story' || type === 'song';
    return {
      slug: def.slug,
      title: def.titleFr,
      author: AUTHOR,
      description: def.descFr,
      content_type: type,
      language: 'fr',
      theme: config.theme,
      category_name: config.category,
      age_group_min: def.min,
      age_group_max: def.max,
      emoji: def.emoji || config.emoji,
      gradient: pickGradient(index + 7),
      pages: defaultPages(def),
      ...(isAudio ? {
        audio_text: def.audioFr,
        duration_seconds: Math.max(35, Math.round(def.audioFr.length / 11)),
      } : {
        duration_seconds: 240 + index * 7,
      }),
      tags: buildTags({
        level: `${def.min}-${def.max}`,
        theme: config.theme,
        extra: [def.area, ...def.subjects, ...def.skills, ...(def.character ? ['premium-character', def.character.toLowerCase().replace(/\s+/g, '-')] : [])],
        difficulty: def.max <= 6 ? 'easy' : def.min >= 7 ? 'advanced' : 'medium',
        editorial: ['catalog-final', 'curriculum-aligned'],
      }),
      catalog_area: def.area,
      subjects: def.subjects,
      skills: def.skills,
      character: def.character || null,
      series: def.character ? 'Les héros HKids' : null,
      is_premium: def.area === 'characters',
      is_recommended: index % 3 === 0 || def.area === 'characters',
      is_new: true,
      editorial_rank: 80 + (index % 20),
      localizations: buildLocalizations({
        titleEn: def.titleEn,
        descEn: def.descEn,
        titleAr: def.titleAr,
        descAr: def.descAr,
        audioEn: def.audioEn,
        audioAr: def.audioAr,
      }),
    };
  });
}
