import { buildLocalizations, buildTags, cycleAgeBand, pickGradient } from './catalogMeta.js';

const AUTHOR = 'Le Lit Qui Lit';

function audioStoryItem(index, config) {
  const age = cycleAgeBand(index);
  const slug = config.slug || `audio-${String(index + 1).padStart(2, '0')}-${config.theme}`;
  return {
    slug,
    title: config.title,
    author: AUTHOR,
    description: config.description || `Une histoire audio douce pour ${age.level} ans.`,
    content_type: config.content_type || 'audio_story',
    language: 'fr',
    theme: config.theme,
    category_name: config.category_name || 'Histoires',
    age_group_min: config.age_min ?? age.min,
    age_group_max: config.age_max ?? age.max,
    emoji: config.emoji,
    gradient: config.gradient || pickGradient(index),
    audio_text: config.audio_text,
    duration_seconds: config.duration_seconds || 12,
    tags: config.tags || buildTags({
      level: age.level,
      theme: config.theme,
      extra: config.extraTags || [],
      difficulty: config.difficulty || 'easy',
      editorial: config.editorial || [],
    }),
    is_recommended: Boolean(config.is_recommended),
    is_popular: Boolean(config.is_popular),
    is_new: Boolean(config.is_new),
    localizations: buildLocalizations({
      titleEn: config.titleEn,
      descEn: config.descEn,
      titleAr: config.titleAr,
      descAr: config.descAr,
      audioEn: config.audioEn,
      audioAr: config.audioAr,
    }),
  };
}

const AUDIO_STORY_DEFS = [
  { title: 'Le dino qui murmure', theme: 'dinosaurs', emoji: '🦖', category_name: 'Dinosaures',
    audio_text: 'Petit dino au coeur doux, tu es courageux ce soir. Ferme les yeux, respire, tout va bien.',
    titleEn: 'The whispering dino', descEn: 'A gentle audio story for little ones.',
    titleAr: 'الديناصور الهامس', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Little dino with a gentle heart, you are brave tonight. Close your eyes, breathe, all is well.',
    audioAr: 'أيها الديناصور الصغير ذو القلب الحنون، أنت شجاع الليلة. أغمض عينيك، تنفس، كل شيء على ما يرام.',
  },
  { title: 'La fusee des reves', theme: 'space', emoji: '🚀', category_name: 'Espace',
    audio_text: 'La fusee vole parmi les etoiles. Chaque lumiere est un reve qui t attend.',
    titleEn: 'The rocket of dreams', descEn: 'A gentle audio story for little ones.',
    titleAr: 'صاروخ الأحلام', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The rocket flies among the stars. Each light is a dream waiting for you.',
    audioAr: 'الصاروخ يطير بين النجوم. كل ضوء هو حلم ينتظرك.',
  },
  { title: 'Mimi chat et la lune', theme: 'animals', emoji: '🐱', category_name: 'Animaux',
    audio_text: 'Mimi chat regarde la lune. Elle ronronne doucement. Bonne nuit petit chat.',
    titleEn: 'Mimi cat and the moon', descEn: 'A gentle audio story for little ones.',
    titleAr: 'ميمي القطة والقمر', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Mimi cat looks at the moon. She purrs softly. Good night little cat.',
    audioAr: 'ميمي القطة تنظر إلى القمر. تخرخر بهدوء. تصبحين على خير يا قطتي الصغيرة.',
  },
  { title: 'La princesse des etoiles', theme: 'princesses', emoji: '👸', category_name: 'Histoires',
    audio_text: 'La princesse tisse des etoiles dans le ciel. Elle veille sur ton sommeil.',
    titleEn: 'The princess of stars', descEn: 'A gentle audio story for little ones.',
    titleAr: 'أميرة النجوم', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The princess weaves stars in the sky. She watches over your sleep.',
    audioAr: 'الأميرة تنسج النجوم في السماء. إنها تسهر على نومك.',
  },
  { title: 'Sami le pompier', theme: 'jobs', emoji: '🚒', category_name: 'Histoires',
    audio_text: 'Sami aide avec gentillesse. Il protege tout le monde. Bravo petit heros.',
    titleEn: 'Sami the firefighter', descEn: 'A gentle audio story for little ones.',
    titleAr: 'سامي رجل الإطفاء', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Sami helps with kindness. He protects everyone. Bravo little hero.',
    audioAr: 'سامي يساعد بلطف. يحمي الجميع. أحسنت أيها البطل الصغير.',
  },
  { title: 'Le bateau des decouvertes', theme: 'world', emoji: '🌍', category_name: 'Contes',
    audio_text: 'Le bateau traverse les mers calmes. Chaque ile est une nouvelle amitie.',
    titleEn: 'The boat of discoveries', descEn: 'A gentle audio story for little ones.',
    titleAr: 'قارب الاكتشافات', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The boat crosses calm seas. Each island is a new friendship.',
    audioAr: 'القارب يعبر البحار الهادئة. كل جزيرة هي صداقة جديدة.',
  },
  { title: 'Foret enchantee', theme: 'nature', emoji: '🌲', category_name: 'Contes',
    audio_text: 'Les arbres murmurent une berceuse. Les feuilles dansent au vent doux.',
    titleEn: 'Enchanted forest', descEn: 'A gentle audio story for little ones.',
    titleAr: 'الغابة المسحورة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The trees whisper a lullaby. The leaves dance in the gentle wind.',
    audioAr: 'الأشجار تهمس بتهويدة. الأوراق ترقص في الريح الناعمة.',
  },
  { title: 'Les amis du jardin', theme: 'animals', emoji: '🐰', category_name: 'Animaux',
    audio_text: 'Lapin, herisson et oiseau partagent le gouter. Ils rient ensemble.',
    titleEn: 'The garden friends', descEn: 'A gentle audio story for little ones.',
    titleAr: 'أصدقاء الحديقة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Rabbit, hedgehog, and bird share a snack. They laugh together.',
    audioAr: 'الأرنب والقنفذ والعصفور يتشاركون وجبة خفيفة. يضحكون معاً.',
  },
  { title: 'Le robot curieux', theme: 'world', emoji: '🤖', category_name: 'Histoires',
    audio_text: 'Le petit robot apprend a sourire. Il decouvre que l amitie est magique.',
    titleEn: 'The curious robot', descEn: 'A gentle audio story for little ones.',
    titleAr: 'الروبوت الفضولي', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The little robot learns to smile. He discovers that friendship is magical.',
    audioAr: 'الروبوت الصغير يتعلم الابتسام. يكتشف أن الصداقة سحرية.',
  },
  { title: 'La fee du sommeil', theme: 'princesses', emoji: '🧚', category_name: 'Histoires',
    audio_text: 'La fee du sommeil pose des paillettes dorees sur tes paupieres.',
    titleEn: 'The sleep fairy', descEn: 'A gentle audio story for little ones.',
    titleAr: 'جنية النوم', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The sleep fairy places golden sparkles on your eyelids.',
    audioAr: 'جنية النوم تضع بريقاً ذهبياً على جفونك.',
  },
  { title: 'Le pirate gentil', theme: 'world', emoji: '🏴‍☠️', category_name: 'Contes',
    audio_text: 'Le pirate partage son tresor de rires. Sa carte mene aux reves bleus.',
    titleEn: 'The kind pirate', descEn: 'A gentle audio story for little ones.',
    titleAr: 'القرصان اللطيف', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The pirate shares his treasure of laughter. His map leads to blue dreams.',
    audioAr: 'القرصان يشارك كنزه من الضحكات. خريطته تقود إلى أحلام زرقاء.',
  },
  { title: 'Nuages tout doux', theme: 'nature', emoji: '☁️', category_name: 'Histoires',
    audio_text: 'Les nuages sont des oreillers geants. Pose ta tete et flotte tout doux.',
    titleEn: 'Soft clouds', descEn: 'A gentle audio story for little ones.',
    titleAr: 'غيوم ناعمة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Clouds are giant pillows. Rest your head and float gently.',
    audioAr: 'الغيوم وسائد عملاقة. ضع رأسك وطِف بهدوء.',
  },
  { title: 'Le train des couleurs', theme: 'colors', emoji: '🌈', category_name: 'Histoires',
    audio_text: 'Rouge, bleu, jaune, vert. Le train des couleurs s endort au terminus.',
    titleEn: 'The color train', descEn: 'A gentle audio story for little ones.',
    titleAr: 'قطار الألوان', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'Red, blue, yellow, green. The color train falls asleep at the last stop.',
    audioAr: 'أحمر، أزرق، أصفر، أخضر. قطار الألوان ينام في المحطة الأخيرة.',
  },
  { title: 'Compte les lucioles', theme: 'numbers', emoji: '✨', category_name: 'Histoires',
    audio_text: 'Une, deux, trois lucioles brillent. Quatre, cinq, six etoiles dansent.',
    titleEn: 'Count the fireflies', descEn: 'A gentle audio story for little ones.',
    titleAr: 'عدّ اليراعات', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'One, two, three fireflies glow. Four, five, six stars dance.',
    audioAr: 'واحدة، اثنتان، ثلاث يراعات تتوهج. أربع، خمس، ست نجوم ترقص.',
  },
  { title: 'ABC du ciel', theme: 'alphabet', emoji: '🔤', category_name: 'Histoires',
    audio_text: 'A comme Astre, B comme Brise, C comme Calme. Bonne nuit alphabet.',
    titleEn: 'ABC of the sky', descEn: 'A gentle audio story for little ones.',
    titleAr: 'أبجدية السماء', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'A for Star, B for Breeze, C for Calm. Good night alphabet.',
    audioAr: 'ألف كالنجم، باء كالنسيم، تاء كالهدوء. تصبح على خير يا أبجدية.',
  },
  { title: 'Le dragon qui peint', theme: 'dinosaurs', emoji: '🐉', category_name: 'Dinosaures',
    audio_text: 'Le dragon peint des arcs-en-ciel. Chaque couleur est un bisou du soir.',
    titleEn: 'The painting dragon', descEn: 'A gentle audio story for little ones.',
    titleAr: 'التنين الرسام', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The dragon paints rainbows. Each color is a goodnight kiss.',
    audioAr: 'التنين يرسم أقواس قزح. كل لون هو قبلة مساء.',
  },
  { title: 'L astronaute timide', theme: 'space', emoji: '👨‍🚀', category_name: 'Espace',
    audio_text: 'L astronaute timide decouvre sa lumiere interieure. Il brille tres fort.',
    titleEn: 'The shy astronaut', descEn: 'A gentle audio story for little ones.',
    titleAr: 'رائد الفضاء الخجول', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The shy astronaut discovers his inner light. He shines so bright.',
    audioAr: 'رائد الفضاء الخجول يكتشف نوره الداخلي. يلمع بقوة.',
  },
  { title: 'La tortue patiente', theme: 'animals', emoji: '🐢', category_name: 'Animaux',
    audio_text: 'La tortue avance doucement. Elle sait que demain sera beau.',
    titleEn: 'The patient turtle', descEn: 'A gentle audio story for little ones.',
    titleAr: 'السلحفاة الصبورة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The turtle moves slowly. She knows tomorrow will be beautiful.',
    audioAr: 'السلحفاة تتقدم بهدوء. تعلم أن الغد سيكون جميلاً.',
  },
  { title: 'Le chateau de sable', theme: 'princesses', emoji: '🏰', category_name: 'Contes',
    audio_text: 'Un chateau de sable au bord de la mer. Les vagues chantent une berceuse.',
    titleEn: 'The sandcastle', descEn: 'A gentle audio story for little ones.',
    titleAr: 'قلعة الرمل', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'A sandcastle by the sea. The waves sing a lullaby.',
    audioAr: 'قلعة رمل على شاطئ البحر. الأمواج تغني تهويدة.',
  },
  { title: 'Le marchand de sourires', theme: 'world', emoji: '😊', category_name: 'Contes',
    audio_text: 'Le marchand offre des sourires gratuits. Prends-en un pour ce soir.',
    titleEn: 'The smile merchant', descEn: 'A gentle audio story for little ones.',
    titleAr: 'بائع الابتسامات', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The merchant gives free smiles. Take one for tonight.',
    audioAr: 'البائع يوزع ابتسامات مجانية. خذ واحدة لهذه الليلة.',
  },
  { title: 'La riviere qui chante', theme: 'nature', emoji: '💧', category_name: 'Histoires',
    audio_text: 'La riviere chante plouf plouf. Les poissons dansent sous la lune.',
    titleEn: 'The singing river', descEn: 'A gentle audio story for little ones.',
    titleAr: 'النهر الذي يغني', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The river sings splash splash. The fish dance under the moon.',
    audioAr: 'النهر يغني بلوب بلوب. الأسماك ترقص تحت القمر.',
  },
  { title: 'Le loup et la lumiere', theme: 'world', emoji: '🐺', category_name: 'Contes',
    audio_text: 'Le loup trouve une lanterne chaude. Il guide les petits vers le sommeil.',
    titleEn: 'The wolf and the light', descEn: 'A gentle audio story for little ones.',
    titleAr: 'الذئب والضوء', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The wolf finds a warm lantern. He guides the little ones to sleep.',
    audioAr: 'الذئب يجد فانوساً دافئاً. يرشد الصغار نحو النوم.',
  },
  { title: 'La licorne reveuse', theme: 'princesses', emoji: '🦄', category_name: 'Histoires',
    audio_text: 'La licorne reveuse galope sur les nuages roses. Elle t emmene au pays calme.',
    titleEn: 'The dreamy unicorn', descEn: 'A gentle audio story for little ones.',
    titleAr: 'وحيدة القرن الحالمة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The dreamy unicorn gallops on pink clouds. She takes you to the land of calm.',
    audioAr: 'وحيدة القرن الحالمة تركض فوق الغيوم الوردية. تأخذك إلى بلاد الهدوء.',
  },
  { title: 'Le petit train du soir', theme: 'jobs', emoji: '🚂', category_name: 'Histoires',
    audio_text: 'Le train du soir traverse la campagne. Tchou tchou, dodo les voyageurs.',
    titleEn: 'The little evening train', descEn: 'A gentle audio story for little ones.',
    titleAr: 'قطار المساء الصغير', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The evening train crosses the countryside. Choo choo, sleepy passengers.',
    audioAr: 'قطار المساء يعبر الريف. توت توت، نام المسافرون.',
  },
  { title: 'Les pingouins rigolos', theme: 'animals', emoji: '🐧', category_name: 'Animaux',
    audio_text: 'Les pingouins glissent sur la glace. Ils applaudissent la nuit etoilee.',
    titleEn: 'The funny penguins', descEn: 'A gentle audio story for little ones.',
    titleAr: 'البطاريق المرحة', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'The penguins slide on the ice. They applaud the starry night.',
    audioAr: 'البطاريق تنزلق على الجليد. تصفق لليلة المرصعة بالنجوم.',
  },
  { title: 'La planete des bisous', theme: 'space', emoji: '🪐', category_name: 'Espace',
    audio_text: 'Sur la planete des bisous, tout le monde dit bonne nuit en souriant.',
    titleEn: 'The planet of kisses', descEn: 'A gentle audio story for little ones.',
    titleAr: 'كوكب القبلات', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'On the planet of kisses, everyone says good night with a smile.',
    audioAr: 'على كوكب القبلات، الجميع يقول تصبح على خير بابتسامة.',
  },
  { title: 'Le jardin secret', theme: 'nature', emoji: '🌷', category_name: 'Histoires',
    audio_text: 'Dans le jardin secret, les fleurs ferment leurs petales. Silence et douceur.',
    titleEn: 'The secret garden', descEn: 'A gentle audio story for little ones.',
    titleAr: 'الحديقة السرية', descAr: 'قصة صوتية هادئة للصغار.',
    audioEn: 'In the secret garden, flowers close their petals. Silence and softness.',
    audioAr: 'في الحديقة السرية، الأزهار تغلق بتلاتها. صمت وهدوء.',
  },
];

const COMPTINE_DEFS = [
  { title: 'Pomme et poire', emoji: '🍎', theme: 'rhymes',
    audio_text: 'Pomme et poire, poire et pomme, dans mon panier tout est bon.',
    titleEn: 'Apple and pear', descEn: 'A sweet nursery rhyme.',
    titleAr: 'تفاحة وإجاصة', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Apple and pear, pear and apple, in my basket all is good.',
    audioAr: 'تفاحة وإجاصة، إجاصة وتفاحة، في سلتي كل شيء طيب.',
  },
  { title: 'Petit canard', emoji: '🦆', theme: 'animals',
    audio_text: 'Coin coin dit le canard, il nage dans l etang tout doux.',
    titleEn: 'Little duck', descEn: 'A sweet nursery rhyme.',
    titleAr: 'البطة الصغيرة', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Quack quack says the duck, he swims in the gentle pond.',
    audioAr: 'كواك كواك تقول البطة، تسبح في البركة الهادئة.',
  },
  { title: 'Les roues du bus', emoji: '🚌', theme: 'rhymes',
    audio_text: 'Les roues du bus tournent, tournent, tournent, dans la ville calme.',
    titleEn: 'The wheels of the bus', descEn: 'A sweet nursery rhyme.',
    titleAr: 'عجلات الحافلة', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'The wheels of the bus go round and round, through the quiet town.',
    audioAr: 'عجلات الحافلة تدور وتدور وتدور، في المدينة الهادئة.',
  },
  { title: 'Mon petit lapin', emoji: '🐇', theme: 'animals',
    audio_text: 'Mon petit lapin saute saute saute, dans le jardin vert.',
    titleEn: 'My little rabbit', descEn: 'A sweet nursery rhyme.',
    titleAr: 'أرنبي الصغير', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'My little rabbit hops hops hops, in the green garden.',
    audioAr: 'أرنبي الصغير يقفز يقفز يقفز، في الحديقة الخضراء.',
  },
  { title: 'Pluie et arc-en-ciel', emoji: '🌧️', theme: 'colors',
    audio_text: 'Pluie fine, arc-en-ciel, rouge bleu jaune, quel beau soleil.',
    titleEn: 'Rain and rainbow', descEn: 'A sweet nursery rhyme.',
    titleAr: 'المطر وقوس قزح', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Fine rain, rainbow, red blue yellow, what a lovely sun.',
    audioAr: 'مطر خفيف، قوس قزح، أحمر أزرق أصفر، يا لها من شمس جميلة.',
  },
  { title: 'Bateau sur l eau', emoji: '⛵', theme: 'world',
    audio_text: 'Bateau sur l eau, il danse, il danse, au rythme des vagues.',
    titleEn: 'Boat on the water', descEn: 'A sweet nursery rhyme.',
    titleAr: 'قارب على الماء', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Boat on the water, it dances, it dances, to the rhythm of the waves.',
    audioAr: 'قارب على الماء، يرقص، يرقص، على إيقاع الأمواج.',
  },
  { title: 'Les cinq doigts', emoji: '🖐️', theme: 'numbers',
    audio_text: 'Pouce, index, majeur, annulaire, auriculaire, cinq doigts joyeux.',
    titleEn: 'The five fingers', descEn: 'A sweet nursery rhyme.',
    titleAr: 'الأصابع الخمسة', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Thumb, index, middle, ring, pinky, five happy fingers.',
    audioAr: 'إبهام، سبابة، وسطى، بنصر، خنصر، خمس أصابع سعيدة.',
  },
  { title: 'La poule pon pon', emoji: '🐔', theme: 'animals',
    audio_text: 'La poule fait pon pon, le coq fait cocorico, bonjour la ferme.',
    titleEn: 'The clucking hen', descEn: 'A sweet nursery rhyme.',
    titleAr: 'الدجاجة كوك كوك', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'The hen goes cluck cluck, the rooster goes cock-a-doodle-doo, hello farm.',
    audioAr: 'الدجاجة تقول قوق قوق، الديك يقول كوكوكوكو، صباح الخير يا مزرعة.',
  },
  { title: 'Danse des etoiles', emoji: '⭐', theme: 'space',
    audio_text: 'Les etoiles dansent une, deux, trois, tourne tourne petit bras.',
    titleEn: 'Dance of the stars', descEn: 'A sweet nursery rhyme.',
    titleAr: 'رقصة النجوم', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'The stars dance one, two, three, spin spin little arms.',
    audioAr: 'النجوم ترقص واحد، اثنان، ثلاثة، دُر دُر يا ذراعي الصغيرتين.',
  },
  { title: 'Bonjour les fleurs', emoji: '🌸', theme: 'nature',
    audio_text: 'Bonjour les fleurs, bonjour le vent, bonjour le jardin enchante.',
    titleEn: 'Hello flowers', descEn: 'A sweet nursery rhyme.',
    titleAr: 'مرحباً يا أزهار', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Hello flowers, hello wind, hello enchanted garden.',
    audioAr: 'مرحباً يا أزهار، مرحباً يا ريح، مرحباً يا حديقة مسحورة.',
  },
  { title: 'Le petit poisson', emoji: '🐠', theme: 'animals',
    audio_text: 'Nage nage petit poisson, dans l eau claire et bleue.',
    titleEn: 'The little fish', descEn: 'A sweet nursery rhyme.',
    titleAr: 'السمكة الصغيرة', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Swim swim little fish, in the clear blue water.',
    audioAr: 'اسبحي اسبحي يا سمكة صغيرة، في الماء الصافي الأزرق.',
  },
  { title: 'Tap tap les mains', emoji: '👏', theme: 'rhymes',
    audio_text: 'Tap tap les mains, clap clap les mains, on fait la fete ensemble.',
    titleEn: 'Clap clap hands', descEn: 'A sweet nursery rhyme.',
    titleAr: 'صفق صفق يا يدين', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Clap clap your hands, tap tap your hands, we celebrate together.',
    audioAr: 'صفق صفق يا يدين، طق طق يا يدين، نحتفل معاً.',
  },
  { title: 'La vache meuh', emoji: '🐄', theme: 'animals',
    audio_text: 'La vache fait meuh, le mouton beee, la ferme chante doucement.',
    titleEn: 'The moo cow', descEn: 'A sweet nursery rhyme.',
    titleAr: 'البقرة مووو', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'The cow goes moo, the sheep goes baa, the farm sings softly.',
    audioAr: 'البقرة تقول مووو، الخروف يقول ماع، المزرعة تغني بهدوء.',
  },
  { title: 'Vent et feuilles', emoji: '🍃', theme: 'nature',
    audio_text: 'Le vent souffle, les feuilles dansent, chuuuut, tout se repose.',
    titleEn: 'Wind and leaves', descEn: 'A sweet nursery rhyme.',
    titleAr: 'الريح والأوراق', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'The wind blows, the leaves dance, shhhh, everything rests.',
    audioAr: 'الريح تهب، الأوراق ترقص، شششش، كل شيء يرتاح.',
  },
  { title: 'Mon ami le soleil', emoji: '☀️', theme: 'rhymes',
    audio_text: 'Mon ami le soleil se couche, bonne nuit, a demain matin.',
    titleEn: 'My friend the sun', descEn: 'A sweet nursery rhyme.',
    titleAr: 'صديقي الشمس', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'My friend the sun goes to bed, good night, see you tomorrow morning.',
    audioAr: 'صديقتي الشمس تنام، تصبح على خير، إلى الغد صباحاً.',
  },
  { title: 'Les abeilles', emoji: '🐝', theme: 'animals',
    audio_text: 'Bzzz bzzz les abeilles, butinent les fleurs du matin.',
    titleEn: 'The bees', descEn: 'A sweet nursery rhyme.',
    titleAr: 'النحلات', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Buzz buzz the bees, sipping nectar from the morning flowers.',
    audioAr: 'طنّ طنّ النحلات، ترتشف رحيق أزهار الصباح.',
  },
  { title: 'Comptine des formes', emoji: '🔺', theme: 'shapes',
    audio_text: 'Rond comme le soleil, carre comme la fenetre, triangle comme la montagne.',
    titleEn: 'Shapes rhyme', descEn: 'A sweet nursery rhyme.',
    titleAr: 'أنشودة الأشكال', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Round like the sun, square like the window, triangle like the mountain.',
    audioAr: 'دائري كالشمس، مربع كالنافذة، مثلث كالجبل.',
  },
  { title: 'La berceuse du loup', emoji: '🌙', theme: 'rhymes',
    audio_text: 'Dodo loup gentil, la lune veille, les etoiles brillent pour toi.',
    titleEn: 'The wolf\'s lullaby', descEn: 'A sweet nursery rhyme.',
    titleAr: 'تهويدة الذئب', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'Sleep gentle wolf, the moon watches, the stars shine for you.',
    audioAr: 'نم أيها الذئب اللطيف، القمر يسهر، النجوم تلمع من أجلك.',
  },
  { title: 'Chanson du marche', emoji: '🛒', theme: 'world',
    audio_text: 'Au marche on chante, pommes poires et sourires partout.',
    titleEn: 'Market song', descEn: 'A sweet nursery rhyme.',
    titleAr: 'أغنية السوق', descAr: 'أنشودة لطيفة للأطفال.',
    audioEn: 'At the market we sing, apples pears and smiles everywhere.',
    audioAr: 'في السوق نغني، تفاح وإجاص وابتسامات في كل مكان.',
  },
];

const RELIGIOUS_DEFS = [
  { title: 'La gratitude du soir',
    audio_text: 'Merci pour cette belle journee. Merci pour les gens qui m aiment. Bonne nuit.',
    titleEn: 'Evening gratitude', descEn: 'A values bedtime story.',
    titleAr: 'امتنان المساء', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Thank you for this beautiful day. Thank you for the people who love me. Good night.',
    audioAr: 'شكراً على هذا اليوم الجميل. شكراً للناس الذين يحبونني. تصبحون على خير.',
  },
  { title: 'Noe et les animaux',
    audio_text: 'Noe accueille chaque animal avec amour. L arche est un refuge de paix.',
    titleEn: 'Noah and the animals', descEn: 'A values bedtime story.',
    titleAr: 'نوح والحيوانات', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Noah welcomes each animal with love. The ark is a refuge of peace.',
    audioAr: 'نوح يستقبل كل حيوان بحب. السفينة ملجأ من السلام.',
  },
  { title: 'Le partage du pain',
    audio_text: 'Partager rend le coeur leger. Un morceau pour toi, un morceau pour moi.',
    titleEn: 'Sharing bread', descEn: 'A values bedtime story.',
    titleAr: 'مشاركة الخبز', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Sharing makes the heart light. A piece for you, a piece for me.',
    audioAr: 'المشاركة تجعل القلب خفيفاً. قطعة لك، وقطعة لي.',
  },
  { title: 'La lumiere dans la nuit',
    audio_text: 'Quand il fait noir, une petite lumiere guide nos pas avec douceur.',
    titleEn: 'The light in the night', descEn: 'A values bedtime story.',
    titleAr: 'النور في الليل', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'When it is dark, a small light gently guides our steps.',
    audioAr: 'عندما يحلّ الظلام، نور صغير يرشد خطانا بلطف.',
  },
  { title: 'Jonas et la baleine',
    audio_text: 'Jonas apprend a ecouter et a faire confiance. La mer l berce calmement.',
    titleEn: 'Jonah and the whale', descEn: 'A values bedtime story.',
    titleAr: 'يونس والحوت', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Jonah learns to listen and to trust. The sea rocks him calmly.',
    audioAr: 'يونس يتعلم الإصغاء والثقة. البحر يهدهده بهدوء.',
  },
  { title: 'Les valeurs du jardin',
    audio_text: 'Dans le jardin, on seme la gentillesse. Elle pousse comme une fleur.',
    titleEn: 'The garden\'s values', descEn: 'A values bedtime story.',
    titleAr: 'قيم الحديقة', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'In the garden, we plant kindness. It grows like a flower.',
    audioAr: 'في الحديقة، نزرع اللطف. ينمو كالزهرة.',
  },
  { title: 'Le berger attentif',
    audio_text: 'Le bon berger veille sur chaque brebis. Personne n est oublie.',
    titleEn: 'The caring shepherd', descEn: 'A values bedtime story.',
    titleAr: 'الراعي الحنون', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'The good shepherd watches over every lamb. No one is forgotten.',
    audioAr: 'الراعي الطيب يسهر على كل خروف. لا أحد يُنسى.',
  },
  { title: 'La patience de Joseph',
    audio_text: 'Joseph attend avec courage. Chaque jour apporte un nouveau cadeau.',
    titleEn: 'Joseph\'s patience', descEn: 'A values bedtime story.',
    titleAr: 'صبر يوسف', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Joseph waits with courage. Each day brings a new gift.',
    audioAr: 'يوسف ينتظر بشجاعة. كل يوم يحمل هدية جديدة.',
  },
  { title: 'Merci maman merci papa',
    audio_text: 'Merci pour les calins, merci pour les histoires, merci pour l amour.',
    titleEn: 'Thank you mom thank you dad', descEn: 'A values bedtime story.',
    titleAr: 'شكراً ماما شكراً بابا', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'Thank you for the hugs, thank you for the stories, thank you for the love.',
    audioAr: 'شكراً على الأحضان، شكراً على القصص، شكراً على الحب.',
  },
  { title: 'Les anges veillent',
    audio_text: 'Les anges veillent sur ton sommeil. Tu es protege et aime.',
    titleEn: 'The angels watch over', descEn: 'A values bedtime story.',
    titleAr: 'الملائكة تسهر', descAr: 'قصة قيم قبل النوم.',
    audioEn: 'The angels watch over your sleep. You are protected and loved.',
    audioAr: 'الملائكة تسهر على نومك. أنت محمي ومحبوب.',
  },
];

export function buildExtendedAudioStories() {
  return AUDIO_STORY_DEFS.map((def, index) => audioStoryItem(index, {
    ...def,
    slug: `audio-${def.theme}-${String(index + 1).padStart(2, '0')}`,
    is_recommended: index % 7 === 0,
    is_popular: index % 5 === 0,
    is_new: index % 9 === 0,
  }));
}

export function buildExtendedComptines() {
  return COMPTINE_DEFS.map((def, index) => {
    const age = cycleAgeBand(index + 2);
    return audioStoryItem(index + 40, {
      ...def,
      slug: `comptine-${String(index + 1).padStart(2, '0')}`,
      content_type: 'song',
      category_name: 'Comptines',
      is_popular: index % 4 === 0,
      is_new: index % 6 === 0,
      tags: buildTags({
        level: age.level,
        theme: def.theme,
        extra: ['comptine', 'rhyme', 'song'],
        difficulty: 'easy',
      }),
    });
  });
}

export function buildReligiousStories() {
  return RELIGIOUS_DEFS.map((def, index) => {
    const age = cycleAgeBand(index + 1);
    return audioStoryItem(index + 60, {
      ...def,
      slug: `spiritual-${String(index + 1).padStart(2, '0')}`,
      theme: 'spiritual',
      category_name: 'Spiritualite',
      emoji: '🕊️',
      extraTags: ['religious', 'values', 'bedtime'],
      is_recommended: index % 2 === 0,
    });
  });
}

export function buildExtendedCatalog() {
  return [
    ...buildExtendedAudioStories(),
    ...buildExtendedComptines(),
    ...buildReligiousStories(),
  ];
}
