/** Demo customizable story templates seeded into generated_stories. */

export const STORY_TEMPLATES = [
  {
    slug: 'template-dragon-amitie',
    title: 'Mon dragon ami',
    theme: 'magie',
    age_level: '5-7',
    language: 'fr',
    characters: ['un dragon', 'un enfant'],
    summary: 'Une histoire a personnaliser sur l amitie avec un dragon.',
    story_text: 'Il etait une fois un enfant courageux qui rencontra un dragon tout doux. Ensemble, ils apprirent que l amitie rend le coeur plus fort. Ce soir, le dragon veille sur tes reves.',
    prompt_metadata: { customizable: true, is_demo_template: true, suggested_themes: ['magie', 'amitie'], placeholders: ['prenom', 'animal_prefere'] },
  },
  {
    slug: 'template-fusee-espace',
    title: 'Ma fusee vers les etoiles',
    theme: 'espace',
    age_level: '5-7',
    language: 'fr',
    characters: ['un astronaute', 'un robot'],
    summary: 'Personnalise un voyage dans l espace.',
    story_text: 'Une fusee douce decolle vers les etoiles. Chaque etoile murmure un secret joyeux. Tu es le capitaine de cette aventure calme.',
    prompt_metadata: { customizable: true, is_demo_template: true, suggested_themes: ['espace'], placeholders: ['prenom', 'planete_preferee'] },
  },
  {
    slug: 'template-princesse-courage',
    title: 'La princesse courageuse',
    theme: 'princesses',
    age_level: '5-7',
    language: 'fr',
    characters: ['une princesse', 'une fee'],
    summary: 'Une princesse qui apprend a etre brave.',
    story_text: 'La princesse decouvrit que le courage vit dans son coeur. Avec sa fee amie, elle illumina le chateau de sourires.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'couleur_preferee'] },
  },
  {
    slug: 'template-dino-nuit',
    title: 'Le dino de la bonne nuit',
    theme: 'dinosaures',
    age_level: '2-4',
    language: 'fr',
    characters: ['un dinosaure'],
    summary: 'Histoire du soir avec un dinosaure gentil.',
    story_text: 'Le petit dinosaure ferma les yeux sous les etoiles. Il savait qu il etait aime. Bonne nuit petit dino.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom'] },
  },
  {
    slug: 'template-animaux-foret',
    title: 'Mes amis de la foret',
    theme: 'animaux',
    age_level: '2-4',
    language: 'fr',
    characters: ['un lapin', 'un ours'],
    summary: 'Aventures douces avec des animaux.',
    story_text: 'Dans la foret, le lapin et l ours partagerent un gouter de baies. Ils rirent jusqu au coucher du soleil.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'animal_prefere'] },
  },
  {
    slug: 'template-pirate-tresor',
    title: 'Le tresor des sourires',
    theme: 'aventure',
    age_level: '8-10',
    language: 'fr',
    characters: ['un pirate', 'un perroquet'],
    summary: 'Un pirate gentil cherche un tresor special.',
    story_text: 'Le pirate gentil trouva un coffre plein de sourires. Il en offrit un a chaque ami rencontre sur son bateau.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'lieu_prefere'] },
  },
  {
    slug: 'template-robot-ecole',
    title: 'Le robot a l ecole',
    theme: 'aventure',
    age_level: '8-10',
    language: 'fr',
    characters: ['un robot', 'un enfant'],
    summary: 'Un robot apprend les emotions a l ecole.',
    story_text: 'Le robot decouvrit la joie, la patience et l entraide. Son coeur de metal brillait de chaleur.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'matiere_preferee'] },
  },
  {
    slug: 'template-fee-couleurs',
    title: 'La fee des couleurs',
    theme: 'magie',
    age_level: '2-4',
    language: 'fr',
    characters: ['une fee'],
    summary: 'Apprendre les couleurs avec une fee.',
    story_text: 'La fee peignit le ciel en rose, bleu et jaune. Chaque couleur etait un bisou du soir.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'couleur_preferee'] },
  },
  {
    slug: 'template-gratitude',
    title: 'Merci pour aujourd hui',
    theme: 'spiritual',
    age_level: '5-7',
    language: 'fr',
    characters: ['un enfant'],
    summary: 'Histoire de gratitude a personnaliser.',
    story_text: 'Avant de dormir, l enfant dit merci pour la journee, la famille et les reves a venir.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'personne_aimee'] },
  },
  {
    slug: 'template-super-heros',
    title: 'Mon super pouvoir',
    theme: 'aventure',
    age_level: '8-10',
    language: 'fr',
    characters: ['un super heros'],
    summary: 'Decouvre ton super pouvoir unique.',
    story_text: 'Chaque enfant a un super pouvoir secret : la gentillesse. Ce soir, il sauve la journee avec un sourire.',
    prompt_metadata: { customizable: true, is_demo_template: true, placeholders: ['prenom', 'super_pouvoir'] },
  },
];
